import type { Lab, Phase, GitHubProject, GitHubProjectFile } from '../types';

/** Same slug used for a lab's own repo and for its entry in the portfolio index. */
export function repoNameFor(lab: Lab): string {
  return lab.title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

export function generateProject(lab: Lab): GitHubProject {
  const repoName = repoNameFor(lab);

  const files: GitHubProjectFile[] = [
    {
      path: 'README.md',
      content: labReadme(lab),
    },
    {
      path: 'architecture/overview.md',
      content: labArchitecture(lab),
    },
    {
      path: 'configs/README.md',
      content: labConfigsReadme(lab),
    },
    {
      path: 'screenshots/README.md',
      content: labScreenshotsReadme(lab),
    },
    {
      path: 'evidence/README.md',
      content: labEvidenceReadme(lab),
    },
    {
      path: 'logs/README.md',
      content: labLogsReadme(lab),
    },
    {
      path: 'reports/README.md',
      content: labReportsReadme(lab),
    },
    {
      path: 'troubleshooting/README.md',
      content: labTroubleshootingReadme(lab),
    },
    {
      path: 'lessons-learned/README.md',
      content: labLessonsLearned(lab),
    },
  ];

  return {
    labId: lab.id,
    repoName,
    files,
    generatedAt: Date.now(),
  };
}

export function serializeProject(project: GitHubProject): string {
  return JSON.stringify(project, null, 2);
}

function labReadme(lab: Lab): string {
  return `# ${lab.title}

## Overview
This is a generated GitHub project for the Security+ Zero-to-Hero 3D Lab Platform.

**Lab ID:** \`${lab.id}\`
**Phase:** ${lab.phaseId}

## Objective
${lab.objective}

## Security Concepts
${lab.securityConcepts.map((c) => `- ${c}`).join('\n')}

## Technologies
${labTechnologies(lab)}

## Environment
${lab.environment}

## Architecture / Topology
${lab.topology}

## Prerequisites
${lab.prerequisites.map((p) => `- ${p}`).join('\n')}

## Step-by-Step Instructions
${lab.steps.map((s, i) => `${i + 1}. ${s.instruction}`).join('\n')}

## Expected Results
${lab.expectedResults.map((r) => `- ${r}`).join('\n')}

## Verification
${lab.verification.map((v) => `- ${v}`).join('\n')}

## Troubleshooting
${lab.troubleshooting.map((t) => `- ${t}`).join('\n')}

## Challenge
${lab.challenge ?? 'None'}

## Evidence
${lab.evidence.map((e) => `- ${e.label} (${e.type})`).join('\n')}

## Security Lesson
${lab.securityLesson}

## Implementation
This lab is a deterministic simulation. Outputs are labeled as \`real\`, \`simulated\`, or \`prepared\`.

## Validation
See \`evidence/\` and \`reports/\` directories.

## Lessons Learned
See \`lessons-learned/\` directory.

---
*Generated by the Security+ Zero-to-Hero 3D Lab Platform.*
`;
}

function labArchitecture(lab: Lab): string {
  return `# Architecture — ${lab.title}

## Topology
\`\`\`
${lab.topology}
\`\`\`

## Environment
${lab.environment}

## Security Concepts
${lab.securityConcepts.map((c) => `- ${c}`).join('\n')}

## Prerequisites
${lab.prerequisites.map((p) => `- ${p}`).join('\n')}

## Notes
- All evidence is prepared/simulated — no real systems are contacted.
- This is an authorized, isolated lab environment.
`;
}

/** The Technologies section every professional security repo README needs — pulled from what the lab actually names, never invented. */
function labTechnologies(lab: Lab): string {
  return lab.securityConcepts.map((c) => `- ${c}`).join('\n');
}

function labConfigsReadme(lab: Lab): string {
  return `# Configs — ${lab.title}

## Purpose
Configuration files or exported settings referenced by this lab belong here —
firewall rules, hardening baselines, sample policy exports, and similar
artifacts that are not logs and are not screenshots.

## Redaction checklist before committing anything here
- [ ] No passwords, API keys, tokens, or private key material
- [ ] No real hostnames, internal IP ranges, or customer/employer names
- [ ] No personally identifiable information

## This lab
${lab.environment}
`;
}

function labScreenshotsReadme(lab: Lab): string {
  const screenshotEvidence = lab.evidence.filter((e) => e.type === 'screenshot');
  return `# Screenshots — ${lab.title}

## What belongs here
${
    screenshotEvidence.length > 0
      ? screenshotEvidence.map((e) => `- **${e.label}**: ${e.placeholder}`).join('\n')
      : '- Screenshots supporting the evidence captured in this lab, where applicable.'
  }

## Redaction checklist before committing a screenshot
- [ ] No visible credentials, tokens, or session cookies
- [ ] No real hostnames, internal IPs, or personal information in the frame
- [ ] Crop to the relevant window rather than a full desktop capture
`;
}

function labEvidenceReadme(lab: Lab): string {
  return `# Evidence — ${lab.title}

## Evidence Templates
${lab.evidence.map((e) => `- **${e.label}** (${e.type}): ${e.placeholder}`).join('\n')}

## Usage
Capture evidence as instructed in the lab. Store screenshots in \`screenshots/\` and text logs in \`logs/\`.
`;
}

function labLogsReadme(lab: Lab): string {
  return `# Logs — ${lab.title}

## Log Sources
${lab.evidence
  .filter((e) => e.type === 'log' || e.type === 'text')
  .map((e) => `- ${e.label}`)
  .join('\n')}

## Format
All logs are prepared sample evidence. Do not include real secrets or sensitive information.
`;
}

function labReportsReadme(lab: Lab): string {
  return `# Reports — ${lab.title}

## Findings
${lab.expectedResults.map((r) => `- ${r}`).join('\n')}

## Remediation
${lab.troubleshooting.map((t) => `- ${t}`).join('\n')}

## Validation
${lab.verification.map((v) => `- ${v}`).join('\n')}

## Template
A professional finding pairs a specific observation with severity, evidence,
a recommended fix, and how the fix was validated — not just a bare list.
Use the sections above as the source material for that structure.
`;
}

function labTroubleshootingReadme(lab: Lab): string {
  return `# Troubleshooting — ${lab.title}

## Common Issues
${lab.troubleshooting.map((t) => `- ${t}`).join('\n')}

## Challenge
${lab.challenge ?? 'None'}
`;
}

function labLessonsLearned(lab: Lab): string {
  return `# Lessons Learned — ${lab.title}

## Security Lesson
${lab.securityLesson}

## Key Takeaways
1. ${lab.securityConcepts[0] ?? 'N/A'}
2. Apply the security lesson to real-world scenarios.
3. Document findings and remediation.
`;
}

// ---------------------------------------------------------------------------
// Phase 25 — portfolio-level index across every built phase's labs.
//
// A single lab repo (generateProject) is the unit a hiring manager opens;
// the portfolio index below is the map that gets them there — grouped by
// exam domain so a reviewer can see coverage at a glance rather than a flat,
// unsorted list of 25+ repos.
// ---------------------------------------------------------------------------

export type PortfolioDomainSummary = {
  examDomain: string;
  labCount: number;
  labs: { title: string; repoName: string; phaseTitle: string }[];
};

export type PortfolioSummary = {
  totalLabs: number;
  totalPhases: number;
  domains: PortfolioDomainSummary[];
  files: GitHubProjectFile[];
  generatedAt: number;
};

export function generatePortfolio(phases: Phase[]): PortfolioSummary {
  const domainOrder: string[] = [];
  const byDomain = new Map<string, PortfolioDomainSummary>();

  for (const phase of phases) {
    if (!byDomain.has(phase.examDomain)) {
      domainOrder.push(phase.examDomain);
      byDomain.set(phase.examDomain, { examDomain: phase.examDomain, labCount: 0, labs: [] });
    }
    const entry = byDomain.get(phase.examDomain)!;
    for (const lab of phase.labs) {
      entry.labCount += 1;
      entry.labs.push({ title: lab.title, repoName: repoNameFor(lab), phaseTitle: phase.title });
    }
  }

  const domains = domainOrder.map((d) => byDomain.get(d)!);
  const totalLabs = domains.reduce((sum, d) => sum + d.labCount, 0);

  return {
    totalLabs,
    totalPhases: phases.length,
    domains,
    files: [{ path: 'PORTFOLIO.md', content: portfolioReadme(domains, totalLabs, phases.length) }],
    generatedAt: Date.now(),
  };
}

function portfolioReadme(domains: PortfolioDomainSummary[], totalLabs: number, totalPhases: number): string {
  const domainSections = domains
    .map((d) => {
      const rows = d.labs
        .map((l) => `| ${l.title} | ${l.phaseTitle} | \`${l.repoName}\` |`)
        .join('\n');
      return `### ${d.examDomain} (${d.labCount} lab${d.labCount === 1 ? '' : 's'})\n\n| Lab | Phase | Repository |\n| --- | --- | --- |\n${rows}\n`;
    })
    .join('\n');

  return `# Security+ Zero-to-Hero Portfolio

## Summary
${totalLabs} labs completed across ${totalPhases} phases, spanning every SY0-701 domain
below. Each lab links to its own generated repository — this file is the index,
not a replacement for opening one.

## Coverage by domain
${domainSections}
## How to use this portfolio
- Feature quality over quantity — a hiring manager will open two or three repos,
  not twenty-five. Curate the strongest, most relevant ones for the role.
- Every artifact inside a linked repo is labeled \`real\`, \`simulated\`, or
  \`prepared\` — never claim simulated work as a real-system finding.
- Never include secrets, credentials, tokens, real hostnames, or personal data
  in any linked repository, screenshot, config, or log.

---
*Generated by the Security+ Zero-to-Hero 3D Lab Platform.*
`;
}
