import type { PreparedCommand } from './types';

// ---------------------------------------------------------------------------
// Phase 20 prepared outputs — Security Automation.
//
// Same closed-allowlist contract. This is the one phase where the "output"
// is itself annotated pseudocode/script text — but nothing here is ever
// executed. It is display-only sample text, exactly like every other
// prepared artifact in this simulator. No real credentials, keys, or tokens
// appear; the intentional "hardcoded credential" gap below uses an obviously
// fictional placeholder value, not a functioning secret.
// ---------------------------------------------------------------------------

export const PHASE_20_COMMANDS: PreparedCommand[] = [
  {
    match: 'show raw auth log',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'RAW AUTHENTICATION LOG — auth.log (sample)',
      '',
      '2026-09-09T02:14:01Z sshd[1201]: Failed password for invalid user admin from 203.0.113.77 port 51422',
      '2026-09-09T02:14:09Z sshd[1201]: Failed password for invalid user admin from 203.0.113.77 port 51430',
      '2026-09-09T02:14:16Z sshd[1201]: Failed password for root from 203.0.113.77 port 51441',
      '2026-09-09T02:14:24Z sshd[1201]: Failed password for root from 203.0.113.77 port 51450',
      '2026-09-09T02:14:33Z sshd[1201]: Failed password for invalid user test from 203.0.113.77 port 51461',
      '2026-09-09T02:14:41Z sshd[1201]: Failed password for invalid user admin from 203.0.113.77 port 51470',
      '2026-09-09T02:15:02Z sshd[1201]: Accepted password for analyst1 from 192.168.1.30 port 51502',
      '2026-09-09T02:16:10Z sshd[1201]: Failed password for analyst1 from 192.168.1.30 port 51520',
      '2026-09-09T02:16:40Z sshd[1201]: Accepted password for analyst1 from 192.168.1.30 port 51520',
    ].join('\n'),
    teaches:
      '203.0.113.77 accumulates six failed attempts across three different usernames within one minute — a pattern consistent with automated credential guessing, distinct from analyst1\'s single mistyped password followed immediately by a successful login from a known internal address.',
  },
  {
    match: 'show log parsing script',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'LOG PARSING SCRIPT (annotated) — parse_auth_log.py',
      '',
      'import re',
      '',
      "LOG_PATTERN = re.compile(",
      "    r'(?P<timestamp>\\S+) sshd\\[\\d+\\]: '",
      "    r'(?P<result>Accepted|Failed) password for '",
      "    r'(?:invalid user )?(?P<username>\\S+) from '",
      "    r'(?P<source_ip>\\d{1,3}(?:\\.\\d{1,3}){3})'",
      ')',
      '',
      'def parse_line(line):',
      '    match = LOG_PATTERN.search(line)',
      '    if not match:',
      '        return None  # line did not match the expected format; do not silently guess',
      '    return match.groupdict()',
      '',
      '# Each parsed line becomes: {"timestamp": ..., "result": "Failed"|"Accepted",',
      '#  "username": ..., "source_ip": ...}',
    ].join('\n'),
    teaches:
      'Notice the script explicitly returns None (and, in a complete version, would log a warning) when a line does not match, rather than guessing or skipping silently. A parser that fails loudly on unexpected input is far safer than one that fails quietly — a silent failure here would mean the detection stage never even sees the unparsed events.',
  },
  {
    match: 'show failed login analysis',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'FAILED LOGIN THRESHOLD ANALYSIS',
      '',
      'RULE: Flag any source IP with more than 5 failed logins within a 10-minute window.',
      '',
      'SOURCE IP        FAILED COUNT (10 min)   DISTINCT USERNAMES TRIED   FLAGGED',
      '───────────────  ──────────────────────  ─────────────────────────  ─────────',
      '203.0.113.77      6                       3 (admin, root, test)      YES ← FINDING',
      '192.168.1.30       1                       1 (analyst1)               NO',
      '',
      'FINDING: 203.0.113.77 exceeds the threshold (6 > 5) and is trying multiple usernames,',
      'a stronger indicator of automated guessing than a single account being retried.',
      '192.168.1.30 shows one failure followed by a success from the same account — consistent',
      'with a legitimate user mistyping a password once, not an attack.',
      '',
      'INDICATOR EXTRACTED: 203.0.113.77 (IP) — recommend enrichment via threat-intelligence lookup.',
    ].join('\n'),
    teaches:
      'Counting distinct usernames tried, not just raw failure count, is what separates "one confused legitimate user" from "an automated credential-guessing attempt" — the same six failures could mean either, depending on this one additional piece of context.',
  },
  {
    match: 'show api response sample',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'THREAT-INTELLIGENCE API RESPONSE (sample) — GET /v1/ip/203.0.113.77',
      '',
      '{',
      '  "ip": "203.0.113.77",',
      '  "reputation_score": 87,',
      '  "reputation_scale": "0-100, higher = more malicious",',
      '  "first_seen": "2026-06-02",',
      '  "last_seen": "2026-09-08",',
      '  "campaign_tags": ["credential-stuffing", "known-scanner"],',
      '  "status_code": 200',
      '}',
      '',
      'FIELD NOTES:',
      '  reputation_score (87/100) is high — this IP has an established history of abuse.',
      '  campaign_tags gives enrichment context beyond a bare numeric score.',
      '  status_code 200 confirms the lookup itself succeeded (distinct from the IP\'s reputation).',
    ].join('\n'),
    teaches:
      'Reading this JSON means walking into the object one field at a time. reputation_score alone tells you "how bad"; campaign_tags tells you "bad in what way" — a complete enrichment step should surface both, not just the number.',
  },
  {
    match: 'show enrichment script',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'ENRICHMENT SCRIPT (annotated) — enrich_ioc.py',
      '',
      'import requests',
      '',
      "TI_TOKEN = 'lab-demo-placeholder-not-a-real-token'  ← FINDING: hardcoded credential",
      '',
      'def enrich_ip(ip_address):',
      "    headers = {'Authorization': f'Bearer {TI_TOKEN}'}",
      "    response = requests.get(",
      "        f'https://ti.example/v1/ip/{ip_address}', headers=headers, timeout=5",
      '    )',
      '    if response.status_code == 429:',
      "        return {'error': 'rate_limited'}  # handled, but caller must decide whether to retry",
      '    if response.status_code != 200:',
      "        return {'error': f'unexpected_status_{response.status_code}'}",
      '    return response.json()',
      '',
      'FINDING: TI_TOKEN is written directly in the script instead of being loaded from an',
      'environment variable or secrets manager — anyone who can read this file can reuse the',
      'credential.',
      '',
      'REMEDIATION: Replace the hardcoded line with:',
      "    import os",
      "    TI_TOKEN = os.environ['TI_TOKEN']",
      'and ensure the environment variable is provisioned securely outside version control.',
    ].join('\n'),
    teaches:
      'This script does several things right — a timeout, explicit 429 handling, explicit non-200 handling — which makes the one thing it does wrong (the hardcoded credential) easier to spot precisely because it stands out against otherwise careful error handling.',
  },
  {
    match: 'show generated report',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'AUTO-GENERATED SECURITY REPORT — Incident #AUTO-2026-0909',
      '',
      'SUMMARY: Automated brute-force detection flagged source IP 203.0.113.77 for 6 failed',
      'authentication attempts across 3 distinct usernames within a 10-minute window.',
      '',
      'EVIDENCE:',
      '  - Raw log excerpt: 6 matching lines from auth.log (2026-09-09T02:14:01Z–02:14:41Z)',
      '  - Threat-intelligence enrichment: reputation_score 87/100, tags: credential-stuffing,',
      '    known-scanner',
      '',
      'SEVERITY: High (established malicious reputation + multi-account guessing pattern)',
      '',
      'RECOMMENDED REMEDIATION:',
      '  1. Block 203.0.113.77 at the perimeter firewall pending analyst confirmation.',
      '  2. Review whether any of the 3 attempted usernames (admin, root, test) exist and are',
      '     enabled; disable or rename default accounts if so.',
      '  3. No account lockout observed as a side effect — confirm lockout policy is active.',
      '',
      'STATUS: Awaiting analyst review before any blocking action is taken.',
    ].join('\n'),
    teaches:
      'The report format is identical to what a human analyst would produce manually, which is the point — automation should make consistent report structure the default, not a special effort.',
  },
  {
    match: 'show evidence collection log',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'EVIDENCE COLLECTION LOG — Incident #AUTO-2026-0909',
      '',
      'TIMESTAMP              ARTIFACT                          SHA-256 HASH                  COLLECTED BY',
      '─────────────────────  ─────────────────────────────────  ─────────────────────────────  ──────────────',
      '2026-09-09T02:20:00Z   auth.log excerpt (6 lines)          a1b2c3d4e5f6...(truncated)      automation-svc',
      '2026-09-09T02:20:05Z   TI API response JSON                 f6e5d4c3b2a1...(truncated)      automation-svc',
      '2026-09-09T02:20:11Z   Generated report PDF                 (none recorded)  ← FINDING        automation-svc',
      '',
      'FINDING: The generated report PDF was collected as evidence but no hash was computed or',
      'recorded for it at collection time, breaking the chain-of-custody guarantee that exists',
      'for the other two artifacts.',
      '',
      'REMEDIATION: Update the evidence-collection function to hash every artifact, including',
      'its own generated outputs, at the moment of collection — no exceptions for "internally',
      'generated" files.',
    ].join('\n'),
    teaches:
      'It is tempting to assume a file the system itself just generated does not need the same integrity check as a file pulled from an external source — this finding shows why that assumption is wrong: the report is evidence too, the moment it is filed.',
  },
];
