import type { PreparedCommand } from './types';

// ---------------------------------------------------------------------------
// Phase 10 prepared outputs — Vulnerability Management.
//
// AUTHORISATION: every scanning artifact here is prepared output describing
// the platform's own simulated estate. PROMPT.md's tool list is honoured by
// teaching what each tool produces and how to read it — not by running
// anything. Scanning is only ever legitimate against systems you own or are
// contracted to test, and the artifacts say so.
// ---------------------------------------------------------------------------

export const PHASE_10_COMMANDS: PreparedCommand[] = [
  {
    match: 'explain vulnerability scanning',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'SCAN TYPE            SEES                          MISSES',
      '-------------------  ----------------------------  --------------------------',
      'Unauthenticated      What an attacker sees from    Local packages, config,',
      '                     the network                   anything behind auth',
      'Authenticated        Installed packages, config,   Nothing much — this is the',
      '(credentialed)       registry, patch level         accurate one',
      'Agent-based          Continuous, survives NAT      Requires deployment',
      '                     and offline hosts             and maintenance',
      '',
      'AUTHENTICATED SCANS FIND FAR MORE AND FALSE-POSITIVE FAR LESS.',
      'An unauthenticated scan guesses from banners; a credentialed scan reads',
      'the actual installed version.',
      '',
      'AUTHORISATION',
      '  Scan only systems you own or are contracted to test, with written',
      '  scope and a defined window. Scanning is intrusive and can disrupt',
      '  fragile services — this is a permission question, not a technical one.',
    ].join('\n'),
    teaches:
      'The unauthenticated versus authenticated distinction explains most false positives. A banner saying nginx/1.18.0 is a guess about what is installed; reading the package database is not. If a scan report is full of version-based findings that turn out wrong, the fix is usually credentials rather than a different scanner.',
  },
  {
    match: 'explain cvss',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'CVSS v3.1 BASE METRICS',
      '',
      'EXPLOITABILITY               IMPACT',
      '  AV  Attack Vector            C  Confidentiality',
      '      N network                   H high / L low / N none',
      '      A adjacent              I  Integrity',
      '      L local                 A  Availability',
      '      P physical',
      '  AC  Attack Complexity      SCOPE',
      '      L low / H high           S  U unchanged / C changed',
      '  PR  Privileges Required        (C means the vulnerability affects',
      '      N none / L low / H high     resources beyond its own component)',
      '  UI  User Interaction',
      '      N none / R required',
      '',
      'SEVERITY RATINGS',
      '  0.0 None   0.1-3.9 Low   4.0-6.9 Medium   7.0-8.9 High   9.0-10.0 Critical',
      '',
      'WHAT CVSS DOES NOT KNOW',
      '  Whether the service is reachable in YOUR network',
      '  Whether the asset matters to YOUR business',
      '  Whether a compensating control already blocks it',
      '',
      'Base score describes the vulnerability. It does not describe your exposure.',
    ].join('\n'),
    teaches:
      'Scope is the metric people misread. S:C means the vulnerability lets an attacker affect resources beyond the vulnerable component — a container escape, or a browser sandbox break. It raises the score substantially, which is why a scope-changed medium can outrank a scope-unchanged high.',
  },
  {
    match: 'show scan report',
    tool: 'platform',
    provenance: 'prepared',
    output: [
      'VULNERABILITY SCAN — Northwind lab estate',
      'Scan type: unauthenticated network scan',
      'Authorised scope: 192.168.1.0/24 (owned lab environment)',
      '',
      'CVE             HOST     SERVICE              CVSS  TITLE',
      'CVE-2026-10005  SRV-01   80/tcp nginx          9.8  Apache Struts RCE',
      'CVE-2026-10002  SRV-01   5432/tcp postgres    10.0  PostgreSQL RCE',
      'CVE-2026-10001  SRV-01   22/tcp sshd           9.8  Root login with password',
      'CVE-2026-10007  SW-01    23/tcp telnet         9.6  Default credentials',
      'CVE-2026-10003  SRV-01   80/tcp nginx          7.4  Request smuggling',
      'CVE-2026-10004  WS-01    445/tcp SMB           6.8  SMB signing not required',
      'CVE-2026-10006  FW-01    443/tcp PAN-OS        4.8  TLS 1.0/1.1 enabled',
      'CVE-2026-10008  WS-01    local package         2.5  Outdated OpenSSL',
      '',
      '8 findings. That is the scanner output, not a work list.',
      'Two of these are false positives and one is far less urgent than it looks.',
    ].join('\n'),
    teaches:
      'Never hand this straight to an operations team. An unverified scan report contains false positives and scores that ignore your environment — sending it as a work list is how security teams lose credibility with the people who have to action it.',
  },
  {
    match: 'verify finding struts',
    tool: 'platform',
    provenance: 'prepared',
    output: [
      'VERIFICATION — CVE-2026-10005 Apache Struts RCE on SRV-01',
      '',
      'Scanner basis:  generic HTTP response fingerprint matched a Struts signature',
      '',
      'Manual checks:',
      '  $ which java                  -> not found',
      '  $ dpkg -l | grep -i tomcat    -> no packages',
      '  $ dpkg -l | grep -i struts    -> no packages',
      '  $ curl -I http://srv-01       -> Server: nginx/1.18.0, static content only',
      '',
      'CONCLUSION: FALSE POSITIVE.',
      'Struts is a Java framework. There is no Java runtime on this host at all.',
      'The scanner matched a response pattern rather than confirming the software.',
      '',
      'Action: suppress this plugin for this host, with the justification recorded.',
    ].join('\n'),
    teaches:
      'This is what verification looks like: four commands that take a minute and definitively settle a 9.8. The cost of not doing it is a maintenance window spent patching software that was never installed, and a server team that trusts your next report less.',
  },
  {
    match: 'verify finding postgres',
    tool: 'platform',
    provenance: 'prepared',
    output: [
      'VERIFICATION — CVE-2026-10002 PostgreSQL RCE on SRV-01',
      '',
      'Scanner basis:  version 14.2 detected on 5432/tcp, within the affected range',
      '',
      'Manual checks:',
      '  $ psql --version              -> psql (PostgreSQL) 14.2   [vulnerable version]',
      '  $ ss -tulpn | grep 5432       -> 127.0.0.1:5432 LISTEN    [loopback only]',
      '  $ nmap -p5432 192.168.1.30    -> 5432/tcp closed          [from the network]',
      '',
      'CONCLUSION: CONFIRMED, but not remotely reachable.',
      'The vulnerable version is genuinely installed, so this is not a false',
      'positive. But the CVSS vector assumes AV:N, and no network attacker can',
      'reach this service.',
      '',
      'Priority: patch in the normal window. Do NOT rank above the SSH finding',
      'just because the number is higher.',
    ].join('\n'),
    teaches:
      'Note this is not a false positive — the vulnerable software really is there, and a local attacker or a compromised web application could still reach it. What changes is the priority, not the validity. Confirmed-but-constrained is a distinct category from false positive, and conflating them is how real findings get dismissed.',
  },
  {
    match: 'compare scan pentest',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      '                   VULNERABILITY SCAN         PENETRATION TEST',
      '-----------------  -------------------------  -------------------------',
      'What it does       Identifies known issues    Attempts actual exploitation',
      'Automation         Automated, repeatable      Manual, human-led',
      'Frequency          Continuous or weekly       Periodic, often annual',
      'Depth              Broad and shallow          Narrow and deep',
      'Chains findings    No                         Yes — combines weaknesses',
      'False positives    Common                     Rare (proven by exploitation)',
      'Business impact    Not assessed               Demonstrated',
      'Cost               Low                        High',
      '',
      'They answer different questions.',
      '  Scan:    "What known weaknesses do we have?"',
      '  Pentest: "What could an attacker actually achieve with them?"',
      '',
      'A pentest that only reports scanner output is not a pentest.',
    ].join('\n'),
    teaches:
      'The distinguishing capability is chaining. A scanner reports a low-severity information disclosure and a medium-severity weak permission as two separate rows; a tester notices the first reveals a path that makes the second exploitable, and reports one critical finding. That combination is what automation cannot do.',
  },
  {
    match: 'show remediation plan',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'REMEDIATION PLAN — verified findings only',
      '',
      'ORDER  CVE             FINDING                     ACTION           WINDOW',
      '  1    CVE-2026-10001  SSH root + password login   Config change    Immediate',
      '  2    CVE-2026-10003  nginx request smuggling     Patch + header   This week',
      '  3    CVE-2026-10004  SMB signing not required    Group Policy     This week',
      '  4    CVE-2026-10006  TLS 1.0/1.1 on mgmt         Config change    This month',
      '  5    CVE-2026-10002  PostgreSQL RCE              Patch            Normal cycle',
      '  6    CVE-2026-10008  Outdated OpenSSL            Patch            Normal cycle',
      '',
      'SUPPRESSED (false positives, with justification recorded)',
      '       CVE-2026-10005  Struts RCE — no Java on host',
      '       CVE-2026-10007  Default creds — wrong host attributed',
      '',
      'NOTE THE ORDERING. CVE-2026-10002 scores 10.0 and sits fifth, because',
      'the service is bound to loopback. CVE-2026-10001 scores 9.8 and sits',
      'first, because it is reachable and already under attack.',
      '',
      'FOUR TREATMENT OPTIONS: remediate, mitigate, transfer, accept.',
      'Accept must be documented and authorised — an undocumented shrug is not',
      'acceptance.',
    ].join('\n'),
    teaches:
      'This is the deliverable. It contains verified findings only, ordered by real exposure rather than raw score, with suppressed items and their justification recorded. The Phase 2 risk treatments apply here unchanged: remediate, mitigate, transfer, accept.',
  },
  {
    match: 'validate remediation',
    tool: 'platform',
    provenance: 'prepared',
    output: [
      'VALIDATION — CVE-2026-10001 SSH root login, after remediation',
      '',
      'BEFORE',
      '  PermitRootLogin yes',
      '  PasswordAuthentication yes',
      '',
      'AFTER',
      '  PermitRootLogin prohibit-password',
      '  PasswordAuthentication no',
      '',
      'EVIDENCE OF FIX',
      '  $ sshd -T | grep -E "permitrootlogin|passwordauthentication"',
      '      permitrootlogin prohibit-password',
      '      passwordauthentication no',
      '  $ ssh root@srv-01                -> Permission denied (publickey)',
      '  Re-scan                          -> finding no longer reported',
      '',
      'EVIDENCE SERVICE STILL WORKS',
      '  $ ssh analyst1@srv-01            -> authenticated by publickey, session ok',
      '',
      'Validation needs BOTH: the vulnerability is gone AND the service still works.',
      'A fix that breaks the service gets rolled back, and the vulnerability returns.',
    ].join('\n'),
    teaches:
      'The second half is the part people skip. Confirming a vulnerability is closed is not enough — if the change broke the service, it will be reverted under pressure and you are back where you started, having spent the maintenance window. Always capture evidence that the thing still works.',
  },
];
