import type { PreparedCommand } from './types';

// ---------------------------------------------------------------------------
// Phase 8 prepared outputs — Windows Security.
//
// Same closed-allowlist contract. These are PowerShell-shaped artifacts the
// learner reads while auditing WS-01, the endpoint carried since Phase 0.
//
// The command syntax is real and correct, so a learner can run the same
// commands on a Windows VM they own. Nothing here executes.
// ---------------------------------------------------------------------------

export const PHASE_8_COMMANDS: PreparedCommand[] = [
  {
    match: 'get-localuser',
    tool: 'windows',
    provenance: 'prepared',
    output: [
      'Name           Enabled Description',
      '----           ------- -----------',
      'Administrator  False   Built-in account for administering the computer',
      'DefaultAccount False   A user account managed by the system',
      'Guest          False   Built-in account for guest access',
      'analyst1       True    Lab Analyst',
      'svc-backup     True    Backup service account',
      'WDAGUtility    False   A user account managed by Windows Defender',
    ].join('\n'),
    teaches:
      'Administrator and Guest are correctly disabled. Note svc-backup: a service account with a local presence. Service accounts should never log on interactively, and checking whether that is enforced is a separate question from whether the account exists.',
  },
  {
    match: 'get-localgroupmember administrators',
    tool: 'windows',
    provenance: 'prepared',
    output: [
      'ObjectClass Name                  PrincipalSource',
      '----------- ----                  ---------------',
      'User        WS-01\\Administrator   Local',
      'Group       LAB\\Domain Admins     ActiveDirectory',
      'User        LAB\\analyst1          ActiveDirectory',
    ].join('\n'),
    teaches:
      'analyst1 is in the local Administrators group. Compare against the Phase 1 enumeration, where the same account was in Users only — it was elevated at some point and never removed. This single finding undermines the rest of the baseline, because an administrator can disable Defender, change audit policy, and clear the event log.',
  },
  {
    match: 'get-mpcomputerstatus',
    tool: 'windows',
    provenance: 'prepared',
    output: [
      'AMServiceEnabled              : True',
      'AntivirusEnabled              : True',
      'RealTimeProtectionEnabled     : True',
      'BehaviorMonitorEnabled        : True',
      'IoavProtectionEnabled         : True',
      'AntispywareSignatureAge       : 1',
      'AntivirusSignatureAge         : 1',
      'MAPSReporting                 : Advanced   (cloud protection)',
      'TamperProtectionSource        : Intune',
      'IsTamperProtected             : True',
    ].join('\n'),
    teaches:
      'Everything here reads healthy — and this output alone would let you conclude Defender is protecting the host. It is not sufficient. Check the exclusions separately, because a broad exclusion disables protection in practice while every field above still reports True.',
  },
  {
    match: 'get-mppreference exclusions',
    tool: 'windows',
    provenance: 'prepared',
    output: [
      'ExclusionPath      : {C:\\}',
      'ExclusionExtension : {}',
      'ExclusionProcess   : {}',
      'ExclusionIpAddress : {}',
      '',
      'WARNING: ExclusionPath C:\\ covers the entire system drive.',
    ].join('\n'),
    teaches:
      'This is the finding the previous command hides. Defender reports fully enabled while scanning nothing on the system drive. Broad exclusions usually start as a fix for a performance complaint and are never revisited — and attackers enumerate exclusion paths precisely because an ignored folder is a safe place to work.',
  },
  {
    match: 'get-netfirewallprofile',
    tool: 'windows',
    provenance: 'prepared',
    output: [
      'Name                  : Domain',
      'Enabled               : True',
      'DefaultInboundAction  : Block',
      'DefaultOutboundAction : Allow',
      'LogAllowed            : False',
      '',
      'Name                  : Private',
      'Enabled               : True',
      'DefaultInboundAction  : Block',
      'DefaultOutboundAction : Allow',
      '',
      'Name                  : Public',
      'Enabled               : False',
      'DefaultInboundAction  : NotConfigured',
      'DefaultOutboundAction : NotConfigured',
    ].join('\n'),
    teaches:
      'The public profile is disabled, and that is the worst one to lose. Public applies on untrusted networks — hotels, cafes, conferences — which is exactly where a laptop is most exposed and least protected by anything else in your estate.',
  },
  {
    match: 'get-scheduledtask suspicious',
    tool: 'windows',
    provenance: 'prepared',
    output: [
      'TaskName        : SystemHealthCheck',
      'TaskPath        : \\',
      'State           : Ready',
      'Author          : LAB\\analyst1',
      'Principal       : SYSTEM  (RunLevel: Highest)',
      'Trigger         : Repeats every 00:30:00 indefinitely',
      'Action          : powershell.exe -WindowStyle Hidden -NoProfile -File C:\\ProgramData\\hc.ps1',
      'Date created    : 2026-09-08 02:53:11',
      '',
      'TaskName        : GoogleUpdateTaskMachineUA',
      'TaskPath        : \\',
      'State           : Ready',
      'Principal       : SYSTEM',
      'Trigger         : Daily at 06:00',
      'Action          : C:\\Program Files\\...\\GoogleUpdate.exe /ua',
    ].join('\n'),
    teaches:
      'Compare the two. SystemHealthCheck has a benign name, a hidden window, SYSTEM privilege, a thirty-minute interval, and a creation timestamp two minutes after the Phase 7 intrusion. That is persistence — the mechanism that survives the reboot after you clean the endpoint. Always check creation time against your incident timeline.',
  },
  {
    match: 'get-service running',
    tool: 'windows',
    provenance: 'prepared',
    output: [
      'Status   Name               DisplayName',
      '------   ----               -----------',
      'Running  Dhcp               DHCP Client',
      'Running  Dnscache           DNS Client',
      'Running  EventLog           Windows Event Log',
      'Running  LanmanWorkstation  Workstation',
      'Running  MpsSvc             Windows Defender Firewall',
      'Running  WinDefend          Microsoft Defender Antivirus Service',
      'Stopped  Spooler            Print Spooler          (Disabled)',
      'Running  Sysmon64           System Monitor',
    ].join('\n'),
    teaches:
      'Print Spooler stopped and disabled is correct — it has a long history of privilege-escalation vulnerabilities and most endpoints do not need it. Sysmon64 running means you have far richer process telemetry than the built-in event log provides.',
  },
  {
    match: 'show sysmon config',
    tool: 'windows',
    provenance: 'prepared',
    output: [
      'Sysmon configuration summary — WS-01',
      '',
      'EVENT ID  WHAT IT RECORDS                       ENABLED',
      '  1       Process creation (with hashes)          Yes',
      '  3       Network connection (with process)       Yes',
      '  7       Image/DLL loaded                        No',
      '  8       CreateRemoteThread                      Yes',
      ' 10       Process access (e.g. LSASS reads)       Yes',
      ' 11       File created                            Yes',
      ' 12/13/14 Registry add/set/rename                 Yes',
      ' 22       DNS query (with process)                Yes',
      '',
      'Sysmon event 3 and 22 attribute network connections and DNS queries to the',
      'PROCESS that made them. The built-in Windows log does not.',
    ].join('\n'),
    teaches:
      'Sysmon event 10 is the one to know: it records processes reading another process memory, which is how credential dumping from LSASS is detected. Note events 3 and 22 — they answer the exact question the Phase 7 firewall log could not, namely which process opened the connection.',
  },
  {
    match: 'get-uac settings',
    tool: 'windows',
    provenance: 'prepared',
    output: [
      'Registry: HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System',
      '',
      'EnableLUA                   : 1     (UAC enabled)',
      'ConsentPromptBehaviorAdmin  : 0     (Elevate without prompting)',
      'ConsentPromptBehaviorUser   : 3     (Prompt for credentials)',
      'PromptOnSecureDesktop       : 1     (Secure desktop enabled)',
      'FilterAdministratorToken    : 1     (Admin Approval Mode for RID 500)',
    ].join('\n'),
    teaches:
      'EnableLUA is 1, so any dashboard reports "UAC: Enabled". But ConsentPromptBehaviorAdmin of 0 means administrators elevate silently with no prompt at all — which defeats the purpose. This is the classic case of the headline setting looking correct while the detail underneath is the finding.',
  },
  {
    match: 'get-powershell logging',
    tool: 'windows',
    provenance: 'prepared',
    output: [
      'PowerShell logging configuration — WS-01',
      '',
      'SETTING                          STATE     EVENT LOG',
      'Module logging                   Disabled  —',
      'Script block logging             Disabled  Microsoft-Windows-PowerShell/Operational 4104',
      'Transcription                    Disabled  —',
      'Execution policy                 RemoteSigned',
      'PowerShell 2.0 engine            Installed',
      '',
      'AMSI                             Enabled',
    ].join('\n'),
    teaches:
      'Script block logging is the highest-value Windows logging setting for detecting living-off-the-land attacks, because it records what PowerShell actually executed after de-obfuscation — and it is off by default. Note the 2.0 engine still being installed: invoking it downgrades an attacker straight past script block logging and AMSI.',
  },
  {
    match: 'get-acl c:\\reports',
    tool: 'windows',
    provenance: 'prepared',
    output: [
      'Path   : C:\\reports',
      'Owner  : BUILTIN\\Administrators',
      '',
      'Access :',
      '  NT AUTHORITY\\SYSTEM       Allow  FullControl        (OI)(CI) Inherited',
      '  BUILTIN\\Administrators    Allow  FullControl        (OI)(CI) Inherited',
      '  LAB\\analyst1              Allow  ReadAndExecute     (OI)(CI) Explicit',
      '  BUILTIN\\Users             Allow  ReadAndExecute     (OI)(CI) Inherited',
      '',
      'NTFS permissions combine with share permissions; the MOST RESTRICTIVE wins.',
    ].join('\n'),
    teaches:
      'Read the inheritance flags: (OI) object inherit, (CI) container inherit, so these apply down the tree. Explicit entries are set on this object; inherited ones come from the parent. And remember the rule the exam tests — when NTFS and share permissions differ, the more restrictive of the two applies.',
  },
  {
    match: 'compare ntfs share permissions',
    tool: 'windows',
    provenance: 'simulated',
    output: [
      'NTFS PERMISSIONS                  SHARE PERMISSIONS',
      '--------------------------------  --------------------------------',
      'Apply locally AND over the        Apply ONLY over the network',
      'network',
      'Granular: Read, Write, Modify,    Coarse: Read, Change, Full Control',
      'Full Control, and special',
      'Travel with the file when moved   Belong to the share, not the data',
      'within the same volume',
      '',
      'WHEN BOTH APPLY, THE MOST RESTRICTIVE WINS.',
      '',
      'Example: Share = Full Control, NTFS = Read  ->  effective access is READ',
      '         Share = Read, NTFS = Full Control  ->  effective access is READ',
      '',
      'Common practice: set Share to Full Control for Authenticated Users and',
      'control access entirely with NTFS, so there is one place to reason about.',
    ].join('\n'),
    teaches:
      'This is a reliable exam question. Work out each permission set separately, then take the more restrictive result. Note that NTFS permissions apply to local logons too, while share permissions are invisible to anyone sitting at the machine.',
  },
  {
    match: 'harden windows endpoint',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'WINDOWS HARDENING — remediation plan for WS-01',
      '',
      'SEV   SETTING                            ACTION',
      'high  Local Administrators membership    Remove LAB\\analyst1',
      'high  UAC ConsentPromptBehaviorAdmin     Set to 2 (prompt on secure desktop)',
      'high  Defender exclusion path C:\\        Remove; scope narrowly if needed',
      'high  Firewall Public profile            Enable, default inbound Block',
      'high  PowerShell script block logging    Enable via Group Policy',
      'high  Scheduled task SystemHealthCheck   INVESTIGATE then remove — persistence',
      'med   Process creation command line      Enable command-line auditing',
      'med   Security log size / forwarding     Increase and forward to the SIEM',
      'med   PowerShell 2.0 engine              Remove the optional feature',
      'low   Display last signed-in user        Disable',
      '',
      'ORDER MATTERS. Remove the administrator membership FIRST — while analyst1',
      'holds local admin, every other change on this list can be undone from the',
      'endpoint itself.',
      '',
      'And treat SystemHealthCheck as an incident, not a config item. Deleting it',
      'without investigating destroys the evidence of how it got there.',
    ].join('\n'),
    teaches:
      'Two judgements here matter more than the list. Sequencing: privilege removal comes first, because standing local admin lets an attacker reverse everything else. And scope: one item on a hardening list is actually an active compromise, and deleting it as a tidy-up would destroy the evidence needed to answer how it was created.',
  },
];
