import type { PreparedCommand } from './types';

// ---------------------------------------------------------------------------
// Phase 21 prepared outputs — Wireshark & Packet Analysis.
//
// Same closed-allowlist contract. All IPs and MACs are RFC 1918 / RFC 5737
// documentation-range or private-lab values. No real credentials, keys, or
// tokens appear — the sample HTTP credential is an obviously fictional lab
// value used only to illustrate a cleartext-exposure finding.
// ---------------------------------------------------------------------------

export const PHASE_21_COMMANDS: PreparedCommand[] = [
  {
    match: 'show packet capture overview',
    tool: 'wireshark',
    provenance: 'simulated',
    output: [
      'PACKET CAPTURE OVERVIEW — office-lan.pcap (sample, 60s window)',
      '',
      'NO.  TIME       SOURCE           DESTINATION      PROTOCOL  LENGTH  INFO',
      '───  ─────────  ───────────────  ───────────────  ────────  ──────  ─────────────────────────────────',
      '1    00:00.10   192.168.1.50     192.168.1.1       ARP       42      Who has 192.168.1.1? Tell 192.168.1.50',
      '2    00:00.11   192.168.1.1      192.168.1.50       ARP       42      192.168.1.1 is at AA:BB:CC:00:00:01',
      '3    00:00.42   192.168.1.50     8.8.8.8            ICMP      74      Echo (ping) request id=0x0001, seq=1/256',
      '4    00:00.60   192.168.1.50     93.184.216.34      TCP       66      51502 → 443 [SYN] Seq=0 Win=64240',
      '5    00:00.61   93.184.216.34    192.168.1.50       TCP       66      443 → 51502 [SYN, ACK] Seq=0 Ack=1 Win=65535',
      '6    00:00.61   192.168.1.50     93.184.216.34      TCP       54      51502 → 443 [ACK] Seq=1 Ack=1 Win=64240',
      '7    00:00.70   192.168.1.50     93.184.216.34      TLS       311     Client Hello',
      '8    00:01.15   192.168.1.50     192.168.1.53       DNS       74      Standard query 0x1a2b A www.example.com',
      '9    00:01.16   192.168.1.53     192.168.1.50       DNS       90      Standard query response 0x1a2b A 93.184.216.34',
      '10   00:02.00   0.0.0.0          255.255.255.255    DHCP      342     DHCP Discover - Transaction ID 0x3a1f2c4d',
      '11   00:15.30   192.168.1.60     198.51.100.20      TCP       74      52200 → 80 [SYN] Seq=0 Win=64240',
      '12   00:15.31   192.168.1.60     198.51.100.20      HTTP      512     GET /login HTTP/1.1',
      '',
      'SAMPLE PROTOCOL DISTRIBUTION: ARP 8%, ICMP 3%, TCP 41%, DNS 22%, HTTP 9%, TLS 12%, DHCP 5%.',
    ].join('\n'),
    teaches:
      'Frames 4-6 are a complete three-way handshake; frame 7 shows encryption beginning immediately after on the same conversation; frames 8-9 are a normal DNS lookup. Recognising these patterns at a glance is the foundation every other exercise in this phase builds on.',
  },
  {
    match: 'show tcp handshake trace',
    tool: 'wireshark',
    provenance: 'simulated',
    output: [
      'TCP HANDSHAKE TRACE — 192.168.1.50:51502 ↔ 93.184.216.34:443',
      '',
      'STEP 1  192.168.1.50 → 93.184.216.34   [SYN]      Seq=0            Win=64240',
      '        Client proposes initial sequence number 0 and requests a new connection.',
      '',
      'STEP 2  93.184.216.34 → 192.168.1.50   [SYN, ACK] Seq=0 Ack=1      Win=65535',
      '        Server acknowledges the client (Ack=1, meaning "I received your byte 0, expecting',
      '        byte 1 next") and proposes its own initial sequence number 0.',
      '',
      'STEP 3  192.168.1.50 → 93.184.216.34   [ACK]      Seq=1 Ack=1      Win=64240',
      '        Client acknowledges the server\'s sequence number. The handshake is complete —',
      '        the connection is now ESTABLISHED and application data (here, TLS Client Hello)',
      '        can begin.',
      '',
      'TOTAL TIME: 0.01 seconds — a healthy, low-latency handshake with no retransmissions.',
    ].join('\n'),
    teaches:
      'Every ACK number is "the next byte I expect from you" — that single rule explains why the server\'s Ack=1 and the client\'s final Ack=1 both make sense once you know each side\'s SYN consumed exactly one sequence number.',
  },
  {
    match: 'show follow tcp stream',
    tool: 'wireshark',
    provenance: 'simulated',
    output: [
      'FOLLOW TCP STREAM — 192.168.1.60:52200 ↔ 198.51.100.20:80 (reassembled)',
      '',
      'GET /login HTTP/1.1',
      'Host: hr-portal.lab.local',
      'User-Agent: Mozilla/5.0',
      'Accept: text/html',
      '',
      'HTTP/1.1 200 OK',
      'Content-Type: text/html',
      '',
      '<html>...login form...</html>',
      '',
      '---',
      '',
      'POST /login HTTP/1.1',
      'Host: hr-portal.lab.local',
      'Content-Type: application/x-www-form-urlencoded',
      'Content-Length: 41',
      '',
      'username=jsmith&pwd_value=Summer2026Lab!',
      '',
      'HTTP/1.1 302 Found',
      'Location: /dashboard',
    ].join('\n'),
    teaches:
      'Twelve individual segments collapse into this one readable transcript. The GET and the initial page load look completely unremarkable — the actual finding only becomes visible once the POST body is read in full, which is exactly what following the stream makes possible.',
  },
  {
    match: 'show arp table anomaly',
    tool: 'wireshark',
    provenance: 'simulated',
    output: [
      'ARP ACTIVITY — office-lan.pcap',
      '',
      'TIME       SOURCE           INFO',
      '─────────  ───────────────  ──────────────────────────────────────────',
      '02:14:01   192.168.1.1      192.168.1.1 is at AA:BB:CC:00:00:01',
      '02:14:03   192.168.1.99      192.168.1.1 is at AA:BB:CC:00:00:99  ← FINDING',
      '02:14:20   192.168.1.1      192.168.1.1 is at AA:BB:CC:00:00:01',
      '',
      'FINDING: Two different MAC addresses (AA:BB:CC:00:00:01 and AA:BB:CC:00:00:99) both',
      'claimed ownership of 192.168.1.1 (the gateway) within 2 seconds of each other. The second',
      'claim, from host 192.168.1.99, did not previously appear as the gateway anywhere in this',
      'capture — this is the signature of an active ARP spoofing (poisoning) attempt.',
      '',
      'RECOMMENDATION: Isolate 192.168.1.99 immediately for investigation; verify the legitimate',
      'gateway MAC (AA:BB:CC:00:00:01) with a trusted out-of-band source; consider dynamic ARP',
      'inspection (DAI) on the switch to prevent recurrence.',
    ].join('\n'),
    teaches:
      'The timestamp gap (2 seconds) matters as much as the conflicting MACs — it rules out a coincidental, delayed legitimate re-announcement and points to an active, ongoing spoofing attempt during the capture window.',
  },
  {
    match: 'show dns query log',
    tool: 'wireshark',
    provenance: 'simulated',
    output: [
      'DNS QUERY LOG (sample) — office-lan.pcap',
      '',
      'TIME       QUERY                                                          TYPE',
      '─────────  ─────────────────────────────────────────────────────────────  ──────',
      '00:01.15   www.example.com                                                A',
      '00:03.40   mail.corp.local                                                A',
      '05:12.01   a1b2c3d4e5f6a7b8c9d0.datasink.example                          TXT  ← FINDING',
      '05:12.30   f6e5d4c3b2a1908070605.datasink.example                         TXT  ← FINDING',
      '05:12.55   9988776655443322110099.datasink.example                       TXT  ← FINDING',
      '           ... 214 additional similar TXT queries to datasink.example in a 3-minute window',
      '',
      'FINDING: 217 TXT queries to the single external domain "datasink.example" occurred in a',
      '3-minute window, each with a long, high-entropy subdomain that does not resemble a normal',
      'hostname. Ordinary DNS traffic in this capture (rows 1-2) uses short, human-readable names',
      'and a normal mix of record types.',
      '',
      'RECOMMENDATION: Treat as likely DNS tunnelling. Block resolution of datasink.example at the',
      'DNS resolver, capture full packet payloads for the affected host for forensic review, and',
      'isolate the host pending investigation.',
    ].join('\n'),
    teaches:
      'The finding is not "TXT records are bad" — TXT records are a normal, legitimate record type. It is the combination of volume, a single destination domain, and high-entropy subdomains that together distinguish tunnelling from ordinary DNS use.',
  },
  {
    match: 'show http cleartext capture',
    tool: 'wireshark',
    provenance: 'simulated',
    output: [
      'HTTP CLEARTEXT REVIEW — 192.168.1.60:52200 ↔ 198.51.100.20:80',
      '',
      'Reassembled POST body:',
      '  username=jsmith&pwd_value=Summer2026Lab!',
      '',
      'FINDING: The HR portal login form submits credentials over plain HTTP (port 80, no TLS).',
      'The username and password value are both readable directly in the reassembled request',
      'body with no decryption required — anyone able to capture this traffic segment can read',
      'this employee\'s credential in full.',
      '',
      'RECOMMENDATION: Immediately force this credential to be reset; migrate the HR portal login',
      'endpoint to HTTPS-only (redirect or reject plain HTTP entirely) and enable HSTS to prevent',
      'any future downgrade to plaintext.',
    ].join('\n'),
    teaches:
      'This finding does not require any special decryption skill — it requires only noticing that the conversation happened on port 80 rather than 443, and that the destination is not a public test page but an internal HR system that should never accept live credentials this way.',
  },
  {
    match: 'show syn flood pattern',
    tool: 'wireshark',
    provenance: 'simulated',
    output: [
      'TCP SYN ACTIVITY — 198.51.100.20:443 (target)',
      '',
      'WINDOW: 00:20.00 - 00:20.05 (5 seconds)',
      '',
      'SOURCE IP        SYN SENT  SYN-ACK RECEIVED  HANDSHAKE COMPLETED',
      '───────────────  ────────  ─────────────────  ────────────────────',
      '203.0.113.10      1         YES                 YES',
      '198.51.100.77     312       0 ← FINDING          0 ← FINDING',
      '(298 additional distinct source IPs, 1 SYN each, 0 completions) ← FINDING',
      '',
      'FINDING: In a 5-second window, 298 distinct source IPs (plus 312 repeated attempts from',
      '198.51.100.77) sent SYN segments to 198.51.100.20:443 with zero completed handshakes —',
      'compared to one legitimate client (203.0.113.10) whose single SYN completed normally.',
      '',
      'RECOMMENDATION: This is a SYN flood. Enable SYN cookies on the target, apply rate limiting',
      'at the upstream firewall/load balancer, and consider a DDoS mitigation service if the',
      'volume continues to scale.',
    ].join('\n'),
    teaches:
      'The single legitimate connection (203.0.113.10) is included deliberately as a contrast — a SYN flood does not mean "all SYNs are bad," it means the overwhelming majority never complete, which is what actually exhausts the target\'s connection table.',
  },
];
