import type { PreparedCommand } from './types';

// ---------------------------------------------------------------------------
// Phase 19 prepared outputs — Security Hardening.
//
// Same closed-allowlist contract. Hostnames, IPs, and identifiers are
// fictional / documentation-range values. No real credentials, keys, or
// tokens appear.
// ---------------------------------------------------------------------------

export const PHASE_19_COMMANDS: PreparedCommand[] = [
  {
    match: 'show endpoint hardening baseline',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'ENDPOINT HARDENING BASELINE — WS-19 (Windows 11) and SRV-19 (Ubuntu 24.04)',
      '',
      'CATEGORY              HOST    FINDING                                              STATUS',
      '─────────────────────  ──────  ───────────────────────────────────────────────────  ──────────────',
      'Firewall                WS-19   Windows Firewall default-deny inbound, mgmt subnet only  COMPLIANT ✓',
      'Firewall                SRV-19  nftables default-deny inbound, SSH from bastion only      COMPLIANT ✓',
      'Patching                WS-19   Fully patched, last update 3 days ago                     COMPLIANT ✓',
      'Patching                SRV-19  47 pending security updates, oldest 118 days old           ← FINDING',
      'Access Control          WS-19   Standard users only; no unnecessary local admin accounts   COMPLIANT ✓',
      'Access Control          SRV-19  sudoers grants (ALL) NOPASSWD:ALL to the deploy account     ← FINDING',
      'Logging                 WS-19   Script block logging ON; Constrained Language Mode OFF     ← FINDING (partial)',
      'Logging                 SRV-19  auditd running, sudo invocations logged and forwarded       COMPLIANT ✓',
      'Service Minimisation     SRV-19  14 unnecessary services running incl. Bluetooth, CUPS      ← FINDING',
      '',
      'SUMMARY: 4 findings across 2 hosts, spanning 3 of the 5 control categories.',
    ].join('\n'),
    teaches:
      'Reading this table by category rather than by host shows the real pattern: WS-19\'s only gap is in logging (Constrained Language Mode), and SRV-19 has gaps in three different categories — the hosts are not "one good, one bad," they simply differ in which categories need attention.',
  },
  {
    match: 'show patch management status',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'PATCH MANAGEMENT STATUS',
      '',
      'WS-19 (Windows 11)',
      '  WSUS pilot ring: 10 machines, 3-day monitoring window',
      '  Last patch Tuesday cycle: approved and deployed fleet-wide on schedule',
      '  Pending updates: 0',
      '  Status: COMPLIANT',
      '',
      'SRV-19 (Ubuntu 24.04)',
      '  unattended-upgrades: NOT CONFIGURED',
      '  Pending security updates: 47 (oldest: 118 days)',
      '  Pending package updates (non-security): 112',
      '  Status: ← FINDING — no automatic security patching and no scheduled manual process found',
      '',
      'RECOMMENDATION: Enable unattended-upgrades scoped to the security repository on SRV-19,',
      'matching the risk-balanced pattern already working on the Windows fleet (pilot ring, then',
      'scheduled full deployment) rather than leaving Linux patching entirely manual.',
    ].join('\n'),
    teaches:
      'The Windows host shows what a working patch process looks like — a pilot ring, then scheduled fleet-wide deployment. SRV-19 shows the same fundamental gap you would expect on any platform with no equivalent process: a growing, aging backlog of unpatched vulnerabilities.',
  },
  {
    match: 'show powershell security config',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'POWERSHELL SECURITY CONFIGURATION — WS-19',
      '',
      'SETTING                          VALUE                    STATUS',
      '────────────────────────────────  ───────────────────────  ──────────────',
      'Execution Policy                  RemoteSigned              Baseline OK',
      'Script Block Logging               Enabled, forwarded to SIEM  COMPLIANT ✓',
      'Module Logging                     Enabled, forwarded to SIEM  COMPLIANT ✓',
      'Constrained Language Mode          Not applied to standard users  ← FINDING',
      'AMSI (Antimalware Scan Interface)  Enabled                   COMPLIANT ✓',
      '',
      'FINDING: Standard users can run PowerShell in Full Language Mode, meaning a successful',
      'phishing payload executed in their context has unrestricted access to sensitive APIs',
      '(including direct Win32 API calls), even though every action would be logged.',
      '',
      'REMEDIATION: Apply Constrained Language Mode via AppLocker or WDAC policy for all',
      'non-administrative accounts, restricting them to a safe language subset while leaving',
      'Full Language Mode available only to signed, authorised administrative scripts.',
    ].join('\n'),
    teaches:
      'Logging alone tells you what happened after the fact. Constrained Language Mode is the control that limits what could happen in the first place — the two are complementary, and this host has only implemented one of them.',
  },
  {
    match: 'show linux service baseline',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'LINUX SERVICE AND MAC BASELINE — SRV-19',
      '',
      'MANDATORY ACCESS CONTROL',
      '  SELinux status: Enabled, mode = PERMISSIVE  ← FINDING',
      '  (Permissive mode logs policy violations but does not block them.)',
      '',
      'RUNNING SERVICES (sample of unnecessary services found)',
      '  bluetooth.service        active   ← FINDING: not needed on a headless server',
      '  cups.service              active   ← FINDING: no local printing required',
      '  avahi-daemon.service      active   ← FINDING: mDNS discovery not required in this environment',
      '  ... 11 additional unnecessary services found',
      '',
      'FINDINGS:',
      '  1. SELinux is in permissive mode, providing visibility but no actual enforcement — a',
      '     policy violation is logged, not blocked.',
      '  2. 14 unnecessary services are running, each representing avoidable attack surface',
      '     with no corresponding business need on this headless application server.',
      '',
      'REMEDIATION: Switch SELinux to enforcing mode after validating the policy against a short',
      'monitoring period; disable and mask all 14 unnecessary services.',
    ].join('\n'),
    teaches:
      'Permissive mode is a common half-measure — it looks like SELinux is "on," but it provides audit visibility only, not containment. Enforcing mode is the actual control; permissive mode is a staging step toward it, not an end state.',
  },
  {
    match: 'show network device hardening',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'NETWORK DEVICE HARDENING — core-sw-01, core-rtr-01',
      '',
      'DEVICE       MANAGEMENT PROTOCOLS      UNUSED PORTS          FINDING',
      '───────────  ─────────────────────────  ────────────────────  ──────────────────────────',
      'core-sw-01   SSH (v2) + Telnet enabled   18 of 48 ports UP      ← FINDING x2',
      'core-rtr-01  SSH (v2) + HTTP enabled     N/A                    ← FINDING',
      '',
      'FINDINGS:',
      '  1. core-sw-01 has Telnet enabled alongside SSH — cleartext management access remains',
      '     possible even though a secure alternative exists.',
      '  2. core-sw-01 has 18 unused access ports administratively enabled — a walk-up attacker',
      '     with brief physical access could plug in and reach the network directly.',
      '  3. core-rtr-01 has its HTTP web management interface enabled alongside SSH; HTTP',
      '     transmits the session in cleartext.',
      '',
      'REMEDIATION: Disable Telnet on core-sw-01 and HTTP on core-rtr-01 once SSH access is',
      'confirmed working for all administrators; shut down all 18 unused ports and document',
      'the process for re-enabling one when a new device is provisioned.',
    ].join('\n'),
    teaches:
      'Every finding here is the same shape: a legacy or unnecessary access path left enabled "alongside" a secure one, rather than being removed once the secure path was confirmed to work.',
  },
  {
    match: 'show management plane config',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'MANAGEMENT PLANE CONFIGURATION',
      '',
      'Management VLAN: NONE CONFIGURED  ← FINDING',
      'Device management interfaces reachable from: VLAN 10 (general workstation traffic)  ← FINDING',
      'Jump host / bastion: NONE  ← FINDING',
      'Device administration AAA: Local password only, shared across 6 administrators  ← FINDING',
      '',
      'FINDINGS:',
      '  1. There is no dedicated management VLAN — device management interfaces are reachable',
      '     from the same broadcast domain as general employee workstations.',
      '  2. No jump host exists; administrators connect directly from their workstations to',
      '     device management interfaces.',
      '  3. All 6 administrators share a single local password on every device, so no individual',
      '     action can be attributed to a specific person, and revoking one administrator\'s',
      '     access requires changing the password for all of them.',
      '',
      'REMEDIATION: Create a dedicated out-of-band management VLAN; deploy a hardened jump host',
      'with MFA as the only permitted path to management interfaces; migrate to TACACS+/RADIUS',
      'with individual administrator accounts.',
    ].join('\n'),
    teaches:
      'This is the same finding from the Phase 11 network review, seen again here with the specific remediation this phase\'s lab asks you to design: segmentation, a jump host, and centralised AAA together close it.',
  },
  {
    match: 'show acl review',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'ACCESS CONTROL LIST REVIEW — core-rtr-01, management-interface-acl',
      '',
      'SEQ  ACTION  SOURCE            DESTINATION         PORT   NOTE',
      '───  ──────  ────────────────  ──────────────────  ─────  ──────────────────────',
      '10   DENY    203.0.113.0/24     any (mgmt iface)     22     Known-bad range blocked',
      '20   DENY    198.51.100.50      any (mgmt iface)     22     Specific known-bad host blocked',
      '(no further rules — ACL ends here)',
      '',
      'FINDING: The ACL contains only specific DENY entries for known-bad sources, with no',
      'final DENY ALL rule. On this platform, an ACL with no matching explicit rule for a given',
      'packet falls through to a permissive default — meaning any source NOT explicitly listed',
      'above is allowed to reach the management interface.',
      '',
      'REMEDIATION: Replace this deny-list approach with an explicit-permit, implicit-deny',
      'structure: PERMIT management traffic only from the bastion host\'s specific IP, then DENY',
      'ALL as the final rule.',
    ].join('\n'),
    teaches:
      'This is the textbook deny-list mistake: blocking specific known-bad sources feels productive, but it only stops the sources you already know about. Explicit-permit, implicit-deny protects against every source you have not yet identified as a threat.',
  },
  {
    match: 'show cis benchmark gaps',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'CIS BENCHMARK COMPLIANCE GAPS — core-sw-01, core-rtr-01',
      '',
      'CIS ITEM                                              STATUS       CROSS-REFERENCE',
      '───────────────────────────────────────────────────────  ───────────  ────────────────────────',
      '1.1 — Disable Telnet, enforce SSHv2 only                 ← FAIL       show network device hardening',
      '1.4 — Disable unused switch ports                        ← FAIL       show network device hardening',
      '2.3 — Disable HTTP management interface                  ← FAIL       show network device hardening',
      '3.2 — Restrict management access via ACL to known hosts   ← FAIL       show acl review',
      '4.1 — Centralised AAA (TACACS+/RADIUS) for administration ← FAIL       show management plane config',
      '5.5 — Dedicated out-of-band management network            ← FAIL       show management plane config',
      '',
      'SUMMARY: 6 of 6 relevant CIS Benchmark items fail for this device pair — every finding',
      'from the individual reviews maps directly to a specific, named benchmark item.',
    ].join('\n'),
    teaches:
      'A CIS Benchmark turns "these devices seem insecure" into six specific, individually testable, individually fixable line items — this is what makes a hardening finding auditable rather than a matter of opinion.',
  },
];
