import type { PreparedCommand } from './types';

// ---------------------------------------------------------------------------
// Phase 17 prepared outputs — Governance, Risk & Compliance.
//
// Same closed-allowlist contract. The company, vendors, and figures below are
// entirely fictional. No real credentials, keys, or tokens appear.
// ---------------------------------------------------------------------------

export const PHASE_17_COMMANDS: PreparedCommand[] = [
  {
    match: 'show asset inventory',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'ASSET INVENTORY — Meridian Retail Co. (fictional)',
      '',
      'ASSET                          TYPE          BUSINESS VALUE   OWNER',
      '─────────────────────────────  ────────────  ───────────────  ──────────────',
      'Customer database (350k rows)  Data          Critical         VP Engineering',
      'Payment processing system      System        Critical         CFO',
      'Employee laptops (200 units)   Endpoint      High             IT Director',
      'Cloud payroll vendor (SaaS)    Third party   High             HR Director',
      'Marketing website (public)     System        Low              Marketing Lead',
      '',
      'NOTE: This inventory is the starting point for risk identification — a risk',
      'cannot be assessed against an asset that was never inventoried.',
    ].join('\n'),
    teaches:
      'An asset inventory is the prerequisite for everything downstream: you cannot assess, treat, or monitor risk to something you never identified as valuable in the first place.',
  },
  {
    match: 'show threat catalog',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'THREAT CATALOGUE — Meridian Retail Co. (fictional)',
      '',
      'THREAT                        LIKELY TARGET ASSET(S)                 SOURCE',
      '────────────────────────────  ──────────────────────────────────────  ──────────────',
      'Ransomware                    Customer database, payment system      External',
      'Lost/stolen unencrypted laptop Employee laptops                       Physical/insider',
      'Vendor breach                 Cloud payroll vendor                    Third party',
      'Insider data exfiltration     Customer database                       Internal',
      'Phishing / credential theft   All systems (via employee accounts)     External',
      '',
      'NOTE: Each threat should map to one or more inventoried assets. A threat with',
      'no mapped asset either does not apply here or reveals a gap in the inventory.',
    ].join('\n'),
    teaches:
      'A threat catalogue is only useful when cross-referenced against the asset inventory. The mapping itself is the analysis — a threat in isolation is just a headline.',
  },
  {
    match: 'show risk register',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'RISK REGISTER — Meridian Retail Co. (fictional)',
      '',
      'RISK                                  LIKELIHOOD  IMPACT  TREATMENT  LAST REVIEWED   STATUS',
      '─────────────────────────────────────  ──────────  ──────  ─────────  ──────────────  ──────────────',
      'Ransomware on payment system            Medium      High    Mitigate   2026-06-01      Current',
      'Vendor breach (cloud payroll)            Medium      High    (none)     Never           ← FINDING: no entry',
      'Unencrypted laptop stolen                Medium      High    (unassessed) —              ← FINDING: not yet assessed',
      'Public website defacement                Low         Low     Accept     2024-03-10      ← FINDING: stale (>2 yrs)',
      '',
      'FINDINGS:',
      '  1. The cloud payroll vendor, a High-impact asset per the threat catalogue, has no risk',
      '     register entry at all.',
      '  2. The unencrypted-laptop risk is identified but has never been formally assessed.',
      '  3. The public-website risk was last reviewed over two years ago — stale relative to a',
      '     typical annual review cycle.',
    ].join('\n'),
    teaches:
      'A risk register with gaps is more dangerous than no register at all, because it creates false confidence — leadership believes risk is being tracked when entire categories are silently missing.',
  },
  {
    match: 'show risk calculation',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'QUANTITATIVE RISK CALCULATION — Unencrypted Laptop Theft',
      '',
      'Single Loss Expectancy (SLE):',
      '  Cost of one incident (breach notification, credit monitoring, legal, brand impact) = $80,000',
      '',
      'Annualized Rate of Occurrence (ARO):',
      '  Historical data: 1 laptop stolen every 2 years  →  ARO = 0.5',
      '',
      'Annualized Loss Expectancy (ALE):',
      '  ALE = SLE x ARO = $80,000 x 0.5 = $40,000 per year',
      '',
      'PROPOSED CONTROL: Fleet-wide full-disk encryption',
      '  One-time deployment cost: $18,000',
      '  Annual licensing/management cost: $6,000',
      '',
      'COMPARISON:',
      '  Annual control cost ($6,000, after year one) is well below the ALE ($40,000).',
      '  RECOMMENDATION: Mitigate — deploy full-disk encryption. The control is clearly',
      '  cost-justified, and residual risk drops to Low (a stolen encrypted laptop exposes',
      '  no readable data).',
    ].join('\n'),
    teaches:
      'This is the calculation that turns "we should probably encrypt the laptops" into a funded project: ALE gives the risk a dollar figure, and comparing it to control cost gives a decision-maker something concrete to approve.',
  },
  {
    match: 'show vendor risk assessment',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'VENDOR RISK ASSESSMENT — Meridian Retail Co. (fictional)',
      '',
      'VENDOR                    DATA ACCESS         QUESTIONNAIRE  ATTESTATION   RIGHT-TO-AUDIT  BREACH SLA',
      '────────────────────────  ──────────────────  ─────────────  ────────────  ──────────────  ──────────',
      'CloudPay HR (payroll)      Employee SSNs, bank  Completed      SOC 2 Type II  YES             24 hours',
      'QuickShip Logistics        Shipping addresses    Not sent      ← FINDING     None            ← FINDING  Not defined  ← FINDING',
      '',
      'FINDINGS:',
      '  1. QuickShip Logistics has direct access to customer shipping addresses (PII) but has',
      '     never completed a security questionnaire.',
      '  2. QuickShip\'s contract has no right-to-audit clause and no defined breach notification',
      '     SLA — if QuickShip is breached, Meridian may not learn about it in a timely manner.',
      '',
      'REMEDIATION: Send QuickShip the standard vendor security questionnaire; request their most',
      'recent attestation (SOC 2 or equivalent); renegotiate the contract to add a right-to-audit',
      'clause and a 72-hour breach notification requirement at the next renewal.',
    ].join('\n'),
    teaches:
      'CloudPay shows the target state — assessed, attested, contractually accountable. QuickShip shows the far more common reality: a vendor with real data access and zero governance wrapped around it.',
  },
  {
    match: 'show compliance audit findings',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'INTERNAL COMPLIANCE AUDIT — Meridian Retail Co. (fictional), Q1 2026',
      '',
      'FINDING                                              OWNER            TARGET DATE   STATUS',
      '────────────────────────────────────────────────────  ───────────────  ────────────  ──────────────',
      'MFA not enforced for 3 admin accounts                  IT Security Mgr  2026-04-15    Remediated',
      'Data retention policy undefined for closed accounts    (unassigned)     (none set)    ← FINDING: open, 18 months',
      'Vendor questionnaire missing for QuickShip Logistics   (unassigned)     (none set)    ← FINDING: open',
      '',
      'FINDINGS:',
      '  1. The closed-account retention finding has been open for 18 months with no owner and',
      '     no target remediation date — it has effectively become an unacknowledged accepted risk.',
      '  2. The vendor questionnaire finding correlates directly with the QuickShip gap identified',
      '     in show vendor risk assessment — the same governance failure surfacing in two reports.',
      '',
      'REMEDIATION: Assign an owner and a target date to both open findings at the next governance',
      'committee meeting; track both to closure in the risk register.',
    ].join('\n'),
    teaches:
      'An audit finding without an owner and a date is not really tracked — it is recorded. The two open findings here are 18 months old for the same underlying reason: no one was made accountable for closing them.',
  },
  {
    match: 'show business impact analysis',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'BUSINESS IMPACT ANALYSIS — Meridian Retail Co. (fictional)',
      '',
      'PROCESS                          CRITICALITY  MAX TOLERABLE DOWNTIME (MTD)',
      '────────────────────────────────  ───────────  ────────────────────────────',
      'Payment processing                 Critical     4 hours',
      'Customer order fulfilment           Critical     24 hours',
      'Payroll processing (biweekly)       High         3 business days',
      'Marketing website                   Low          5 business days',
      '',
      'MOST TIME-CRITICAL PROCESS: Payment processing — an outage longer than 4 hours',
      'is judged to cause unacceptable revenue loss and customer trust damage.',
      '',
      'NOTE: The BIA defines the requirement (MTD per process). It does not itself design',
      'the recovery solution — that is the role of business continuity and disaster',
      'recovery planning, built to meet each process\'s MTD.',
    ].join('\n'),
    teaches:
      'Payment processing has both the shortest MTD and was already flagged as a Critical risk in the risk register — the BIA and the risk register should agree on what matters most, and here they do.',
  },
];
