import type { PreparedCommand } from './types';

// ---------------------------------------------------------------------------
// Phase 9 prepared outputs — Linux Security.
//
// Same closed-allowlist contract. Artifacts describe SRV-01, the Ubuntu host
// carried since Phase 0, and are the direct counterpart to the Phase 8 Windows
// audit — the same questions asked in a different dialect.
//
// Command syntax is real and correct, so a learner can run the same commands
// on a Linux VM they own. Nothing here executes.
// ---------------------------------------------------------------------------

export const PHASE_9_COMMANDS: PreparedCommand[] = [
  {
    match: 'cat /etc/shadow',
    tool: 'linux',
    provenance: 'prepared',
    output: [
      'root:*:19700:0:99999:7:::',
      'daemon:*:19700:0:99999:7:::',
      'www-data:*:19700:0:99999:7:::',
      'sshd:*:19700:0:99999:7:::',
      'postgres:!:19812:0:99999:7:::',
      'analyst1:$6$[REDACTED]:19855:0:90:7:::',
      'svc-backup:$6$[REDACTED]:19855:0:99999:7:::',
      '',
      'Field 2 legend:  *  no password login    !  locked    $6$  SHA-512 hash',
    ].join('\n'),
    teaches:
      'Hashes are redacted here on purpose — this platform never carries usable credential material. Read the second field: * means the account cannot log in with a password, ! means locked, and $6$ is a SHA-512 hash. Note analyst1 has a 90-day maximum age while svc-backup has 99999, which is effectively never.',
  },
  {
    match: 'getent group sudo',
    tool: 'linux',
    provenance: 'prepared',
    output: ['sudo:x:27:analyst1,deploy'].join('\n'),
    teaches:
      'Group membership is how sudo access is granted on Debian-family systems. Two members — and "deploy" was not in the Phase 1 enumeration. An account added to a privileged group outside your process is exactly the Windows finding from Phase 8, in a different dialect.',
  },
  {
    match: 'sudo -l -u deploy',
    tool: 'linux',
    provenance: 'prepared',
    output: [
      'Matching Defaults entries for deploy on srv-01:',
      '    env_reset, secure_path=/usr/sbin:/usr/bin:/sbin:/bin',
      '',
      'User deploy may run the following commands on srv-01:',
      '    (ALL : ALL) NOPASSWD: ALL',
    ].join('\n'),
    teaches:
      'Compare this with the analyst1 grant from Phase 1, which permitted exactly one command. (ALL : ALL) NOPASSWD: ALL means deploy can become root, as any user, without even re-entering a password. This is the single most consequential line you can find in a sudoers file.',
  },
  {
    match: 'find / -perm -4000',
    tool: 'linux',
    provenance: 'prepared',
    output: [
      '/usr/bin/sudo',
      '/usr/bin/su',
      '/usr/bin/passwd',
      '/usr/bin/chsh',
      '/usr/bin/gpasswd',
      '/usr/bin/mount',
      '/usr/lib/openssh/ssh-keysign',
      '/usr/local/bin/backup-helper',
      '',
      '8 SUID binaries found.',
    ].join('\n'),
    teaches:
      'SUID means the binary runs as its owner rather than as you, which for root-owned files means it runs as root. The first seven are standard and expected. /usr/local/bin/backup-helper is not — anything under /usr/local is locally installed, and a custom SUID binary is a privilege-escalation path worth investigating before anything else.',
  },
  {
    match: 'ls -la /usr/local/bin/backup-helper',
    tool: 'linux',
    provenance: 'prepared',
    output: [
      '-rwsr-xr-x 1 root root 16744 Sep  8 02:54 /usr/local/bin/backup-helper',
      '',
      'Mode 4755:  s in the owner execute position = SUID',
      'Owner root, so this runs with root privilege for any user who executes it.',
      'Created 2026-09-08 02:54 — two minutes after the Phase 7 intrusion.',
    ].join('\n'),
    teaches:
      'Read the mode string: -rwsr-xr-x has an s where the owner execute bit would be, which is SUID. Owned by root and executable by everyone means any user runs it as root. The creation timestamp places it inside the incident window — this is Linux persistence, the counterpart to the Phase 8 scheduled task.',
  },
  {
    match: 'explain linux permissions',
    tool: 'linux',
    provenance: 'simulated',
    output: [
      'MODE STRING     - rwx r-x r-x',
      '                │  │   │   └── other',
      '                │  │   └────── group',
      '                │  └────────── owner',
      '                └───────────── type (- file, d dir, l link)',
      '',
      'NUMERIC   r=4  w=2  x=1     rwx=7  rw-=6  r-x=5  r--=4',
      '',
      'SPECIAL BITS',
      '  SUID  4000   s in owner execute    runs as the FILE OWNER',
      '  SGID  2000   s in group execute    runs as group / dir inherits group',
      '  Sticky 1000  t in other execute    only the owner may delete (see /tmp)',
      '',
      'DIRECTORIES ARE DIFFERENT',
      '  r  list the names inside',
      '  w  create and DELETE entries — including files you do not own',
      '  x  traverse into it / access a known path',
      '',
      'A directory you can write lets you delete files you cannot write.',
    ].join('\n'),
    teaches:
      'The directory rules catch people out. Write permission on a directory means you can delete any file in it regardless of that file own permissions, because deletion modifies the directory rather than the file. That is what the sticky bit on /tmp exists to prevent.',
  },
  {
    match: 'show sshd config',
    tool: 'linux',
    provenance: 'prepared',
    output: [
      '# /etc/ssh/sshd_config — SRV-01 effective settings',
      '',
      'Port 22',
      'PermitRootLogin yes                 <-- finding',
      'PasswordAuthentication yes          <-- finding',
      'PubkeyAuthentication yes',
      'PermitEmptyPasswords no',
      'MaxAuthTries 6                      <-- finding (recommend 3)',
      'X11Forwarding yes                   <-- finding (not needed on a server)',
      'ClientAliveInterval 0               <-- finding (sessions never time out)',
      'AllowUsers (not set)                <-- finding (no allowlist)',
      'Protocol 2',
      'LogLevel INFO',
    ].join('\n'),
    teaches:
      'PermitRootLogin yes combined with PasswordAuthentication yes is the pairing that matters: it means root is directly brute-forceable over the network. Fixing either one breaks that path, and fixing both is correct. Note the config file may contain settings that are overridden later in the file — always verify with sshd -T rather than reading the file top to bottom.',
  },
  {
    match: 'harden sshd',
    tool: 'linux',
    provenance: 'simulated',
    output: [
      'SSH HARDENING — recommended changes for SRV-01',
      '',
      'SETTING                    FROM   TO             WHY',
      'PermitRootLogin            yes    prohibit-password  or no',
      '                                                 Removes direct root brute force',
      'PasswordAuthentication     yes    no             Keys only; defeats guessing',
      'MaxAuthTries               6      3              Fewer attempts per connection',
      'X11Forwarding              yes    no             Unused attack surface on a server',
      'ClientAliveInterval        0      300            Idle sessions expire',
      'AllowUsers                 unset  analyst1 deploy  Explicit allowlist',
      '',
      'ORDER MATTERS: confirm key-based login WORKS in a second session before',
      'setting PasswordAuthentication no. Otherwise you lock yourself out of a',
      'remote host and the fix requires console access you may not have.',
      '',
      'Validate before reloading:   sshd -t',
      'Apply:                       systemctl reload sshd',
    ].join('\n'),
    teaches:
      'The sequencing warning is the practical lesson. Disabling password authentication before verifying your key works is the classic way to lock yourself out of a remote server — always keep a second session open and test in it. And run sshd -t first: a syntax error on reload can leave the daemon refusing to start.',
  },
  {
    match: 'show auth log linux',
    tool: 'linux',
    provenance: 'prepared',
    output: [
      'Sep  8 02:41:07 srv-01 sshd[2201]: Failed password for root from 198.51.100.77 port 51022',
      'Sep  8 02:41:09 srv-01 sshd[2203]: Failed password for root from 198.51.100.77 port 51024',
      'Sep  8 02:41:11 srv-01 sshd[2205]: Failed password for invalid user admin from 198.51.100.77',
      'Sep  8 02:41:14 srv-01 sshd[2207]: Failed password for invalid user oracle from 198.51.100.77',
      '  ... 1,204 further failures from 198.51.100.77 over 6 minutes ...',
      'Sep  8 02:47:31 srv-01 sshd[2891]: Accepted publickey for deploy from 198.51.100.77',
      'Sep  8 02:47:31 srv-01 sshd[2891]: pam_unix(sshd:session): session opened for user deploy',
      'Sep  8 02:53:02 srv-01 sudo:   deploy : TTY=pts/1 ; PWD=/tmp ; USER=root ; COMMAND=/bin/bash',
      'Sep  8 08:14:52 srv-01 sudo: analyst1 : TTY=pts/0 ; PWD=/home/analyst1 ; USER=root ;',
      '                              COMMAND=/usr/bin/systemctl restart nginx',
    ].join('\n'),
    teaches:
      'Read the transition. Over a thousand password failures, then a success — but "Accepted publickey", not a password. The brute force never worked; the attacker already had a key. Then deploy escalates to a root shell six minutes later. Contrast the final line: analyst1 running one scoped command during working hours is what legitimate sudo looks like.',
  },
  {
    match: 'systemctl list-units suspicious',
    tool: 'linux',
    provenance: 'prepared',
    output: [
      'UNIT                     LOAD   ACTIVE SUB     DESCRIPTION',
      'nginx.service            loaded active running A high performance web server',
      'ssh.service              loaded active running OpenBSD Secure Shell server',
      'postgresql.service       loaded active running PostgreSQL RDBMS',
      'sysstat-collect.timer    loaded active waiting Run system activity accounting',
      'cloud-sync.service       loaded active running Cloud Sync Helper',
      '',
      '--- cloud-sync.service ---',
      '  Loaded: /etc/systemd/system/cloud-sync.service',
      '  Created: 2026-09-08 02:55',
      '  ExecStart=/usr/local/bin/backup-helper --daemon',
      '  User=root',
      '  Restart=always',
      '  WantedBy=multi-user.target',
    ].join('\n'),
    teaches:
      'A benign name, root privilege, Restart=always so it survives being killed, and WantedBy=multi-user.target so it survives reboot. Created a minute after the SUID binary. This is the same persistence pattern as the Phase 8 scheduled task, expressed through systemd — and note it executes the same suspicious binary.',
  },
  {
    match: 'show ufw status',
    tool: 'linux',
    provenance: 'prepared',
    output: [
      'Status: active',
      'Default: deny (incoming), allow (outgoing), disabled (routed)',
      '',
      'To                         Action      From',
      '--                         ------      ----',
      '22/tcp                     ALLOW IN    Anywhere',
      '80/tcp                     ALLOW IN    Anywhere',
      '443/tcp                    ALLOW IN    Anywhere',
      '5432/tcp                   ALLOW IN    192.168.1.0/24',
      '',
      'Note: postgres also binds to 127.0.0.1 only, so this rule grants nothing',
      'additional. Defence in depth, or a leftover from an earlier design?',
    ].join('\n'),
    teaches:
      'Default deny inbound with an explicit allowlist is correct. The postgres rule is interesting: the service is already bound to loopback, so the firewall rule is redundant. That is either deliberate layering or a stale rule from when the service was exposed — and knowing which requires asking, not guessing. Redundant rules accumulate and eventually nobody dares remove any of them.',
  },
  {
    match: 'show package status',
    tool: 'linux',
    provenance: 'prepared',
    output: [
      'Package management — SRV-01 (Ubuntu 22.04 LTS)',
      '',
      'Security updates pending:        7',
      'Total updates pending:          23',
      'Unattended-upgrades:        enabled (security only)',
      'Last successful apt update: 2026-09-07 06:14',
      '',
      'THIRD-PARTY REPOSITORIES',
      '  /etc/apt/sources.list.d/vendor-tools.list',
      '    deb [trusted=yes] http://packages.vendor.example/ubuntu jammy main',
      '                       ^^^^^^^^^^^^^  ^^^^',
      '                       signature check disabled, and plain HTTP',
    ].join('\n'),
    teaches:
      'trusted=yes disables signature verification for that repository, and http means the transport is unauthenticated too. Together they mean anyone who can intercept the connection can install packages as root on this host. This is the Phase 3 supply-chain lesson as a concrete configuration line.',
  },
  {
    match: 'show auditd rules',
    tool: 'linux',
    provenance: 'prepared',
    output: [
      'auditd status: active',
      '',
      'RULE                                                    WATCHES',
      '-w /etc/passwd -p wa -k identity                        account changes',
      '-w /etc/shadow -p wa -k identity                        credential changes',
      '-w /etc/sudoers -p wa -k privilege                      sudo policy changes',
      '-w /etc/ssh/sshd_config -p wa -k sshd                   remote access config',
      '-a always,exit -F arch=b64 -S execve -k exec            all process execution',
      '',
      'NOT WATCHED',
      '  /etc/systemd/system/          <-- new services are not audited',
      '  /usr/local/bin/               <-- locally installed binaries not audited',
      '',
      'Both gaps were used by this intrusion.',
    ].join('\n'),
    teaches:
      'auditd is the Linux counterpart to Sysmon: -w watches a path, -p wa means write and attribute changes, and -k tags events for searching. The gaps matter more than the rules here — the attacker placed a SUID binary in /usr/local/bin and a unit file in /etc/systemd/system, and neither location was being watched.',
  },
  {
    match: 'compare windows linux security',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'CONCEPT              WINDOWS                    LINUX',
      '-------------------  -------------------------  --------------------------',
      'Identity             SID                        UID / GID',
      'Privileged account   Administrator (RID 500)    root (UID 0)',
      'Elevation            UAC + admin group          sudo + sudoers',
      'File permissions     ACLs (granular, ordered)   rwx triplets + special bits',
      'Escalation via file  Writable service binary    SUID root binary',
      'Persistence          Scheduled task, Run key,   systemd unit, cron,',
      '                     service                    .bashrc, SUID binary',
      'Auth logging         4624 / 4625 / 4688         auth.log, journald',
      'Process auditing     Sysmon                     auditd',
      'Remote admin         RDP                        SSH',
      'Host firewall        Windows Firewall profiles  ufw / firewalld / nftables',
      'Patching             Windows Update             apt / dnf',
      '',
      'The questions are identical. Only the dialect changes.',
    ].join('\n'),
    teaches:
      'This is the payoff of doing both phases. Every question you asked of Windows has a Linux equivalent: who has privilege, what runs at boot, what is logged, what is exposed. Learning the mapping means a new platform is a vocabulary problem rather than a fresh start.',
  },
];
