import type { PreparedCommand } from './types';

// ---------------------------------------------------------------------------
// Phase 7 prepared outputs — Security Operations / SOC.
//
// Same closed-allowlist contract. These are SIEM-shaped artifacts: query
// results, rule definitions, and dashboard summaries the learner reads as an
// analyst would.
// ---------------------------------------------------------------------------

export const PHASE_7_COMMANDS: PreparedCommand[] = [
  {
    match: 'compare detection tooling',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'TOOL   SEES                          SCOPE            PRIMARY JOB',
      '-----  ----------------------------  ---------------  ----------------------------',
      'SIEM   Logs from everything          Whole estate     Correlate and alert',
      'EDR    Process, file, registry,      Endpoints only   Detect and respond on host',
      '       network from the endpoint',
      'XDR    EDR plus network, identity,   Multiple layers  Correlate across those layers',
      '       email, cloud telemetry',
      'SOAR   Alerts plus playbooks         Response layer   Automate the repetitive response',
      '',
      'The distinction that matters: SIEM ingests what other systems send it.',
      'EDR generates its own telemetry from an agent on the host. XDR is EDR',
      'that also correlates beyond the endpoint. SOAR does not detect anything —',
      'it acts on what the others found.',
    ].join('\n'),
    teaches:
      'A common exam trap is treating SOAR as a detection tool. It is an automation layer: it takes an alert that already exists and runs a playbook — enrich the indicator, open the ticket, isolate the host. If a question asks what found the incident, SOAR is never the answer.',
  },
  {
    match: 'compare ioc ioa',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'INDICATOR OF COMPROMISE (IOC)      INDICATOR OF ATTACK (IOA)',
      '---------------------------------  ---------------------------------',
      'An artifact: hash, IP, domain,     A behaviour: what the attacker is',
      'filename, registry key             trying to DO',
      '',
      'Example from this incident:',
      '  IOC  203.0.113.55                IOA  interactive shell holding a',
      '  IOC  srv01-portal-login.example        long-lived outbound TLS session',
      '                                        at a regular interval',
      '',
      'IOCs are precise and brittle — the attacker changes the address and your',
      'detection stops working.',
      'IOAs are durable — the behaviour is what the attacker needs to do, and',
      'changing it costs them capability.',
      '',
      'Mature detection favours IOAs. IOCs remain useful for fast retrospective',
      'search: "has anything in the estate ever talked to this address?"',
    ].join('\n'),
    teaches:
      'This is the difference between blocking one address and detecting the technique. An IOC tells you a specific attacker was here; an IOA tells you that something is beaconing regardless of where it beacons to.',
  },
  {
    match: 'show siem rule beacon',
    tool: 'platform',
    provenance: 'prepared',
    output: [
      'RULE     Suspicious outbound beaconing',
      'TYPE     Behavioural (IOA)',
      'SOURCES  firewall flow log, EDR process telemetry',
      '',
      'LOGIC',
      '  GROUP BY  src_ip, dst_ip, dst_port',
      '  WINDOW    30 minutes',
      '  WHERE     connection_count >= 5',
      '    AND     stddev(interval_seconds) < 15      -- regularity, not volume',
      '    AND     stddev(bytes) < 512                -- near-constant payload',
      '    AND     process IN (powershell.exe, cmd.exe, wscript.exe, rundll32.exe)',
      '',
      'SEVERITY critical',
      'TUNING   Exclude documented monitoring agents and update services by',
      '         process path, NOT by destination address.',
      '',
      'Why regularity rather than volume: a beacon is small and periodic.',
      'A volume threshold would have missed it entirely and caught the nightly',
      'backup instead.',
    ].join('\n'),
    teaches:
      'Note what this rule does NOT use: volume. The beacon moved about 4 KB per check-in — utterly unremarkable. Standard deviation of the interval is the signal, because humans and normal software do not connect on a metronome.',
  },
  {
    match: 'show alert queue',
    tool: 'platform',
    provenance: 'prepared',
    output: [
      'TIME      SEVERITY  ALERT                                    HOST     STATUS',
      '--------  --------  ---------------------------------------  -------  --------',
      '02:44:36  medium    Multiple failed logons from one source    DC-01    new',
      '02:47:02  high      Auth from unfamiliar ASN at unusual hour  DC-01    new',
      '02:51:53  critical  Interactive PowerShell, sustained TLS     WS-01    new',
      '03:00:04  high      Large outbound transfer to external host  SRV-01   new',
      '08:14:52  medium    Privilege escalation via sudo             SRV-01   new',
      '',
      'Five alerts. Not five incidents.',
      '',
      'Two of these are noise. Deciding which is the entire job — an analyst who',
      'escalates everything is as unhelpful as one who escalates nothing.',
    ].join('\n'),
    teaches:
      'Alert fatigue is a real security failure, not just an annoyance. A queue where most alerts are noise trains analysts to skim, and the one that mattered gets skimmed too. Tuning out false positives is defensive work.',
  },
  {
    match: 'show log sources',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'SOURCE            ANSWERS                              KEY EVENT IDS / FIELDS',
      '----------------  -----------------------------------  ------------------------',
      'Windows Event     Who authenticated, what ran          4624 logon success',
      '                                                       4625 logon failure',
      '                                                       4688 process creation',
      '                                                       4672 special privileges',
      'Linux auth.log    Who authenticated, sudo use          sshd, sudo, CRON',
      'Firewall flow     What talked to what, how much        src, dst, port, bytes,',
      '                                                       duration, policy name',
      'DNS query         What names were resolved             query, response, host',
      'Web proxy         What URLs were fetched               url, category, verdict',
      'EDR               Process trees, parent-child          pid, ppid, command line',
      '',
      'NO SINGLE SOURCE SEES THE WHOLE ATTACK. That is why they are centralised.',
    ].join('\n'),
    teaches:
      'Learn what each source can and cannot answer. DNS logs tell you a name was resolved but not what happened next; firewall logs tell you bytes moved but not which process moved them. The answer usually requires two sources joined on a shared indicator.',
  },
  {
    match: 'show pivot example',
    tool: 'platform',
    provenance: 'prepared',
    output: [
      'PIVOTING — following one indicator across sources',
      '',
      'START   EDR alert names a suspicious process on WS-01, pid 6644',
      '',
      '  pivot on pid 6644',
      '  -> Windows 4688: powershell.exe created, parent explorer.exe',
      '',
      '  pivot on host WS-01 around that time',
      '  -> DNS: query for updates.example.net -> 203.0.113.55',
      '',
      '  pivot on 203.0.113.55',
      '  -> Firewall: three flows, 5 minutes apart, ~4 KB each',
      '',
      '  pivot on user analyst1',
      '  -> Windows 4624 success from 198.51.100.77 at 02:47',
      '  -> Windows 4625 x3 from the same address, minutes earlier',
      '',
      '  pivot on 198.51.100.77',
      '  -> nothing else. First and only time this address appears.',
      '',
      'RESULT  A process alert became a full intrusion timeline in five pivots.',
    ].join('\n'),
    teaches:
      'Each pivot answers one question and raises the next. Notice the last pivot returning nothing useful — that is also a finding: the source address appears exactly once, which is consistent with a targeted attempt rather than broad scanning.',
  },
  {
    match: 'show triage workflow',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'ALERT TRIAGE — the analyst loop',
      '',
      '  1  VALIDATE     Is the alert what it claims? Read the rule logic.',
      '  2  SCOPE        One host or many? One user or many?',
      '  3  ENRICH       Reputation, asset owner, business context, change tickets.',
      '  4  PIVOT        Follow indicators across sources to build a timeline.',
      '  5  DECIDE       True positive -> escalate. False positive -> close AND tune.',
      '  6  DOCUMENT     What you saw, what you concluded, what you did.',
      '',
      'STEP 3 IS THE ONE ANALYSTS SKIP.',
      'The 4.2 GB transfer looked alarming until enrichment showed a change',
      'ticket, a cron job, and a policy literally named backup-egress.',
      '',
      'Closing a false positive WITHOUT tuning the rule means you will triage',
      'the same alert again next week, and the week after.',
    ].join('\n'),
    teaches:
      'Step 5 has two halves and the second gets dropped under pressure. An untuned false positive is a permanent tax on every future shift — closing it without tuning means you have done the work and kept the problem.',
  },
  {
    match: 'show dashboard summary',
    tool: 'platform',
    provenance: 'prepared',
    output: [
      'SOC DASHBOARD — 24 hour summary',
      '',
      'ALERTS BY SEVERITY        MEAN TIME (minutes)',
      '  critical    1             to detect (MTTD)      11',
      '  high        2             to acknowledge         4',
      '  medium      2             to triage             23',
      '  low         0             to escalate           31',
      '',
      'DISPOSITION               TOP INDICATORS',
      '  escalated       3         203.0.113.55        7 events',
      '  closed FP       2         198.51.100.77       4 events',
      '  open            0         updates.example.net 1 event',
      '',
      'FALSE POSITIVE RATE  40%   <-- two of five alerts were noise',
      '',
      'A 40% false positive rate is a tuning problem, not an analyst problem.',
    ].join('\n'),
    teaches:
      'Mean time to detect is the number that matters most: everything the attacker does between compromise and detection is uncontested. Note the false positive rate is presented as a tuning problem — measuring analysts on volume rather than fixing the rules produces faster skimming, not better security.',
  },
];
