import type { PreparedCommand } from './types';

// ---------------------------------------------------------------------------
// Phase 4 prepared outputs — Security Architecture.
//
// Same closed-allowlist contract. Addressing extends the existing lab estate:
// Core 192.168.1.0/24 (from Phase 0), plus segment VLANs and a DMZ in RFC 1918
// space. External addresses remain RFC 5737 documentation ranges.
// ---------------------------------------------------------------------------

export const PHASE_4_COMMANDS: PreparedCommand[] = [
  {
    match: 'show zones',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'Enterprise security zones — trust ascending',
      '',
      'ZONE         TRUST  VLAN      NETWORK             ROLE',
      '-----------  -----  --------  ------------------  ----------------------------',
      'Internet         0  —         —                   Wholly untrusted',
      'Guest            5  VLAN 50   10.50.0.0/24        Visitor wireless, egress only',
      'DMZ             25  VLAN 20   172.16.20.0/24      Internet-facing services',
      'Users           55  VLAN 30   192.168.30.0/24     Staff workstations',
      'Core            60  VLAN 10   192.168.1.0/24      Transit and inspection',
      'Servers         75  VLAN 40   192.168.40.0/24     Internal applications',
      'Management      95  VLAN 99   10.99.0.0/24        Out-of-band administration',
      '',
      'A boundary exists wherever trust changes. That is where controls go.',
    ].join('\n'),
    teaches:
      'Note that Guest sits at trust 5 — barely above the Internet — while Management sits at 95. Zones are not about geography or department; they are about how much you are willing to assume about what is inside.',
  },
  {
    match: 'inspect boundary internet-dmz',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'Boundary: Internet (trust 0) -> DMZ (trust 25)     delta 25',
      '',
      'CONTROLS',
      '  Perimeter firewall (FW-01)      stateful, deny by default',
      '  Web application firewall        inspects HTTP request content',
      '  Reverse proxy                   terminates TLS, hides origin',
      '  IPS                             inline, blocks on signature match',
      '',
      'ALLOWED INBOUND',
      '  TCP 443  -> reverse proxy',
      '  TCP  53  -> external resolver',
      '',
      'DENIED',
      '  Every other inbound port',
      '  Any direct inbound connection past the DMZ',
      '  Inbound SSH, RDP, SNMP',
    ].join('\n'),
    teaches:
      'Two controls that are constantly confused sit here. An IDS is passive: it observes a copy of the traffic and alerts. An IPS is inline: traffic passes through it and it can drop. A WAF is neither — it is application-aware, inspecting HTTP request content rather than packets and ports.',
  },
  {
    match: 'inspect boundary dmz-core',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'Boundary: DMZ (trust 25) -> Core (trust 60)        delta 35',
      '',
      'CONTROLS',
      '  Internal firewall               deny by default, both directions',
      '  IDS sensor                      passive, on a span port',
      '  Application-layer proxy         no direct socket between zones',
      '',
      'ALLOWED',
      '  Reverse proxy -> SRV-01 TCP 443, inbound-initiated only',
      '',
      'DENIED',
      '  DMZ hosts initiating ANY connection into the Core',
      '  DMZ hosts reaching DC-01',
      '  Management protocols from the DMZ',
      '',
      'This is the boundary that decides whether a compromised public service',
      'means a foothold or means the estate.',
    ].join('\n'),
    teaches:
      'The direction of initiation matters as much as the port. The proxy may forward an inbound request to SRV-01, but a DMZ host may never start a conversation inward. Reverse that rule and the DMZ stops being a screened subnet and becomes a staging area.',
  },
  {
    match: 'inspect boundary users-management',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'Boundary: Users (trust 55) -> Management (trust 95)  delta 40  <-- steepest',
      '',
      'CONTROLS',
      '  Firewall policy                 deny all, no exceptions',
      '  Jump host                       MFA required, session recorded',
      '  Privileged access workstation   hardened, no email, no browsing',
      '',
      'ALLOWED',
      '  Nothing directly.',
      '',
      'DENIED',
      '  All traffic from VLAN 30 to VLAN 99',
      '  Administrative protocols from any general-purpose workstation',
      '',
      'Rationale: if a phished workstation could reach VLAN 99, one click would',
      'compromise the firewall, the SIEM, and the backups simultaneously.',
    ].join('\n'),
    teaches:
      'The steepest trust delta in the design gets the strictest control — deny-all rather than a port list. Notice the PAW has no email and no browsing: the administrator uses a different machine for the risky activities, so the machine holding the keys never touches an attachment.',
  },
  {
    match: 'compare ids ips waf',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'CONTROL  PLACEMENT   SEES                 CAN BLOCK  FAILS TO',
      '-------  ----------  -------------------  ---------  --------------------------',
      'IDS      Out of band  Copy of traffic      No         Detect only; alerts',
      '         (span/tap)                                   after the fact',
      'IPS      Inline       Live traffic         Yes        Becomes a bottleneck and',
      '                                                      a single point of failure',
      'WAF      Inline, L7   HTTP request content Yes        Only understands web;',
      '         (proxy)                                      blind to non-HTTP traffic',
      '',
      'Trade-off: an IDS cannot break your network but cannot stop an attack.',
      'An IPS can stop an attack and can break your network. Both are legitimate',
      'choices; the question is what an outage costs you versus a breach.',
    ].join('\n'),
    teaches:
      'Placement determines capability. Out-of-band means a copy, which means detection only. Inline means the traffic passes through, which means blocking becomes possible and availability becomes a risk. This trade-off appears on the exam constantly.',
  },
  {
    match: 'show segmentation policy',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'Inter-zone policy matrix  (rows initiate, columns receive)',
      '',
      '             INTERNET  DMZ    CORE   USERS  SERVERS  MGMT   GUEST',
      'INTERNET     —         443/53 DENY   DENY   DENY     DENY   DENY',
      'DMZ          egress    —      443*   DENY   DENY     DENY   DENY',
      'CORE         proxy     any    —      any    any      DENY   DENY',
      'USERS        proxy     DENY   any    —      443,389  DENY   DENY',
      'SERVERS      proxy     DENY   any    DENY   —        DENY   DENY',
      'MGMT         proxy     any    any    any    any      —      DENY',
      'GUEST        direct    DENY   DENY   DENY   DENY     DENY   DENY',
      '',
      '* inbound-initiated only, via the reverse proxy',
      '',
      'Read the GUEST row: one permitted destination, the Internet, and it does',
      'not transit the Core to get there.',
    ].join('\n'),
    teaches:
      'Read a policy matrix by rows first — what may this zone start? Servers cannot initiate to Users, which stops a compromised server pivoting to workstations. Management can reach everything but nothing can reach Management: administration flows one way by design.',
  },
  {
    match: 'show honeypot',
    tool: 'platform',
    provenance: 'prepared',
    output: [
      'Deception assets — simulated',
      '',
      'ASSET        TYPE       PLACEMENT     PURPOSE',
      'HP-01        Honeypot   DMZ           Fake SSH service, no real access',
      'HP-02        Honeypot   Servers VLAN  Fake file share named "HR-Payroll-2026"',
      'HONEYNET-A   Honeynet   Isolated      Full fake segment, observed end to end',
      '',
      'HP-02 alert log (last 24h):',
      '  02:51  SMB enumeration from 192.168.30.44 (Users VLAN)',
      '  02:53  Access attempt to \\\\HP-02\\HR-Payroll-2026',
      '',
      'No legitimate business process touches HP-02. Any interaction with it is,',
      'by construction, either a misconfiguration or an intruder.',
    ].join('\n'),
    teaches:
      'The value of a honeypot is its near-zero false-positive rate. Normal monitoring drowns in benign activity; a decoy nothing legitimate should ever touch turns any single interaction into a high-confidence signal. Note the trade-off: honeypots detect, they do not protect.',
  },
  {
    match: 'show high availability',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'Availability design — Northwind reference architecture',
      '',
      'COMPONENT          REDUNDANCY          FAILOVER   SINGLE POINT OF FAILURE?',
      'Perimeter firewall  Active/passive pair  ~3 s       No',
      'Core switching      Stacked pair         sub-second No',
      'SRV-01 application  Two nodes + LB       ~5 s       No',
      'DC-01 directory     Single node          none       YES  <-- finding',
      'Internet link       Single ISP           none       YES  <-- finding',
      '',
      'Two single points of failure remain. Availability is part of the CIA triad,',
      'so these are security findings, not merely operational ones.',
    ].join('\n'),
    teaches:
      'Redundancy removes single points of failure; high availability adds automatic failover so the redundancy is used without a human. A lone domain controller means an authentication outage takes down every zone at once — which is why availability sits in the CIA triad alongside confidentiality.',
  },
  {
    match: 'trace flow users servers',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'Flow trace: WS-01 (Users, VLAN 30) -> SRV-01 (Servers, VLAN 40) TCP 443',
      '',
      '  [1] NAC          Device posture verified at connection; VLAN 30 assigned',
      '  [2] SWITCH       Frame tagged VLAN 30, forwarded to the Core',
      '  [3] CORE         Routed between VLANs — policy can now apply',
      '  [4] FIREWALL     Rule "users->servers allow 443" matched, flow logged',
      '  [5] IDS          Copy inspected on the span port; no signature match',
      '  [6] SERVER       SRV-01 accepts on TCP 443',
      '  [7] APP          Application authenticates and authorises the request',
      '',
      'Note step 3. Traffic between VLANs is ROUTED, which is precisely what makes',
      'step 4 possible. Traffic switched within one VLAN never meets a policy.',
    ].join('\n'),
    teaches:
      'This is the Phase 1 connection path with zones added. The reason segmentation works is visible at step 3: putting hosts in different VLANs forces their traffic through a router, and a router is somewhere you can attach policy. Same-VLAN traffic is invisible to the firewall.',
  },
  {
    match: 'trace flow guest servers',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'Flow trace: Guest device (VLAN 50) -> SRV-01 (Servers, VLAN 40) TCP 443',
      '',
      '  [1] NAC          Unmanaged device; assigned to guest VLAN 50',
      '  [2] SWITCH       Client isolation active — cannot reach other guests',
      '  [3] ROUTING      No route to 192.168.40.0/24 exists from VLAN 50',
      '  [4] BLOCKED      Packet discarded. Firewall rule not even consulted.',
      '',
      'RESULT: DENIED at layer 3. There is no path to filter, because there is no',
      'path at all.',
    ].join('\n'),
    teaches:
      'The strongest control is the absence of a route. A firewall rule can be misconfigured; a route that does not exist cannot be. Compare this with the Phase 2 lesson that surface reduction beats surface protection — the same principle at network scale.',
  },
];
