import type { PreparedCommand } from './types';

// ---------------------------------------------------------------------------
// Phase 12 prepared outputs — Incident Response.
//
// Same closed-allowlist contract. These artifacts close the incident the
// platform has carried since Phase 0.
// ---------------------------------------------------------------------------

export const PHASE_12_COMMANDS: PreparedCommand[] = [
  {
    match: 'explain ir lifecycle',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'INCIDENT RESPONSE LIFECYCLE',
      '',
      '  1 PREPARATION      Plan, playbooks, tooling, contacts, authority to act',
      '  2 DETECTION        Something is wrong and we know it',
      '  3 ANALYSIS         What happened, how far it reaches, what it touched',
      '  4 CONTAINMENT      Stop it spreading WITHOUT destroying evidence',
      '  5 ERADICATION      Remove the attacker, including persistence',
      '  6 RECOVERY         Return to service and watch',
      '  7 LESSONS LEARNED  Change what allowed it',
      '',
      'PREPARATION IS THE ONLY PHASE THAT HAPPENS BEFORE AN INCIDENT.',
      'Everything an organisation does badly during a response was decided',
      'before the incident started: whether the logs exist, whether anyone has',
      'authority to disconnect a production host at 03:00, whether the contact',
      'list is current.',
      '',
      'The loop closes: lessons learned feeds back into preparation.',
    ].join('\n'),
    teaches:
      'Preparation is the phase nobody practises and the one that decides how the other six go. During the Phase 7 investigation the evidence existed because someone had configured DNS logging and log forwarding months earlier — a preparation decision made long before anyone knew it would matter.',
  },
  {
    match: 'explain order of volatility',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'ORDER OF VOLATILITY — most volatile first (RFC 3227)',
      '',
      '  1  CPU registers and cache          gone when the process stops',
      '  2  MEMORY (RAM)                     processes, command lines, keys',
      '  3  Network state, running processes live connections, ARP, routing',
      '  4  Temporary filesystems            cleared on reboot',
      '  5  Disk                             survives reboot',
      '  6  Remote logs and monitoring       already off the host',
      '  7  Physical configuration           stable',
      '  8  Archival media and backups       most durable',
      '',
      'THE PRACTICAL CONSEQUENCE',
      '  "Reboot it" discards ranks 1-4 instantly. For a living-off-the-land',
      '  attack that is the whole case: the binary is legitimate and only the',
      '  command line was hostile, and the command line lived in memory.',
      '',
      'CHAIN OF CUSTODY starts at the first capture: who collected it, when,',
      'from where, and every hand it passed through. A gap in that record is',
      'evidence a lawyer can exclude.',
    ].join('\n'),
    teaches:
      'The ordering is not a preference, it is a constraint — collecting out of order does not delay the volatile items, it loses them. Note the interaction with Phase 3: when an attacker lives off the land, memory is often the only place the actual malicious content ever existed.',
  },
  {
    match: 'explain containment tradeoff',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'CONTAINMENT — every action judged on two axes',
      '',
      'ACTION                          STOPS ATTACKER  PRESERVES EVIDENCE',
      '------------------------------  --------------  ------------------',
      'Capture memory, then isolate           yes             yes',
      'Disable account + revoke tokens        yes             yes',
      'Network isolate the host               yes             yes',
      'Block the C2 address                   no              yes',
      'Kill the malicious process             partly          NO',
      'Reboot the host                        no              NO',
      'Reimage immediately                    yes             NO',
      'Monitor and do nothing                 no              yes',
      '',
      'THE TRAP: the fastest, most decisive-feeling actions sit in the NO column.',
      '',
      'Rebooting fails BOTH tests — it destroys memory and the persistence',
      'mechanism restores the beacon at startup. It feels like doing something.',
      '',
      'Monitoring is legitimate when the attacker is already contained and you',
      'are mapping infrastructure. It is not legitimate while they hold active',
      'root on a second host.',
    ].join('\n'),
    teaches:
      'The two-axis framing is what makes containment decisions arguable rather than obvious. Note that reimaging genuinely stops the attacker on that host and is still usually wrong early — you lose the ability to answer how they got in and whether anything else is affected, and the credentials they used are still valid.',
  },
  {
    match: 'show incident timeline',
    tool: 'platform',
    provenance: 'prepared',
    output: [
      'IR-2026-0908-01 — reconstructed timeline',
      '',
      'TIME      EVENT                                          SOURCE',
      '02:41:58  DNS query for the lookalike domain             DNS log',
      '02:42:31  Credentials submitted to the lookalike page    Web proxy',
      '02:44:07  Three failed logons, varying usernames         Windows 4625',
      '02:47:02  Successful logon from an unfamiliar ASN        Windows 4624',
      '02:47:31  SSH accepted by publickey on SRV-01            auth.log',
      '02:51:44  PowerShell created from explorer.exe           Windows 4688',
      '02:51:53  First outbound beacon to 203.0.113.55          Firewall flow',
      '02:53:02  Root shell obtained on SRV-01 via sudo         auth.log',
      '02:54:00  SUID root binary written to /usr/local/bin     Filesystem',
      '02:55:00  systemd unit created for persistence           systemd',
      '03:02:10  EDR raises behavioural beaconing detection     EDR',
      '',
      'DWELL TIME: 20 minutes 12 seconds from first query to detection.',
      'SIX SOURCES. No single one of them saw the whole attack.',
    ].join('\n'),
    teaches:
      'Twenty minutes of uncontested access, and the detection came at stage five of six. Note the sources column — the timeline exists because DNS, proxy, Windows, Linux, firewall and EDR logs were all being collected centrally, which was a preparation decision taken long before this incident.',
  },
  {
    match: 'show eradication checklist',
    tool: 'platform',
    provenance: 'prepared',
    output: [
      'ERADICATION — IR-2026-0908-01',
      '',
      'WS-01 (Windows)',
      '  [ ] Capture the scheduled task SystemHealthCheck as evidence',
      '  [ ] Remove the scheduled task',
      '  [ ] Remove analyst1 from local Administrators',
      '',
      'SRV-01 (Linux)',
      '  [ ] Capture /usr/local/bin/backup-helper as evidence',
      '  [ ] Remove the SUID binary',
      '  [ ] Remove the cloud-sync.service systemd unit',
      '  [ ] Reduce or remove the deploy account sudo grant',
      '',
      'IDENTITY',
      '  [ ] Reset analyst1 credentials',
      '  [ ] Re-enrol MFA on a phishing-resistant factor',
      '  [ ] Revoke all existing sessions and refresh tokens',
      '',
      'VERIFY',
      '  [ ] Confirm no other host carries the same artifacts',
      '',
      'ERADICATION IS NOT COMPLETE UNTIL PERSISTENCE IS GONE FROM BOTH HOSTS.',
      'Cleaning WS-01 alone leaves a root-level systemd unit running on SRV-01.',
    ].join('\n'),
    teaches:
      'Note the capture-before-remove pairing on every persistence item. And note the scope: the alert named WS-01, and eradication that follows the alert rather than the investigation leaves an attacker with root on the second host. Incomplete eradication is why incidents recur.',
  },
  {
    match: 'show lessons learned',
    tool: 'platform',
    provenance: 'prepared',
    output: [
      'LESSONS LEARNED — IR-2026-0908-01  (blameless)',
      '',
      'CONTROL GAP                              PHASE FIRST IDENTIFIED',
      'DMARC not enforced                       Phase 3 — headers showed p=NONE',
      'MFA factor was relayable push            Phase 5 — factor choice',
      'PowerShell script block logging off      Phase 8 — logging baseline',
      'auditd not watching persistence paths    Phase 9 — rule coverage',
      'Firewall permit-any from 2025 migration  Phase 11 — rule shadowing',
      '',
      'MEAN TIME TO DETECT     20 min from delivery, 11 min from first beacon',
      'MEAN TIME TO CONTAIN    target under 30 min from detection',
      '',
      'THE SINGLE HIGHEST-VALUE CHANGE',
      '  Phishing-resistant MFA. The user still clicks, the password is still',
      '  submitted, and the authentication fails — because a FIDO2 authenticator',
      '  will not respond to a lookalike origin.',
      '',
      '  Every stage after the third depended on that credential working.',
      '',
      'BLAMELESS MEANS BLAMELESS. Every row above is a control gap. None of them',
      'is "the user clicked a link" — users will always eventually click.',
    ].join('\n'),
    teaches:
      'A blameless review is not politeness, it is accuracy. "The user clicked" is not a finding because it is not actionable — people click, and a control set that depends on them never doing so is not a control set. Every row here names something the organisation can change.',
  },
  {
    match: 'compare incident types',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'INCIDENT TYPE          CONTAINMENT PRIORITY        COMMON MISTAKE',
      '---------------------  --------------------------  ------------------------',
      'Phishing               Find other recipients       Delete before extracting',
      '                                                   headers and recipients',
      'Malware                Isolate, then check spread  AV deletes the only sample',
      'Ransomware             Isolate IMMEDIATELY —       "Restored from backup, done"',
      '                       spread rate beats evidence  ignores prior exfiltration',
      'Compromised account    Disable AND revoke tokens   Password reset only',
      'Privilege escalation   Remove privilege first      Fixing access without',
      '                                                   finding how it was gained',
      'Suspicious PowerShell  Capture memory first        Killing the process',
      'Data exfiltration      Stop egress, scope what     "May have been accessed"',
      '                       actually left               instead of what left',
      'Unauthorised access    Establish malice vs error   Treating a provisioning',
      '                       BEFORE acting               error as an attack',
      '',
      'RANSOMWARE IS THE EXCEPTION to capture-before-contain: encryption spreads',
      'faster than you can image a host, so isolation comes first.',
    ].join('\n'),
    teaches:
      'The ransomware exception is worth knowing precisely because it contradicts the general rule. Everywhere else you capture volatile evidence before containing; with ransomware, every second of delay encrypts more, so isolation wins. Knowing when a rule does not apply is more useful than knowing the rule.',
  },
  {
    match: 'show ir report template',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'INCIDENT REPORT STRUCTURE',
      '',
      '1  EXECUTIVE SUMMARY   What happened, impact, status. Five sentences.',
      '                       Written for someone who will read only this.',
      '2  TIMELINE            Events with times and sources. Facts only.',
      '3  SCOPE               Assets, accounts and data confirmed affected —',
      '                       and explicitly, what was ruled OUT.',
      '4  ROOT CAUSE          How they got in, not what they did afterwards.',
      '5  RESPONSE ACTIONS    What was done, by whom, when.',
      '6  EVIDENCE            What was collected, where it is, custody record.',
      '7  LESSONS LEARNED     Control gaps, blameless.',
      '8  RECOMMENDATIONS     Prioritised, with owners and dates.',
      '',
      'SECTION 3 MATTERS MORE THAN IT LOOKS. Stating what you RULED OUT is what',
      'stops an incident expanding indefinitely in the retelling — without it,',
      '"we found it on two hosts" becomes "we do not know how many hosts".',
      '',
      'Recommendations without an owner and a date are not recommendations.',
    ].join('\n'),
    teaches:
      'Section 3 is the one people skip. An incident report that says what was affected but not what was checked and cleared leaves the scope open forever — and the question "how do you know it was only those two hosts?" has no answer. Ruling things out is evidence work, and it belongs in the report.',
  },
];
