import type { PreparedCommand } from './types';

// ---------------------------------------------------------------------------
// Phase 14 prepared outputs — Cloud Security.
//
// Same closed-allowlist contract. All ARNs, account IDs, IPs, and resource
// names are fictional / documentation-range values. No real cloud credentials,
// keys, or tokens appear.
// ---------------------------------------------------------------------------

export const PHASE_14_COMMANDS: PreparedCommand[] = [
  {
    match: 'show cloud environment',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'CLOUD ENVIRONMENT OVERVIEW — Account 111122223333 (Lab-Prod)',
      '',
      'REGION: us-east-1',
      '',
      'VPC',
      '  vpc-0a1b2c3d4e  10.0.0.0/16  "lab-prod-vpc"',
      '    Subnets:',
      '      subnet-pub-1a   10.0.1.0/24   us-east-1a  public   (IGW attached)',
      '      subnet-priv-1a  10.0.10.0/24  us-east-1a  private  (NAT gateway)',
      '      subnet-priv-1b  10.0.11.0/24  us-east-1b  private  (NAT gateway)',
      '',
      'EC2 INSTANCES',
      '  i-0aaa1111  t3.medium  10.0.1.50   web-server-01    running  sg-web',
      '  i-0bbb2222  t3.large   10.0.10.20  app-server-01    running  sg-app',
      '  i-0ccc3333  t3.micro   10.0.1.80   bastion-host     running  sg-bastion',
      '',
      'S3 BUCKETS',
      '  lab-prod-assets         us-east-1  Versioning: ON   Encryption: AES-256',
      '  lab-prod-customer-data  us-east-1  Versioning: OFF  Encryption: NONE     ← FINDING',
      '',
      'RDS INSTANCES',
      '  lab-prod-db  PostgreSQL 15.4  db.t3.medium  Multi-AZ: YES  Encryption: NONE  ← FINDING',
      '',
      'LAMBDA FUNCTIONS',
      '  process-orders    Python 3.12  128 MB  Timeout: 30s',
      '  generate-reports  Node 20      256 MB  Timeout: 60s',
      '',
      'IAM SUMMARY',
      '  Users: 5   Groups: 3   Roles: 3   Policies: 8',
      '',
      'CLOUDTRAIL: Enabled (single-region)',
    ].join('\n'),
    teaches:
      'A cloud environment overview is the equivalent of a network diagram. Before you audit, you need an inventory: what exists, where it lives, and what security controls are (or are not) applied.',
  },
  {
    match: 'show iam policies',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'IAM POLICIES — Account 111122223333',
      '',
      'POLICY                      ATTACHED TO           EFFECT  ACTION   RESOURCE',
      '──────────────────────────  ────────────────────  ──────  ───────  ────────',
      'AdminAccess-Full            user/admin-jsmith     Allow   *        *          ← FINDING: wildcard',
      'EC2-ReadOnly                group/developers      Allow   ec2:Describe*  *',
      'S3-ReadWrite-Assets         role/app-server-role  Allow   s3:Get*, s3:Put*  arn:aws:s3:::lab-prod-assets/*',
      'S3-ReadWrite-CustomerData   role/lambda-orders    Allow   s3:*     arn:aws:s3:::lab-prod-customer-data/*  ← FINDING: s3:*',
      'RDS-FullAccess              role/app-server-role  Allow   rds:*    *          ← FINDING: rds:* on *',
      'Lambda-Invoke               group/developers      Allow   lambda:InvokeFunction  arn:aws:lambda:us-east-1:111122223333:function:*',
      'CloudTrail-ReadOnly         group/security-team   Allow   cloudtrail:LookupEvents  *',
      'SecretsManager-Read         role/lambda-orders    Allow   secretsmanager:GetSecretValue  arn:aws:secretsmanager:us-east-1:111122223333:secret-db-creds-*',
      '',
      'FINDINGS:',
      '  1. AdminAccess-Full grants Action: *, Resource: * — violates least privilege.',
      '     REMEDIATION: Replace with scoped policies per service; require MFA for sensitive actions.',
      '  2. S3-ReadWrite-CustomerData grants s3:* — includes s3:DeleteBucket, s3:PutBucketPolicy.',
      '     REMEDIATION: Restrict to s3:GetObject, s3:PutObject on the specific bucket ARN.',
      '  3. RDS-FullAccess grants rds:* on all resources — the app server can delete any database.',
      '     REMEDIATION: Scope to rds:Connect on the specific DB instance ARN.',
    ].join('\n'),
    teaches:
      'IAM policy review is the highest-value audit activity in any cloud account. A single Action: *, Resource: * policy turns any compromised credential into full account compromise.',
  },
  {
    match: 'show security groups',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'SECURITY GROUPS — vpc-0a1b2c3d4e',
      '',
      'SG NAME      SG ID         DIRECTION  PROTOCOL  PORT   SOURCE/DEST     NOTE',
      '───────────  ────────────  ─────────  ────────  ─────  ──────────────  ──────',
      'sg-web       sg-0aaa1111   Inbound    TCP       443    0.0.0.0/0       OK (HTTPS)',
      'sg-web       sg-0aaa1111   Inbound    TCP       80     0.0.0.0/0       OK (HTTP → redirect)',
      'sg-web       sg-0aaa1111   Outbound   All       All    0.0.0.0/0       Default allow-all',
      '',
      'sg-app       sg-0bbb2222   Inbound    TCP       8080   sg-web          OK (from web tier)',
      'sg-app       sg-0bbb2222   Inbound    TCP       22     0.0.0.0/0       ← FINDING: SSH open to world',
      'sg-app       sg-0bbb2222   Outbound   All       All    0.0.0.0/0       Default allow-all',
      '',
      'sg-bastion   sg-0ccc3333   Inbound    TCP       22     0.0.0.0/0       ← FINDING: SSH open to world',
      'sg-bastion   sg-0ccc3333   Inbound    TCP       3389   0.0.0.0/0       ← FINDING: RDP open to world',
      'sg-bastion   sg-0ccc3333   Outbound   All       All    0.0.0.0/0       Default allow-all',
      '',
      'FINDINGS:',
      '  1. sg-app allows SSH (22) from 0.0.0.0/0 — the app server should only accept SSH from the bastion.',
      '     REMEDIATION: Change source to sg-bastion (sg-0ccc3333).',
      '  2. sg-bastion allows SSH (22) and RDP (3389) from 0.0.0.0/0 — brute-force target.',
      '     REMEDIATION: Restrict source to the corporate office CIDR (e.g., 198.51.100.0/24).',
      '     BETTER: Replace bastion with AWS Systems Manager Session Manager (no open ports).',
    ].join('\n'),
    teaches:
      'Security groups default to deny-all inbound. Every inbound rule you add is a deliberate decision to open an attack surface. The question is not "does this port need to be open?" but "does this port need to be open to the entire internet?"',
  },
  {
    match: 'show storage config',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'S3 BUCKET CONFIGURATION',
      '',
      'BUCKET: lab-prod-assets',
      '  Block Public Access:  ALL ENABLED  ✓',
      '  ACL:                  Private',
      '  Versioning:           Enabled',
      '  Encryption:           SSE-S3 (AES-256)',
      '  Logging:              Enabled → lab-prod-assets-logs',
      '  Status:               COMPLIANT',
      '',
      'BUCKET: lab-prod-customer-data',
      '  Block Public Access:  DISABLED     ← FINDING',
      '  ACL:                  Everyone → READ  ← FINDING: Public read access',
      '  Versioning:           Disabled',
      '  Encryption:           NONE         ← FINDING: Customer PII stored unencrypted',
      '  Logging:              Disabled     ← FINDING: No access logging',
      '  Status:               NON-COMPLIANT — 4 findings',
      '',
      '  CONTENTS (sample):',
      '    customer-data/2026/customers.csv      142 MB  (contains PII: names, emails, SSNs)',
      '    customer-data/2026/transactions.json   89 MB  (contains payment card data)',
      '',
      'FINDINGS:',
      '  1. Block Public Access disabled — anyone on the internet can read this bucket.',
      '     REMEDIATION: Enable all four Block Public Access settings.',
      '  2. ACL grants Everyone READ — redundantly ensures public access.',
      '     REMEDIATION: Set ACL to Private.',
      '  3. No encryption at rest — PII and payment data stored in plaintext.',
      '     REMEDIATION: Enable SSE-S3 (AES-256) or SSE-KMS with a CMK.',
      '  4. No access logging — you cannot tell who accessed the data or when.',
      '     REMEDIATION: Enable server access logging to a separate logging bucket.',
    ].join('\n'),
    teaches:
      'An S3 bucket with Block Public Access disabled, a public ACL, no encryption, and no logging is four independent failures. Each has a one-click fix. The question to ask is not "how do we fix this?" but "why does our process allow this to exist?"',
  },
  {
    match: 'show cloud logs',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'CLOUDTRAIL — Recent API Activity (last 24 hours)',
      '',
      'TIMESTAMP              USER/ROLE                 ACTION                        RESOURCE                     SOURCE IP        MFA',
      '─────────────────────  ────────────────────────  ────────────────────────────  ───────────────────────────  ───────────────  ────',
      '2026-09-08T22:15:03Z   root                      ConsoleLogin                  arn:aws:iam::111122223333    203.0.113.45     NO   ← FINDING',
      '2026-09-08T22:16:41Z   root                      iam:CreateUser                user/temp-admin              203.0.113.45     NO   ← FINDING',
      '2026-09-08T22:17:02Z   root                      iam:AttachUserPolicy          AdminAccess-Full → temp-admin 203.0.113.45   NO   ← FINDING',
      '2026-09-08T22:18:30Z   user/temp-admin            iam:CreateAccessKey           user/temp-admin              203.0.113.45     —',
      '2026-09-08T22:20:15Z   user/temp-admin            s3:GetObject                  lab-prod-customer-data/*     198.51.100.99    —',
      '2026-09-08T23:01:00Z   role/app-server-role       rds:DescribeDBInstances       lab-prod-db                  10.0.10.20       —',
      '2026-09-09T01:30:00Z   role/lambda-orders         secretsmanager:GetSecretValue  db-creds-prod               (Lambda)         —',
      '2026-09-09T02:00:00Z   user/dev-analyst           ec2:DescribeInstances         *                            192.0.2.10       —',
      '',
      'FINDINGS:',
      '  1. Root account console login WITHOUT MFA from 203.0.113.45.',
      '     Root should never be used for daily operations; MFA must be enforced.',
      '  2. Root created a new user (temp-admin) and attached AdminAccess-Full.',
      '     This pattern is consistent with credential compromise → persistence.',
      '  3. temp-admin created access keys and read customer data from an external IP.',
      '     Likely data exfiltration. The access key should be immediately deactivated.',
      '',
      'RECOMMENDED ACTIONS:',
      '  a. Deactivate temp-admin access keys and delete the user.',
      '  b. Enable MFA on root and store root credentials in a physical safe.',
      '  c. Set up CloudTrail alerts for root logins and IAM policy changes.',
      '  d. Investigate 203.0.113.45 and 198.51.100.99 for threat intelligence.',
    ].join('\n'),
    teaches:
      'CloudTrail is your forensic evidence in a cloud incident. The sequence here — root login without MFA, user creation, admin policy attachment, access key creation, data access from external IP — is a textbook credential-compromise-to-exfiltration chain.',
  },
  {
    match: 'show encryption status',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'ENCRYPTION AT REST STATUS — Account 111122223333',
      '',
      'SERVICE    RESOURCE                   ENCRYPTED  KEY TYPE       KEY ID',
      '─────────  ─────────────────────────  ─────────  ─────────────  ──────────────',
      'S3         lab-prod-assets            YES        SSE-S3         (AWS managed)',
      'S3         lab-prod-customer-data     NO         —              —              ← FINDING',
      'RDS        lab-prod-db                NO         —              —              ← FINDING',
      'EBS        vol-0aaa (web-server-01)   YES        aws/ebs        (AWS managed)',
      'EBS        vol-0bbb (app-server-01)   YES        aws/ebs        (AWS managed)',
      'EBS        vol-0ccc (bastion-host)    YES        aws/ebs        (AWS managed)',
      'Lambda     process-orders env vars    NO         —              —              ← FINDING',
      'Lambda     generate-reports env vars  YES        aws/lambda     (AWS managed)',
      '',
      'ENCRYPTION IN TRANSIT',
      '  ALB → web-server-01:     TLS 1.2  ✓',
      '  web-server → app-server: HTTP (plaintext)  ← FINDING: internal traffic unencrypted',
      '  app-server → RDS:        TLS 1.2  ✓',
      '',
      'FINDINGS:',
      '  1. lab-prod-customer-data (S3) — customer PII stored without encryption.',
      '  2. lab-prod-db (RDS) — cannot be encrypted after creation; must snapshot, encrypt, restore.',
      '  3. process-orders Lambda environment variables — secrets visible in plaintext in console.',
      '  4. Internal traffic between web and app tiers is unencrypted.',
    ].join('\n'),
    teaches:
      'Encryption at rest and in transit are separate controls solving different threats. At rest protects against physical theft and improper decommissioning. In transit protects against eavesdropping. Both are required for defence in depth.',
  },
  {
    match: 'show container images',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'CONTAINER IMAGE SCAN REPORT',
      '',
      'REGISTRY: 111122223333.dkr.ecr.us-east-1.amazonaws.com',
      '',
      'IMAGE: payments-api:latest',
      '  Base: node:18-alpine',
      '  Pulled: tag (not digest)  ← FINDING: not pinned by SHA-256',
      '  User: root                ← FINDING: running as root',
      '  Size: 245 MB',
      '',
      '  VULNERABILITIES:',
      '    CRITICAL  CVE-2026-31337  libcurl 7.88.0  Remote code execution     Fixed in 8.0.1',
      '    HIGH      CVE-2026-28001  openssl 3.0.8   Buffer overread           Fixed in 3.0.14',
      '    MEDIUM    CVE-2026-15220  busybox 1.35    Directory traversal       Fixed in 1.36.1',
      '    LOW       CVE-2026-09812  zlib 1.2.13     Denial of service         Fixed in 1.3.0',
      '  Total: 1 Critical, 1 High, 1 Medium, 1 Low',
      '',
      'IMAGE: frontend-web:v2.1.0',
      '  Base: nginx:1.25-alpine',
      '  Pulled: sha256:a3b4c5d6...  ✓ (pinned by digest)',
      '  User: nginx (non-root)      ✓',
      '  Size: 42 MB',
      '',
      '  VULNERABILITIES:',
      '    NONE FOUND',
      '',
      'FINDINGS:',
      '  1. payments-api is pulled by tag, not digest — supply-chain risk.',
      '     REMEDIATION: Pin by SHA-256 digest.',
      '  2. payments-api runs as root — container escape gives root on host.',
      '     REMEDIATION: Add USER node to Dockerfile.',
      '  3. payments-api has a critical CVE (RCE in libcurl).',
      '     REMEDIATION: Rebuild with updated base image; block deployment in CI/CD.',
    ].join('\n'),
    teaches:
      'Container image security is supply-chain security. Pin by digest, run as non-root, scan before deployment, and restrict pulls to an approved internal registry. A passing functional test does not mean the image is safe.',
  },
  {
    match: 'show k8s rbac',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'KUBERNETES RBAC CONFIGURATION — Cluster: lab-prod-eks',
      '',
      'CLUSTER ROLES',
      '  cluster-admin             (built-in)  Full access to all resources',
      '  view                      (built-in)  Read-only access to most resources',
      '  system:node               (built-in)  Kubelet permissions',
      '',
      'NAMESPACE: payments',
      '  RoleBinding: payments-admin',
      '    Subject:   ServiceAccount/payments-sa',
      '    Role:      ClusterRole/cluster-admin    ← FINDING: over-permissive',
      '',
      '  Correct binding should be:',
      '    Role:      Role/payments-rw (get, list, watch, create, update pods, services, deployments)',
      '    Scope:     namespace: payments only',
      '',
      'NAMESPACE: frontend',
      '  RoleBinding: frontend-deployer',
      '    Subject:   ServiceAccount/frontend-sa',
      '    Role:      Role/frontend-deploy (create, update deployments, services)',
      '    Status:    COMPLIANT ✓',
      '',
      'NAMESPACE: monitoring',
      '  RoleBinding: monitoring-reader',
      '    Subject:   ServiceAccount/prometheus-sa',
      '    Role:      ClusterRole/view',
      '    Status:    COMPLIANT ✓  (read-only is appropriate for monitoring)',
      '',
      'FINDINGS:',
      '  1. payments-sa bound to cluster-admin — a compromised pod in payments',
      '     can read secrets in all namespaces, delete any deployment, and',
      '     escalate to full cluster compromise.',
      '     REMEDIATION: Create a namespace-scoped Role with minimal permissions.',
    ].join('\n'),
    teaches:
      'Kubernetes RBAC follows the same principle as cloud IAM: least privilege per scope. cluster-admin is the equivalent of Action: *, Resource: *. The blast radius of a compromised pod is defined by its service account\'s RBAC binding.',
  },
  {
    match: 'show serverless config',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'SERVERLESS FUNCTION CONFIGURATION',
      '',
      'FUNCTION: process-orders',
      '  Runtime:     Python 3.12',
      '  Memory:      128 MB',
      '  Timeout:     30 seconds',
      '  VPC:         Not attached (public internet access)',
      '',
      '  EXECUTION ROLE: arn:aws:iam::111122223333:role/lambda-orders-role',
      '    Policies:',
      '      S3-ReadWrite-CustomerData  (s3:* on lab-prod-customer-data/*)  ← FINDING',
      '      SecretsManager-Read        (GetSecretValue on db-creds-*)     ✓',
      '',
      '  ENVIRONMENT VARIABLES:',
      '    DB_HOST     = lab-prod-db.abc123.us-east-1.rds.amazonaws.com',
      '    DB_NAME     = orders',
      '    DB_USER     = orders_svc',
      '    DB_PASSWORD → P@ssw0rd2026!Lab   ← FINDING: hardcoded secret',
      '    S3_BUCKET   = lab-prod-customer-data',
      '',
      'FUNCTION: generate-reports',
      '  Runtime:     Node.js 20',
      '  Memory:      256 MB',
      '  Timeout:     60 seconds',
      '  VPC:         Attached (subnet-priv-1a, subnet-priv-1b)',
      '',
      '  EXECUTION ROLE: arn:aws:iam::111122223333:role/lambda-reports-role',
      '    Policies:',
      '      S3-ReadOnly-Assets  (s3:GetObject on lab-prod-assets/*)  ✓',
      '',
      '  ENVIRONMENT VARIABLES:',
      '    REPORT_BUCKET = lab-prod-assets',
      '    DB_SECRET_ARN = arn:aws:secretsmanager:us-east-1:111122223333:secret-db-creds-reports  ✓',
      '',
      'FINDINGS:',
      '  1. process-orders has DB_PASSWORD in plaintext environment variables.',
      '     Anyone with lambda:GetFunctionConfiguration can read it.',
      '     REMEDIATION: Use Secrets Manager ARN; the function already has SecretsManager-Read.',
      '  2. process-orders role has s3:* — includes s3:DeleteBucket.',
      '     REMEDIATION: Scope to s3:GetObject, s3:PutObject.',
    ].join('\n'),
    teaches:
      'Serverless does not mean secure by default. The function inherits the permissions of its execution role. A hardcoded password in an environment variable is visible to anyone who can describe the function — which may include every developer in the account.',
  },
  {
    match: 'show api gateway',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'API GATEWAY CONFIGURATION — lab-prod-api',
      '',
      'ENDPOINT                  METHOD  AUTH          RATE LIMIT    BACKEND',
      '────────────────────────  ──────  ────────────  ────────────  ──────────────────',
      '/api/v1/orders            GET     Cognito JWT   100 req/min   Lambda: process-orders',
      '/api/v1/orders            POST    Cognito JWT   50 req/min    Lambda: process-orders',
      '/api/v1/orders/{id}       GET     Cognito JWT   100 req/min   Lambda: process-orders',
      '/api/v1/reports           GET     Cognito JWT   20 req/min    Lambda: generate-reports',
      '/api/v1/health            GET     NONE          1000 req/min  Static 200 OK',
      '/api/internal/admin       GET     NONE          NONE          Lambda: process-orders   ← FINDING',
      '/api/internal/admin       POST    NONE          NONE          Lambda: process-orders   ← FINDING',
      '',
      'WAF: Not attached   ← FINDING',
      '',
      'FINDINGS:',
      '  1. /api/internal/admin has NO authentication — anyone can invoke admin functions.',
      '     REMEDIATION: Add IAM auth or Cognito JWT; restrict to internal VPC endpoint.',
      '  2. /api/internal/admin has NO rate limiting — vulnerable to abuse and enumeration.',
      '     REMEDIATION: Add a usage plan with a throttle (e.g., 10 req/min).',
      '  3. No WAF attached — no protection against injection, XSS, or bot traffic.',
      '     REMEDIATION: Attach AWS WAF with managed rule groups (SQL injection, XSS, bot control).',
    ].join('\n'),
    teaches:
      'An API gateway is only as good as its configuration. An unauthenticated admin endpoint is the API equivalent of leaving SSH open to the internet. Authentication, rate limiting, and a WAF are the minimum baseline.',
  },
  {
    match: 'show secrets vault',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'SECRETS MANAGER — Account 111122223333',
      '',
      'SECRET NAME            TYPE       ROTATION   LAST ROTATED         AGE     STATUS',
      '─────────────────────  ─────────  ─────────  ───────────────────  ──────  ─────────',
      'db-creds-prod          RDS creds  Disabled   2026-01-15           237 d   ← FINDING',
      'db-creds-reports       RDS creds  30 days    2026-09-01           8 d     COMPLIANT ✓',
      'paymentgw-token        API token  Disabled   2025-12-01           282 d   ← FINDING',
      'tls-cert-wildcard      TLS cert   (ACM)      2026-08-15           25 d    COMPLIANT ✓',
      '',
      'FINDINGS:',
      '  1. db-creds-prod — rotation disabled, last rotated 237 days ago.',
      '     If compromised, the attacker has had valid credentials for 8 months.',
      '     REMEDIATION: Enable automatic rotation (30 or 60 day schedule).',
      '  2. paymentgw-token — rotation disabled, last rotated 282 days ago.',
      '     A stale API token to a payment gateway is a compliance and fraud risk.',
      '     REMEDIATION: Rotate immediately and enable automatic rotation.',
      '',
      'POLICY CHECK:',
      '  Organisation policy requires rotation every 90 days.',
      '  2 of 4 secrets are NON-COMPLIANT.',
    ].join('\n'),
    teaches:
      'A secrets vault solves storage and access control. Rotation solves the window of compromise. A secret that has not rotated in 282 days means an attacker who stole it 9 months ago still has a valid credential today. Rotation is not optional — it is the difference between "compromised" and "compromised and still useful."',
  },
];
