import type { PreparedCommand } from './types';
import {
  SAMPLE_BASE64,
  SAMPLE_PLAINTEXT,
  SAMPLE_SHA256,
  SAMPLE_TAMPERED,
  TAMPERED_SHA256,
} from '../data/cryptoOperations';

// ---------------------------------------------------------------------------
// Phase 6 prepared outputs — Cryptography & PKI.
//
// SAFETY: no private keys, no session keys, no real certificates. Public
// digests and encodings ARE real and verifiable — a learner can reproduce
// every digest below with any hashing tool, which is the point. Inventing
// them would teach the shape while quietly undermining the lesson.
// ---------------------------------------------------------------------------

export const PHASE_6_COMMANDS: PreparedCommand[] = [
  {
    match: 'compare crypto operations',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'OPERATION   REVERSIBLE?      KEY?  PROVIDES                      DOES NOT PROVIDE',
      '----------  ---------------  ----  ----------------------------  -------------------',
      'Encoding    Yes, trivially   No    Safe transport of data        ANY security property',
      'Hashing     No, by design    No    Integrity checking            Confidentiality',
      'Encryption  Yes, with key    Yes   Confidentiality               Integrity (alone)',
      'Signing     No, by design    Yes   Integrity, authenticity,      Confidentiality',
      '                              (priv) non-repudiation',
      '',
      'TWO QUESTIONS PLACE ALL FOUR:',
      '  1. Is it reversible?',
      '  2. Does it need a key?',
      '',
      'No key + reversible      = encoding    (secures nothing)',
      'No key + not reversible  = hashing',
      'Key + reversible         = encryption',
      'Private key + not rev.   = signing',
    ].join('\n'),
    teaches:
      'Note that encryption alone does not provide integrity — ciphertext can be altered. That is why authenticated modes such as AES-GCM exist. And "one-way encryption" is not a thing: encryption is defined by being reversible with a key, so an irreversible transformation is a hash.',
  },
  {
    match: 'hash sample',
    tool: 'platform',
    provenance: 'prepared',
    output: [
      `INPUT   ${SAMPLE_PLAINTEXT}`,
      '',
      `SHA-256 ${SAMPLE_SHA256}`,
      'LENGTH  64 hex characters (256 bits) — constant, whatever the input size',
      '',
      'Verify this yourself:',
      `  echo -n "${SAMPLE_PLAINTEXT}" | sha256sum`,
      '',
      'The digest is NOT a shortened copy of the message. You cannot recover any',
      'part of the original from it.',
    ].join('\n'),
    teaches:
      'Constant output length is the tell that distinguishes a digest from ciphertext — ciphertext grows with its input, a digest never does. Hash a single word or a gigabyte and SHA-256 still gives you exactly 64 hex characters.',
  },
  {
    match: 'hash tampered',
    tool: 'platform',
    provenance: 'prepared',
    output: [
      'ONE CHARACTER CHANGED — the avalanche effect',
      '',
      `ORIGINAL  ${SAMPLE_PLAINTEXT}`,
      `          ${SAMPLE_SHA256}`,
      '',
      `TAMPERED  ${SAMPLE_TAMPERED}`,
      `          ${TAMPERED_SHA256}`,
      '',
      'The digests share no meaningful similarity. A one-character change produces',
      'a completely different output — which is exactly what makes a digest useful',
      'for integrity checking.',
    ].join('\n'),
    teaches:
      'A single added zero turned a $500 transfer into $5000, and the digest changed entirely rather than slightly. If digests changed proportionally to the input, an attacker could search for a small edit that kept the digest close — the avalanche effect is what forecloses that.',
  },
  {
    match: 'encode sample',
    tool: 'platform',
    provenance: 'prepared',
    output: [
      `INPUT   ${SAMPLE_PLAINTEXT}`,
      '',
      `BASE64  ${SAMPLE_BASE64}`,
      '',
      'Reverse it:',
      `  echo "${SAMPLE_BASE64}" | base64 -d`,
      '',
      'NO KEY WAS USED. Anyone can reverse this instantly. Compare with the hash:',
      'the hash cannot be reversed at all, and the ciphertext could not be reversed',
      'without the key. This can be reversed by anybody, with nothing.',
      '',
      'Base64 provides NO confidentiality. It is a transport format.',
    ].join('\n'),
    teaches:
      'This is the most consequential confusion in the phase. Base64 looks scrambled, so it gets mistaken for encryption — and "the data was encoded, not encrypted" has genuinely appeared in breach reports where someone believed data at rest was protected.',
  },
  {
    match: 'compare symmetric asymmetric',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      '                 SYMMETRIC                   ASYMMETRIC',
      '---------------  --------------------------  --------------------------',
      'Keys             One shared key              Public + private pair',
      'Speed            Fast (bulk data)            Slow (orders of magnitude)',
      'Typical use      Encrypting the actual data  Agreeing keys, signing',
      'Key problem      How do both ends get it?    Solves that problem',
      'Examples         AES-256-GCM, ChaCha20       RSA, ECDSA, ECDH, Ed25519',
      '',
      'EVERY REAL SYSTEM IS HYBRID:',
      '  Asymmetric  ->  authenticate the parties, agree a shared key',
      '  Symmetric   ->  protect the actual data with that key',
      '',
      'In a TLS session the asymmetric work happens ONCE in the handshake.',
      'Every byte of the page after that is AES.',
    ].join('\n'),
    teaches:
      'The key distribution problem in one sentence: to talk securely you both need the same key, but sharing it needs a secure channel — and if you had one you would not need the encryption. Asymmetric cryptography exists to break that circle.',
  },
  {
    match: 'show key strengths',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'ALGORITHM      KEY SIZE   ROUGH EQUIVALENT   NOTE',
      '-------------  ---------  -----------------  --------------------------------',
      'AES-128        128 bit    —                  Symmetric baseline',
      'AES-256        256 bit    —                  Symmetric, long-term',
      'RSA-2048      2048 bit    ~AES-112           Minimum acceptable today',
      'RSA-3072      3072 bit    ~AES-128           Longer-term RSA',
      'RSA-4096      4096 bit    ~AES-140           Diminishing returns, slower',
      'ECC P-256      256 bit    ~RSA-3072          Far smaller for equal strength',
      'ECC P-384      384 bit    ~RSA-7680          High assurance',
      'Ed25519        256 bit    ~RSA-3072          Modern signature default',
      '',
      'Note the asymmetry: a 256-bit ECC key is comparable to a 3072-bit RSA key.',
      'Smaller keys mean less computation and less bandwidth, which is why ECC',
      'dominates in mobile, IoT and modern TLS.',
    ].join('\n'),
    teaches:
      'Do not compare key sizes across algorithm families — 256 bits of ECC is not weaker than 2048 bits of RSA, it is stronger. The numbers only mean something within one family, because the underlying hard problems differ in difficulty per bit.',
  },
  {
    match: 'explain forward secrecy',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'FORWARD SECRECY — the threat model',
      '',
      'WITHOUT (RSA key transport):',
      '  Day 0     Attacker records encrypted sessions. Cannot read them.',
      '  Day 700   Attacker compromises the server, steals the private key.',
      '  Day 700   Attacker decrypts EVERY recorded session, retroactively.',
      '',
      'WITH (ECDHE ephemeral exchange):',
      '  Day 0     Fresh key pair generated for the session, then discarded.',
      '  Day 700   Attacker steals the long-term private key.',
      '  Day 700   Recorded sessions stay unreadable — the session keys are gone.',
      '',
      'The long-term key authenticates the server. It never encrypts session data.',
      'That separation is the whole mechanism.',
    ].join('\n'),
    teaches:
      'Forward secrecy protects against retroactive decryption, which is a genuinely realistic threat: recording traffic is cheap and patient adversaries exist. Note that a longer RSA key does not help here at all — the property comes from the key being ephemeral, not from it being large.',
  },
  {
    match: 'show certificate srv-01',
    tool: 'platform',
    provenance: 'prepared',
    output: [
      'Certificate:',
      '  Version: 3 (0x2)',
      '  Serial Number: 4a:1f:...:redacted',
      '  Signature Algorithm: ecdsa-with-SHA256',
      '  Issuer:  CN=Lab Issuing CA G2, O=Northwind Lab, C=GB',
      '  Validity',
      '      Not Before: 2025-11-02 09:00:00 UTC',
      '      Not After : 2026-11-02 09:00:00 UTC',
      '  Subject: CN=srv-01.lab.local, O=Northwind Lab, C=GB',
      '  Subject Public Key Info:',
      '      Public Key Algorithm: id-ecPublicKey  (P-256)',
      '      Public Key: [REDACTED — no key material in this platform]',
      '  X509v3 extensions:',
      '      Key Usage: Digital Signature, Key Encipherment',
      '      Extended Key Usage: TLS Web Server Authentication',
      '      Subject Alternative Name: DNS:srv-01.lab.local, DNS:srv-01',
      '      Basic Constraints: CA:FALSE',
      '  Signature: [REDACTED]',
    ].join('\n'),
    teaches:
      'Basic Constraints CA:FALSE means this certificate cannot sign others — it is a leaf. Extended Key Usage restricts it to server authentication, so it could not be repurposed for code signing. Modern clients validate the Subject Alternative Name, not the Common Name, so a certificate without a matching SAN fails even if the CN looks right.',
  },
  {
    match: 'show certificate chain',
    tool: 'platform',
    provenance: 'prepared',
    output: [
      'Chain of trust — srv-01.lab.local',
      '',
      '  [LEAF]          CN=srv-01.lab.local',
      '                  Issued by: Lab Issuing CA G2       CA:FALSE',
      '                       |',
      '                       | signed by',
      '                       v',
      '  [INTERMEDIATE]  CN=Lab Issuing CA G2',
      '                  Issued by: Northwind Lab Root CA   CA:TRUE, pathlen:0',
      '                       |',
      '                       | signed by',
      '                       v',
      '  [ROOT]          CN=Northwind Lab Root CA',
      '                  Self-signed. Private key held OFFLINE.',
      '                  Must be present in the client trust store.',
      '',
      'Validation walks upward until it reaches a certificate the client already',
      'trusts. Trust has to start somewhere — it starts at the pre-installed root.',
    ].join('\n'),
    teaches:
      'Intermediates exist so the root private key can stay offline. If an intermediate is compromised it can be revoked without invalidating every certificate the root ever signed — which for a public CA would mean breaking a substantial fraction of the internet.',
  },
  {
    match: 'show certificate lifecycle',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'CERTIFICATE LIFECYCLE',
      '',
      'STEP  ACTION              NOTE',
      '  1   Generate key pair   Private key never leaves the server',
      '  2   Create CSR          Contains the public key and requested names',
      '  3   CA validates        Proves the requester controls the name',
      '  4   CA issues           Signs the certificate with its private key',
      '  5   Deploy              Install leaf + intermediates on the server',
      '  6   Monitor             Alert well before expiry',
      '  7   Renew               BEFORE expiry — expiry is an outage',
      '  8   Revoke              On compromise, via CRL or OCSP',
      '',
      'Note step 1: the private key is generated on the server and never sent to',
      'the CA. The CA only ever sees the public key.',
      '',
      'Revocation checking is unreliable in practice — some clients soft-fail when',
      'they cannot reach the OCSP responder. This is a major reason short-lived',
      'certificates have become the preferred answer to compromise.',
    ].join('\n'),
    teaches:
      'Expiry is an outage, not a warning — and it is one of the most common causes of unplanned downtime in any estate. Note also that the CA never receives the private key: if a CA ever asks for one, that is a serious red flag.',
  },
  {
    match: 'diagnose certificate errors',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'FOUR DISTINCT CAUSES BEHIND ONE BROWSER WARNING',
      '',
      'ERROR                  VALIDATION CHECK FAILED     TYPICAL FIX',
      '---------------------  --------------------------  -----------------------------',
      'Expired                Current time outside the    Renew. This is a lifecycle',
      '                       validity window             failure, not an attack',
      'Name mismatch          SAN does not include the    Reissue with the correct SAN',
      '                       hostname requested',
      'Untrusted issuer       Chain does not reach a      Distribute the internal root',
      '                       root in the trust store     to client trust stores',
      'Revoked                CA has withdrawn it         Investigate WHY it was revoked',
      '                       (CRL / OCSP)                before reissuing',
      '',
      'Four very different problems. "Certificate error" is a symptom; knowing',
      'which check failed turns it into a diagnosis.',
    ].join('\n'),
    teaches:
      'On an internal application the answer is almost always an untrusted issuer — the internal root was never distributed to clients. The wrong fix is telling users to click through the warning, because that trains them to ignore the one signal that would flag a genuine attack.',
  },
  {
    match: 'trace tls handshake',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'TLS 1.3 handshake — WS-01 -> srv-01.lab.local',
      '',
      '  [1] CLIENT HELLO      Supported versions, cipher suites, key share',
      '                        (client already offers its ECDHE public part)',
      '  [2] SERVER HELLO      Chosen cipher suite, server key share',
      '  [3] CERTIFICATE       Server presents leaf + intermediate',
      '  [4] CERT VERIFY       Server SIGNS the handshake transcript,',
      '                        proving it holds the private key',
      '  [5] CLIENT VALIDATES  Chain to trusted root, validity dates,',
      '                        SAN matches hostname, not revoked',
      '  [6] KEY DERIVATION    Both sides derive identical session keys from',
      '                        the ECDHE exchange. Keys never transmitted.',
      '  [7] FINISHED          Both confirm with a MAC over the transcript',
      '  [8] APPLICATION DATA  AES-256-GCM from here on',
      '',
      'ALL FOUR OPERATIONS APPEAR:',
      '  Hashing     transcript hashes throughout, and in key derivation',
      '  Signing     step 4 (server) and the CA signature validated at step 5',
      '  Encryption  step 8 onward, symmetric',
      '  Encoding    certificates are DER/Base64 — format, not security',
    ].join('\n'),
    teaches:
      'Step 4 is the one learners miss: presenting a certificate proves nothing on its own, because certificates are public. The server must also sign something to prove it holds the matching private key. Note too that validation (step 5) precedes key derivation completing — agreeing a key with an unverified server would defeat the purpose.',
  },
];
