import type { PreparedCommand } from './types';

// ---------------------------------------------------------------------------
// Phase 18 prepared outputs — Business Continuity & Disaster Recovery.
//
// Same closed-allowlist contract, continuing the fictional Meridian Retail
// Co. company introduced in Phase 17. No real credentials, keys, or tokens
// appear.
// ---------------------------------------------------------------------------

export const PHASE_18_COMMANDS: PreparedCommand[] = [
  {
    match: 'show backup schedule',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'BACKUP SCHEDULE — Meridian Retail Co. (fictional)',
      '',
      'SYSTEM                  BACKUP TYPE    FREQUENCY        LAST TESTED RESTORE',
      '───────────────────────  ─────────────  ───────────────  ─────────────────────',
      'Payment processing        Log shipping   Every 5 minutes  2026-08-20 (passed)',
      'Order database             Full nightly   Every 24 hours   Never                ← FINDING',
      'Payroll system              Full weekly    Every 7 days     2025-11-01 (passed)',
      'File shares                 Incremental    Every 24 hours   Never                ← FINDING',
      '',
      'FINDINGS:',
      '  1. Order database is backed up only nightly, but the BIA-derived RPO for order data',
      '     is 15 minutes (see show recovery objectives) — a 24-hour backup cannot meet a',
      '     15-minute RPO.',
      '  2. Order database and file share restores have never been tested — both are',
      '     unverified controls regardless of how reliably the backup job itself completes.',
    ].join('\n'),
    teaches:
      'A backup that runs successfully every night is not the same thing as a backup that meets the business\'s RPO. Frequency must be measured against the requirement, not against whether the job reports success.',
  },
  {
    match: 'show recovery objectives',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'RECOVERY OBJECTIVES (from Phase 17 BIA) — Meridian Retail Co. (fictional)',
      '',
      'PROCESS                  RTO        RPO         SOURCE',
      '────────────────────────  ─────────  ──────────  ────────────────────────',
      'Payment processing         4 hours    5 minutes   BIA: Critical, MTD 4h',
      'Order database              8 hours    15 minutes  BIA: Critical, MTD 24h (buffer applied)',
      'Payroll processing           3 days     24 hours    BIA: High, MTD 3 business days',
      '',
      'NOTE: RTO/RPO values are derived from the Phase 17 Business Impact Analysis MTD',
      'figures, with an operating buffer subtracted for validation and cutover time.',
      'They are business requirements — the DR architecture must be designed to meet them,',
      'not the reverse.',
    ].join('\n'),
    teaches:
      'This is the direct link between Phase 17 and Phase 18: the BIA sets the requirement (MTD), and RTO/RPO translate that requirement into numbers a backup schedule and recovery architecture can be measured against.',
  },
  {
    match: 'show site options',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'ALTERNATE SITE OPTIONS — comparison',
      '',
      'SITE TYPE     TYPICAL RECOVERY TIME  RELATIVE COST  NOTES',
      '────────────  ──────────────────────  ─────────────  ──────────────────────────────',
      'Hot site       Minutes                 Highest        Continuously synchronised, standby ready',
      'Warm site      Hours to 1-2 days       Moderate       Some equipment installed, needs configuration',
      'Cold site      Days to weeks           Lowest         Empty facility, everything procured after declaration',
      'Cloud-based    Minutes to hours        Pay-per-use    No idle standby cost; scales with automation quality',
      '',
      'RECOMMENDATION FOR MERIDIAN:',
      '  Payment processing (RTO 4h) → Cloud-based DR with automated failover, or a warm site.',
      '  Order database (RTO 8h) → Warm site is sufficient and more cost-effective than hot.',
      '  Payroll (RTO 3 days) → Cold site is cost-justified given the multi-day tolerance.',
    ].join('\n'),
    teaches:
      'Notice that no system here is recommended a hot site — even the 4-hour RTO can be met more cheaply with cloud-based DR or a warm site. Reserve hot sites for RTOs measured in minutes, not hours.',
  },
  {
    match: 'show disaster scenario ransomware',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'DISASTER SCENARIO — Ransomware',
      '',
      'TRIGGER: File servers and the order-database backup network share are found encrypted.',
      '',
      'RECOVERY CONSIDERATIONS:',
      '  1. Assume the attacker specifically targeted backup systems — verify whether any',
      '     immutable, offline, or air-gapped backup copy exists before planning restoration.',
      '  2. Do NOT restore from a backup until it has been scanned and confirmed clean —',
      '     restoring an already-infected backup reintroduces the ransomware.',
      '  3. Coordinate with the Phase 12 incident response process for containment and',
      '     eradication before any restoration begins.',
      '  4. Paying the ransom is a business/legal decision with no guarantee of a working',
      '     decryption key — it is never a substitute for a verified clean backup.',
      '',
      'MERIDIAN STATUS: A cloud-based immutable backup of the order database exists, taken',
      '6 hours before the incident. Restoration should proceed from that copy, accepting',
      '6 hours of data loss — within the 15-minute RPO target only if log-shipped transactions',
      'since that snapshot can also be replayed; otherwise this exceeds RPO and must be reported',
      'as an exception.',
    ].join('\n'),
    teaches:
      'The exam-relevant insight here is the RPO exception: even a "successful" ransomware recovery can still miss the stated RPO, and that gap must be reported, not hidden, because it reveals a genuine backup-frequency shortfall for immutable copies specifically.',
  },
  {
    match: 'show disaster scenario server outage',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'DISASTER SCENARIO — Server Outage',
      '',
      'TRIGGER: The primary order-database server suffers a hardware failure (disk array).',
      '',
      'RECOVERY CONSIDERATIONS:',
      '  1. Check for redundancy first — if a passive replica or active-active peer exists,',
      '     failover may resolve the outage in minutes with no data restoration needed.',
      '  2. If no redundancy exists, provision replacement hardware and restore the most',
      '     recent verified backup.',
      '  3. Validate data integrity and application functionality before returning the',
      '     system to production traffic.',
      '',
      'MERIDIAN STATUS: The order database has no active-passive replica configured — this is',
      'a single point of failure. Recovery requires restoring the last full backup (up to 24',
      'hours old) to a standby server, which will take approximately 6 hours and will not meet',
      'the 15-minute RPO or the 8-hour RTO reliably.',
    ].join('\n'),
    teaches:
      'This scenario surfaces a second, independent finding: the same order database that has an RPO gap in its backup schedule also has no redundancy at all, meaning any hardware failure — not just ransomware — will breach its stated recovery objectives.',
  },
  {
    match: 'show disaster scenario network outage',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'DISASTER SCENARIO — Network Outage',
      '',
      'TRIGGER: The primary ISP circuit to the data centre fails; all servers remain fully',
      'operational but unreachable from the internet.',
      '',
      'RECOVERY CONSIDERATIONS:',
      '  1. Distinguish this from a server outage immediately — the servers are healthy;',
      '     the path to reach them is what failed. Server redundancy does not help here.',
      '  2. The fix is path diversity: a secondary ISP circuit, a diverse physical route,',
      '     or a backup connectivity method (e.g., LTE/5G failover for critical management access).',
      '  3. Internal users on the local network may still be able to reach systems even',
      '     while external/customer access is down — scope communication accordingly.',
      '',
      'MERIDIAN STATUS: Only one ISP circuit exists into the primary data centre — a single',
      'point of failure with no diverse path. RECOMMENDATION: contract a second ISP over a',
      'physically diverse route, or add a cloud-based failover origin for customer-facing traffic.',
    ].join('\n'),
    teaches:
      'A network outage and a server outage can look identical to a customer ("the site is down"), but the recovery action is completely different. Applying a server-outage runbook (restore from backup) to a network outage would accomplish nothing.',
  },
  {
    match: 'show disaster scenario cloud outage',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'DISASTER SCENARIO — Cloud Provider Outage',
      '',
      'TRIGGER: The public cloud provider hosting the payment-processing workload suffers a',
      'region-wide outage.',
      '',
      'RECOVERY CONSIDERATIONS:',
      '  1. The organisation cannot directly repair the provider\'s infrastructure — recovery',
      '     time depends entirely on the provider\'s own incident response and published SLA.',
      '  2. Mitigation must be architected in advance: multi-region deployment (so a single',
      '     region\'s outage does not take down the whole service) or a multi-cloud/hybrid',
      '     contingency for the most critical workloads.',
      '  3. During the outage itself, the only realistic actions are invoking any pre-built',
      '     failover to a secondary region/provider and communicating status to stakeholders —',
      '     there is no "fix the server" option available.',
      '',
      'MERIDIAN STATUS: Payment processing runs in a single cloud region with no secondary',
      'region configured. RECOMMENDATION: deploy a warm standby in a second region with',
      'automated DNS failover, sized to meet the 4-hour RTO.',
    ].join('\n'),
    teaches:
      'This is the scenario that most clearly separates planning from improvisation: multi-region architecture has to exist before the outage happens. There is no recovery action available during a cloud provider outage that was not already built in advance.',
  },
  {
    match: 'show bcdr test log',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'BC/DR TEST LOG — Meridian Retail Co. (fictional)',
      '',
      'SCENARIO                TABLETOP    SIMULATION   FULL-INTERRUPTION   LAST TEST DATE',
      '───────────────────────  ──────────  ───────────  ──────────────────  ─────────────────',
      'Ransomware                Completed   Completed    Not yet performed   2026-05-14 (sim)',
      'Server outage             Completed   Not yet       Not yet performed   2025-09-02 (tabletop)',
      'Network outage             Not yet performed         —                  —              ← FINDING',
      'Cloud outage               Completed   Not yet       Not yet performed   2026-02-20 (tabletop)',
      '',
      'FINDINGS:',
      '  1. The network outage scenario has never been tested at any level — not even a',
      '     tabletop exercise — despite the single-ISP finding identified in show disaster',
      '     scenario network outage.',
      '',
      'RECOMMENDATION: Schedule a tabletop exercise for the network outage scenario as the',
      'next test, following the same progression already used for the other three scenarios.',
    ].join('\n'),
    teaches:
      'The test log and the scenario findings should always be read together: the single-ISP gap and the complete absence of any test for that exact scenario are the same underlying priority gap seen from two different angles.',
  },
];
