import type { PreparedCommand } from './types';

// ---------------------------------------------------------------------------
// Phase 27 prepared outputs — Security+ to IAM Career Bridge.
//
// Two kinds of entry: reference material explaining how a Security+ concept is
// actually implemented, and prepared identity log excerpts an IAM analyst would
// read. Same closed-allowlist contract as every other phase — nothing here
// queries a directory, an identity provider, or any live system.
//
// All account names are lab-only, all addresses are RFC 1918 / RFC 5737
// documentation ranges, and no credential, token, key, or tenant identifier
// appears in any output.
// ---------------------------------------------------------------------------

export const PHASE_27_COMMANDS: PreparedCommand[] = [
  {
    match: 'show iam bridge topics',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'SECURITY+ -> IAM CAREER BRIDGE — BRIDGE TOPICS',
      '',
      '1. How is authentication implemented?        [authentication, kerberos, ldap]',
      '2. How is authorization implemented?         [authorization, least-privilege]',
      '3. How does MFA work?                        [mfa, phishing-resistant-mfa]',
      '4. How does SSO work?                        [sso, federation, saml, oidc]',
      '5. How does RBAC work?                       [rbac, least-privilege]',
      '6. How does Zero Trust affect identity?      [zero-trust, conditional-access]',
      '7. How is privileged access managed?         [pam, least-privilege]',
      '8. How do identity events appear in logs?    [windows-logs, siem, accounting]',
      '9. How are IAM incidents investigated?       [ir-lifecycle, containment]',
      '',
      'Every concept ID above is already taught and mastery-tracked by an',
      'earlier phase. The bridge adds implementation detail, not new concepts.',
    ].join('\n'),
    teaches:
      'These nine questions are the difference between passing Security+ and being useful on an IAM team: the exam asks what a control is, the job asks how it is built, what it logs, and what you do when it fails.',
  },
  {
    match: 'explain concept before vendor',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'CONCEPT BEFORE VENDOR — WHY THE ORDER IS FIXED',
      '',
      'Vendor features are interchangeable; the concepts are not. Conditional',
      'Access, Okta adaptive authentication, and Ping policy orchestration are',
      'three products implementing one idea: evaluate signals at access time',
      'and decide allow / step up / block.',
      '',
      'Learn the idea and all three become configuration. Learn the console',
      'first and you can operate one product without being able to explain,',
      'defend, or troubleshoot the decision it made.',
      '',
      'This platform enforces the order: each vendor stays locked until every',
      'prerequisite concept is above the weak-area threshold (mastery 2).',
    ].join('\n'),
    teaches:
      'Product knowledge expires with the product. The concept behind it is what transfers to the next employer, the next console, and the next interview question.',
  },
  {
    match: 'show iam vendor landscape',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'IAM VENDOR LANDSCAPE — six platforms, four categories',
      '',
      'DIRECTORY / IDENTITY PROVIDER',
      '  Active Directory     on-premises directory; Kerberos + LDAP',
      '  Microsoft Entra ID   cloud identity provider; tokens + Conditional Access',
      '  Okta                 vendor-neutral identity provider; SAML/OIDC catalogue',
      '  Ping Identity        federation and authentication orchestration',
      '',
      'PRIVILEGED ACCESS MANAGEMENT',
      '  CyberArk             credential vaulting, session brokering, recording',
      '',
      'IDENTITY GOVERNANCE AND ADMINISTRATION',
      '  SailPoint            role modelling, access certification, JML automation',
      '',
      'Prerequisite concepts per platform:',
      '  Active Directory  -> ldap, kerberos, active-directory, authentication',
      '  Entra ID          -> identity-provider, sso, federation, conditional-access',
      '  Okta              -> identity-provider, sso, saml, oidc',
      '  Ping Identity     -> federation, saml, oauth',
      '  CyberArk          -> pam, least-privilege, privilege-escalation',
      '  SailPoint         -> rbac, authorization, least-privilege, account-lifecycle',
    ].join('\n'),
    teaches:
      'Notice the categories, not the names. An IAM job description listing "Okta or Ping" is asking for federation; one listing "CyberArk or Delinea" is asking for privileged access. The category tells you which concepts to study.',
  },
  {
    match: 'explain identity event ids',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'IDENTITY EVENT IDS AN IAM ANALYST READS',
      '',
      'AUTHENTICATION',
      '  4624  successful logon      (read the Logon Type: 2 interactive, 3 network, 10 RDP)',
      '  4625  failed logon          (status code separates bad password from disabled/locked)',
      '  4768  Kerberos TGT requested',
      '  4769  Kerberos service ticket requested',
      '  4771  Kerberos pre-authentication failed',
      '',
      'ACCOUNT AND GROUP MANAGEMENT',
      '  4720  account created',
      '  4726  account deleted',
      '  4738  account changed',
      '  4740  account locked out',
      '  4767  account unlocked',
      '  4728  member added to a global security-enabled group',
      '  4732  member added to a local security-enabled group',
      '  4756  member added to a universal security-enabled group',
      '',
      'PRIVILEGE',
      '  4672  special privileges assigned to new logon (an administrative logon)',
      '',
      'The identity provider side has equivalents under different names:',
      'sign-in logs, audit logs, risk detections, consent grants.',
    ].join('\n'),
    teaches:
      'These are configured, not automatic — advanced audit policy has to be enabled before the incident. An event that was never logged cannot be investigated afterwards, which is why accounting is a control and not a by-product.',
  },
  {
    match: 'show identity timeline',
    tool: 'platform',
    provenance: 'prepared',
    output: [
      'PREPARED SAMPLE EVIDENCE — per-account identity timeline',
      'Account: lab\\j.okafor    Window: 2024-06-11 21:40 - 22:19 UTC',
      '',
      'TIME      SOURCE            EVENT',
      '21:41     idp sign-in       Failed sign-in x14, source 198.51.100.77 (unfamiliar ASN)',
      '21:44     idp sign-in       Failed sign-in x9, source 198.51.100.77',
      '21:52     idp sign-in       SUCCESS, source 198.51.100.77, MFA satisfied: SMS code',
      '21:53     idp risk          Risk detection raised: unfamiliar sign-in properties',
      '21:56     idp audit         MFA method registered: authenticator app (new device)',
      '22:03     idp audit         OAuth consent granted to third-party mail client, offline_access',
      '22:07     dc security       4728 member added to group "Helpdesk Operators" (lab\\j.okafor)',
      '22:11     endpoint          4624 Logon Type 3 to SRV-FILE-02 (192.168.20.24)',
      '22:14     endpoint          4672 special privileges assigned to new logon',
      '22:18     dc security       4738 account changed: alternate contact address set',
      '',
      'Three sources, one account, one order of events.',
    ].join('\n'),
    teaches:
      'Read the shape, not the individual lines: spray, then a success on a weak second factor, then persistence (new MFA method, consent grant), then privilege (group add), then use (network logon, admin privileges). Any one line alone is noise.',
  },
  {
    match: 'show iam containment checklist',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'IDENTITY CONTAINMENT CHECKLIST',
      '',
      '  [ ] 1. Reset the credential',
      '  [ ] 2. Revoke sessions AND refresh tokens',
      '  [ ] 3. Remove attacker-registered MFA methods',
      '  [ ] 4. Review and revoke OAuth consent grants',
      '  [ ] 5. Reverse group / role / delegation changes made in the window',
      '  [ ] 6. Re-check the account against peers for residual entitlements',
      '',
      'Step 1 alone is the classic incomplete containment. A refresh token',
      'issued before the reset keeps working; an attacker-registered',
      'authenticator satisfies MFA on the new password; a consent grant with',
      'offline_access needs no password at all.',
      '',
      'TEST: after each step, ask "what could the attacker still do?"',
      'While that answer is non-empty, containment is not finished.',
    ].join('\n'),
    teaches:
      'This is the single most valuable thing to carry into an IAM interview. A host-focused analyst says "reset the password"; an identity analyst names the token, the registered method, and the consent grant — and that difference is audible in about ten seconds.',
  },
  {
    match: 'explain zero trust identity',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'ZERO TRUST AND IDENTITY',
      '',
      'Remove implicit network trust and the identity provider becomes the',
      'policy enforcement point. Zero Trust is therefore an identity project',
      'in practice, whatever the network diagram says.',
      '',
      'Implemented as policy evaluated on every authentication:',
      '  SIGNALS   user risk, sign-in risk, device compliance, location,',
      '            application sensitivity, client app',
      '  DECISION  allow / step up to a stronger factor / block',
      '  SCOPE     per resource, re-evaluated continuously — not once at login',
      '',
      'THE FINDING IS USUALLY THE EXCLUSION. Break-glass accounts, legacy',
      'service accounts, and "temporary" carve-outs are paths where the',
      'controls do not run, which is exactly why attackers land there.',
    ].join('\n'),
    teaches:
      'When you review a suspicious sign-in, read the policy evaluation result before the user. A success that landed in an exclusion is a policy finding — the control did not fail, it was never applied.',
  },
  {
    match: 'explain privileged access management',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'PRIVILEGED ACCESS MANAGEMENT — FOUR STACKED CONTROLS',
      '',
      '  VAULTING     remove the standing shared password; rotate it',
      '  BROKERING    admin connects through a proxy holding the credential,',
      '               so the human never learns it',
      '  JUST-IN-TIME grant the privileged role for a bounded window, with an',
      '               approval and a stated reason — no standing admin',
      '  RECORDING    session and keystroke capture makes it reviewable',
      '',
      'All four shrink the same two quantities: how long privilege exists,',
      'and how many places a privileged credential can be stolen from.',
      '',
      'AUDIT TEST: reconcile every privileged action against an activation or',
      'checkout record. Privileged activity with no matching record means an',
      'unmanaged standing account or a credential used outside the broker.',
    ].join('\n'),
    teaches:
      'A vault nobody routes through provides no protection at all. The reconciliation test — privileged action against activation record — is what proves the control is actually in the path rather than merely purchased.',
  },
  {
    match: 'show iam career ladder',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'SECURITY+ -> IAM CAREER LADDER',
      '',
      'ENTRY            IAM Analyst / Identity Support',
      '                 account lifecycle tickets, access requests, MFA resets,',
      '                 first-line sign-in troubleshooting',
      '                 concepts: authentication, mfa, account-lifecycle',
      '',
      'JUNIOR-MID       Junior IAM Engineer',
      '                 application SSO onboarding, conditional access changes,',
      '                 role and group modelling, provisioning automation',
      '                 concepts: sso, federation, saml, oidc, rbac, conditional-access',
      '',
      'SPECIALIST       IAM Engineer / PAM Engineer / IGA Engineer',
      '                 privileged access architecture, governance campaigns,',
      '                 identity incident response, hybrid identity design',
      '                 concepts: pam, authorization, zero-trust, ir-lifecycle',
      '',
      'Security+ is the concept foundation for all three rows. The bridge is',
      'the implementation detail, the log evidence, and the investigation',
      'habits the rows above entry actually assess for.',
    ].join('\n'),
    teaches:
      'IAM is one of the few security specialisms with a genuine entry-level door, because account lifecycle and access-request work is real, needed, and learnable — and it sits directly beside the engineers doing the federation and PAM work you want next.',
  },
];
