import type { PreparedCommand } from './types';

// ---------------------------------------------------------------------------
// Phase 13 prepared outputs — Threat Intelligence.
//
// Same closed-allowlist contract. MITRE ATT&CK identifiers below are public
// reference data verified against attack.mitre.org; nothing here describes how
// to carry out any of the techniques it names.
// ---------------------------------------------------------------------------

export const PHASE_13_COMMANDS: PreparedCommand[] = [
  {
    match: 'explain intelligence lifecycle',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'THE INTELLIGENCE LIFECYCLE',
      '',
      '  1 PLANNING AND DIRECTION   What do we need to know, and who acts on it?',
      '  2 COLLECTION              Where does the data come from?',
      '  3 PROCESSING              Parsed, normalised, deduplicated',
      '  4 ANALYSIS AND PRODUCTION What does it mean for us, and how sure are we?',
      '  5 DISSEMINATION           To the person who can act, in a usable form',
      '  6 FEEDBACK                Did it help? What do we ask for next time?',
      '',
      'IT IS A LOOP, AND FEEDBACK IS THE PHASE EVERYONE SKIPS.',
      'Skipping it is why organisations renew feeds nobody has ever acted on.',
      '',
      'THE MOST COMMON FAILURE IS AT PHASE 1. Teams buy feeds before anyone has',
      'stated a requirement, then measure success by volume of indicators. Volume',
      'is not intelligence. A requirement makes the other five phases decidable.',
    ].join('\n'),
    teaches:
      'Direction comes first for the same reason preparation came first in Phase 12: it is the phase that determines whether the rest are useful. "What would we do differently if we knew this?" is the question that separates intelligence from a subscription.',
  },
  {
    match: 'explain ioc vs ioa',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'INDICATOR OF COMPROMISE vs INDICATOR OF ATTACK',
      '',
      'IOC   Evidence something HAS happened.   An artifact you match.',
      'IOA   Evidence something IS happening.   A behaviour you recognise.',
      '',
      'FROM IR-2026-0908-01',
      '',
      'OBSERVATION                                        KIND   WHY',
      '-------------------------------------------------  -----  -------------------',
      '203.0.113.55 as a C2 endpoint                      IOC    A value to match',
      'The lookalike domain                               IOC    A registered artifact',
      'SHA-256 of the SUID binary                         IOC    Changes on recompile',
      'Scheduled task with an encoded command             IOC    A host artifact',
      'PowerShell from explorer.exe holding outbound TLS  IOA    A relationship',
      'Fixed-interval beaconing                           IOA    A timing property',
      'Failures then success from a new ASN               IOA    A sequence',
      'New SUID root binary outside a change window       IOA    A rule, not a name',
      '',
      'IOCs CONFIRM. IOAs CATCH THE NEXT ONE.',
      'An estate that only has IOCs is always fighting the previous incident.',
    ].join('\n'),
    teaches:
      'The test is whether you could write it down as a value. If you can — a hash, an address, a filename — it is an IOC. If it only exists as a relationship, a sequence or a timing, it is an IOA. Note that the EDR detection that finally caught this incident at 03:02:10 was an IOA; every IOC in the list was discovered afterwards.',
  },
  {
    match: 'show pyramid of pain',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'THE PYRAMID OF PAIN  (David Bianco, 2013) — apex first',
      '',
      '  TTPs                     Tough        Change how they operate',
      '  Tools                    Challenging  Find, buy or write a replacement',
      '  Network/host artifacts   Annoying     Rework the tooling',
      '  Domain names             Simple       Register another domain',
      '  IP addresses             Easy         Rent another host',
      '  Hash values              Trivial      Change one byte',
      '',
      'THE PYRAMID IS ABOUT COST, NOT DIFFICULTY OF DETECTION.',
      'Hashes are the EASIEST thing to detect and the LEAST valuable to detect,',
      'because evading your detection costs the attacker a recompile.',
      '',
      'APPLIED TO THIS INCIDENT',
      '  Block 203.0.113.55        attacker rents a new host           minutes',
      '  Block the domain          attacker registers another          hours',
      '  Alert on the SHA-256      attacker recompiles                 seconds',
      '  Alert on PowerShell spawned by explorer with outbound TLS',
      '                            attacker must change tradecraft     weeks',
      '',
      'ONLY THE LAST ONE IS STILL WORKING NEXT MONTH.',
    ].join('\n'),
    teaches:
      'Most organisations invest almost entirely at the bottom of the pyramid because that is what feeds sell and what controls ingest. The pyramid does not say those indicators are worthless — it says know what you are buying. A blocklist buys you today; a behavioural rule buys you the technique.',
  },
  {
    match: 'show attack mapping',
    tool: 'platform',
    provenance: 'prepared',
    output: [
      'IR-2026-0908-01 MAPPED TO MITRE ATT&CK',
      '',
      'TECHNIQUE   NAME                                  TACTIC',
      '----------  ------------------------------------  --------------------',
      'T1566.002   Spearphishing Link                    Initial Access',
      'T1078       Valid Accounts                        Initial Access +3',
      'T1059.001   PowerShell                            Execution',
      'T1071.001   Web Protocols                         Command and Control',
      'T1053.005   Scheduled Task                        Persistence +2',
      'T1098       Account Manipulation                  Persistence +1',
      'T1548.003   Sudo and Sudo Caching                 Privilege Escalation',
      'T1548.001   Setuid and Setgid                     Privilege Escalation',
      'T1543.002   Systemd Service                       Persistence +1',
      '',
      'WHAT THE MAP SHOWS THAT THE TIMELINE DID NOT',
      '  Persistence appears FOUR times across two operating systems. Any',
      '  eradication that removes one of them leaves the intrusion intact.',
      '',
      '  T1078 Valid Accounts spans four tactics on its own. That is why nothing',
      '  in this incident looked like malware: the account was real throughout.',
      '',
      'ATT&CK IS A SHARED VOCABULARY, NOT A SCORE. Its value is that two teams',
      'describing the same behaviour use the same identifier.',
    ].join('\n'),
    teaches:
      'The most useful thing a mapping produces is the gaps. Lay your detections over this list and the empty rows are your coverage report — here, Execution was invisible because script block logging was off, so the only stage with a detection was Command and Control, which is stage five of six.',
  },
  {
    match: 'compare threat actors',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'THREAT ACTOR TYPES',
      '',
      'TYPE                SOPHIST.   RESOURCES     MOTIVATION',
      '------------------  ---------  ------------  ---------------------------',
      'Nation-state / APT  very high  state-level   Espionage, disruption, war',
      'Organised crime     high       substantial   Financial gain, blackmail',
      'Hacktivist          moderate   moderate      Political belief, chaos',
      'Insider threat      moderate   moderate      Revenge, financial gain',
      'Unskilled attacker  low        minimal       Chaos, curiosity, revenge',
      'Shadow IT           low        moderate      Getting the job done',
      '',
      'WHAT ACTUALLY CHANGES YOUR DECISIONS',
      '  Nation-state    patient. Dwell time measured in months. Detect on',
      '                  behaviour, because the infrastructure will be clean.',
      '  Organised crime fast and loud at the end. Backups and segmentation',
      '                  matter more than elegant detection.',
      '  Insider         no intrusion to find. The access is authorised;',
      '                  only the purpose is not.',
      '  Shadow IT       not an attacker at all. The risk is the absence of',
      '                  patching, logging and backup.',
      '',
      'ATTRIBUTION TO A NAMED GROUP IS THE LEAST ACTIONABLE OUTPUT.',
      'The actor TYPE changes your strategy. The group NAME changes a headline.',
    ].join('\n'),
    teaches:
      'Shadow IT sits in this list because the exam puts it there, and the placement is instructive: the person who stood up an unmanaged server to hit a deadline is not an adversary, but the server is still unpatched, unlogged and unbacked-up. Threat modelling that only considers malice misses it entirely.',
  },
  {
    match: 'explain stix taxii',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'STIX AND TAXII',
      '',
      'STIX   Structured Threat Information Expression — the LANGUAGE.',
      'TAXII  Trusted Automated Exchange of Intelligence Information — the',
      '       TRANSPORT that moves STIX between parties.',
      '',
      'The exam tests this distinction directly. STIX is what you write;',
      'TAXII is how it travels.',
      '',
      'STIX OBJECT TYPES YOU WILL MEET',
      '  indicator       a detection pattern and its validity window',
      '  malware         a family or instance, with capabilities',
      '  attack-pattern  a technique — this is where ATT&CK IDs live',
      '  threat-actor    who, with motivation and sophistication',
      '  identity        an organisation or sector',
      '  observed-data   raw observations, no claim of maliciousness',
      '  relationship    the edges: indicator "indicates" malware',
      '',
      'THE RELATIONSHIPS ARE THE POINT. A list of indicators is a blocklist.',
      'A graph of indicators, techniques and actors is intelligence.',
      '',
      'TAXII moves these as COLLECTIONS (request/response) or CHANNELS',
      '(publish/subscribe) over HTTPS.',
    ].join('\n'),
    teaches:
      'Note that observed-data and indicator are separate object types on purpose. An observation is a fact — this address was contacted. An indicator is a claim — contacting this address is bad. Collapsing them is how a legitimate CDN address ends up on a blocklist.',
  },
  {
    match: 'explain admiralty code',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'THE ADMIRALTY CODE — two independent judgements',
      '',
      'SOURCE RELIABILITY            INFORMATION CREDIBILITY',
      '  A  Completely reliable        1  Confirmed by other sources',
      '  B  Usually reliable           2  Probably true',
      '  C  Fairly reliable            3  Possibly true',
      '  D  Not usually reliable       4  Doubtful',
      '  E  Unreliable                 5  Improbable',
      '  F  Cannot be judged           6  Cannot be judged',
      '',
      'A rating is one of each: B2, A1, E5.',
      '',
      'WHY TWO AXES AND NOT ONE',
      '  A usually-reliable source can still report something doubtful (B4).',
      '  An unreliable source occasionally tells the truth (E1).',
      '  Collapsing them into a single "confidence" number destroys the',
      '  distinction between "who said it" and "is it true".',
      '',
      'RELEVANCE IS A THIRD, SEPARATE QUESTION.',
      'An A1 report about a product you do not run is still not actionable.',
      'Check relevance FIRST — it is the cheapest filter you have.',
    ].join('\n'),
    teaches:
      'This is the same two-axis discipline as Phase 12 containment, applied to sourcing: two independent properties that a single score would blur. Note the F and 6 grades exist precisely so an analyst can record "I do not know" rather than being forced into a false judgement.',
  },
  {
    match: 'show intel feed report',
    tool: 'platform',
    provenance: 'prepared',
    output: [
      'FEED TRIAGE — week of the incident',
      '',
      'RATING  AGE  RELEVANT  HEADLINE',
      '------  ---  --------  -----------------------------------------------',
      'A1      12d  yes       National advisory: phishing-resistant MFA',
      'A1       0d  yes       Internal EDR: fixed-interval beaconing detected',
      'B2       1d  yes       203.0.113.55 reported as active C2',
      'B3       6d  yes       Campaign using health-check scheduled tasks',
      'C4      20d  yes       Vendor blog attributing to a named group',
      'D4       0d  yes       Bulk list of 40,000 addresses, no context',
      'E5       2d  NO        Forum claim of a 0-day in a product we do not run',
      '',
      'ACT ON            A1, A1, B2',
      'CORROBORATE       B3, C4, D4',
      'DISREGARD         E5  (irrelevant before it is even unreliable)',
      '',
      'THE TWO MOST VALUABLE ITEMS ARE THE NATIONAL ADVISORY AND OUR OWN',
      'TELEMETRY. Internal detection data is the most consistently under-rated',
      'intelligence source in any organisation — it is the only source that is',
      'guaranteed to be about you.',
      '',
      'The 40,000-address list is fresh, large, free and nearly worthless.',
      'Volume without provenance produces false positives, not intelligence.',
    ].join('\n'),
    teaches:
      'Look at where the vendor attribution blog lands: C4, corroborate. Attribution feels like the most sophisticated output of intelligence and is the least actionable — it changes no control you would deploy. Compare it with the B3 item describing a technique, which stays useful after the infrastructure rotates.',
  },
];
