import type { PreparedCommand } from './types';

// ---------------------------------------------------------------------------
// Phase 11 prepared outputs — Network Security.
//
// Same closed-allowlist contract. Configuration artifacts for the enterprise
// network built on the Phase 4 zone architecture.
// ---------------------------------------------------------------------------

export const PHASE_11_COMMANDS: PreparedCommand[] = [
  {
    match: 'show access-list perimeter',
    tool: 'platform',
    provenance: 'prepared',
    output: [
      'Extended IP access list PERIMETER-IN',
      '    10 permit tcp 192.168.10.0/24 192.168.30.0/24 eq 443',
      '    20 permit ip any any                 (2,847,113 matches)',
      '    30 deny   tcp 192.168.40.0/24 192.168.30.0/24        (0 matches)',
      '    40 permit tcp 192.168.20.0/24 192.168.30.0/24 eq 22  (0 matches)',
      '    50 deny   tcp 192.168.10.0/24 192.168.20.0/24        (0 matches)',
      '    60 deny   ip any any                                 (0 matches)',
      '',
      'READ THE MATCH COUNTERS.',
      'Sequence 20 has 2.8 million matches. Everything below it has zero.',
      'Those are not unused rules — they are unreachable rules.',
    ].join('\n'),
    teaches:
      'The match counters are the fastest way to find shadowed rules on a live device. A rule with zero matches is either genuinely unused or structurally unreachable, and the two look identical in the config. Counters tell you which — and a broad permit with millions of matches sitting above a wall of zeroes is the signature.',
  },
  {
    match: 'explain rule ordering',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'FIREWALL RULE EVALUATION',
      '',
      '  Rules are read TOP-DOWN. The FIRST match wins. Evaluation stops there.',
      '',
      'THE CONSEQUENCE',
      '  A broad rule placed above a specific one makes the specific one dead.',
      '  The config still lists it, code review still sees it, and it never runs.',
      '',
      'WRONG                                  RIGHT',
      '  10 permit ip any any                   10 deny tcp guest -> servers',
      '  20 deny tcp guest -> servers           20 permit tcp users -> servers 443',
      '     (never reached)                     30 deny ip any any',
      '',
      'GENERAL PRINCIPLE',
      '  Specific rules first, general rules last, explicit deny at the bottom.',
      '',
      'This is why a firewall rule set is a PROGRAM, not a list of intentions.',
    ].join('\n'),
    teaches:
      'People review firewall rules as though each line were an independent statement of policy. They are not — the set is executed in order and earlier lines change what later lines mean. Reading a rule set correctly means simulating it, which is exactly what the analysis tool in this phase does.',
  },
  {
    match: 'compare ids ips',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      '                    IDS                        IPS',
      '------------------  -------------------------  -------------------------',
      'Placement           Out of band (SPAN/TAP)     Inline',
      'Sees                A copy of the traffic      The traffic itself',
      'Can block?          No — alerts only           Yes — drops in real time',
      'Latency added       None                       Some',
      'If it fails         Traffic unaffected         Depends on fail-open/closed',
      'False positive cost An unnecessary alert       A legitimate session dropped',
      '',
      'DETECTION METHODS (both)',
      '  Signature   Known patterns. Precise, blind to anything new.',
      '  Anomaly     Deviation from a learned baseline. Catches novel activity,',
      '              noisier, and needs a clean baseline to learn from.',
      '  Behavioural Sequences of actions rather than payloads.',
      '',
      'FAIL-OPEN vs FAIL-CLOSED on an inline IPS is an availability-versus-',
      'security decision. It should be deliberate and documented, not a default.',
    ].join('\n'),
    teaches:
      'The trade-off is the point. An IPS can stop an attack in progress, and it can also drop a legitimate transaction because of a bad signature — which is why many organisations run inline sensors in alert-only mode for a period before enabling blocking. Note the fail-open question: it decides what happens to your traffic when the sensor dies, and nobody wants to discover the answer during an outage.',
  },
  {
    match: 'show vlan config',
    tool: 'platform',
    provenance: 'prepared',
    output: [
      'VLAN  NAME          SUBNET             PORTS',
      '   1  default       —                  Gi0/5              <-- user port on VLAN 1',
      '  10  USERS         192.168.10.0/24    Gi0/1-4, Gi0/6-9',
      '  20  MANAGEMENT    192.168.20.0/24    Gi0/11-12',
      '  30  SERVERS       192.168.30.0/24    Gi0/13-16',
      '  40  GUEST         192.168.40.0/24    Gi0/10, Gi0/17-20',
      '',
      'TRUNK Gi0/24',
      '  native vlan 1                        <-- untagged, and it is VLAN 1',
      '  allowed vlan all                     <-- carries management and guest',
      '',
      'VLAN HOPPING',
      '  Double tagging works when the native VLAN is one the attacker can reach.',
      '  Two fixes: set the native VLAN to an unused, blackholed ID, and restrict',
      '  the trunk to only the VLANs it actually needs to carry.',
    ].join('\n'),
    teaches:
      'VLAN 1 is the default on every port before anyone configures anything, which is exactly why it should carry no traffic. And "allowed vlan all" on a trunk is the network equivalent of a permit-any firewall rule — it works, nobody notices, and it quietly removes the segmentation everything else depends on.',
  },
  {
    match: 'compare wireless security',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'STANDARD          STATUS      NOTES',
      '----------------  ----------  ------------------------------------------',
      'WEP               BROKEN      Crackable in minutes. Never acceptable.',
      'WPA (TKIP)        BROKEN      Deprecated; TKIP has practical attacks.',
      'WPA2-PSK          Adequate    Shared credential; no per-user identity',
      'WPA2-Enterprise   Good        802.1X, per-user auth, revocable',
      'WPA3-SAE          Good        Replaces PSK handshake; resists offline',
      '                              dictionary attack on the captured handshake',
      'WPA3-Enterprise   Best        802.1X plus modern cryptography',
      '',
      'PSK vs ENTERPRISE — the decision that matters',
      '  PSK         one credential everyone shares. Cannot revoke for one',
      '              leaver. No attribution. Fine for guest networks.',
      '  Enterprise  each user authenticates individually against the directory.',
      '              Revoke one account, that user loses wireless. Attribution',
      '              in the logs. Correct for corporate networks.',
      '',
      'HIDING THE SSID IS NOT SECURITY. The name appears in client probes.',
    ].join('\n'),
    teaches:
      'The PSK-versus-Enterprise decision maps straight onto the Phase 5 identity lifecycle: a shared credential cannot participate in a leaver process. When someone leaves, an Enterprise network revokes their access with their account, and a PSK network requires changing the key for everyone — which is why nobody ever does it.',
  },
  {
    match: 'explain nac',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'NETWORK ACCESS CONTROL — 802.1X',
      '',
      'THREE ROLES',
      '  Supplicant     the device asking for access',
      '  Authenticator  the switch or AP holding the port closed',
      '  Auth server    RADIUS, which checks the credential against the directory',
      '',
      'PORT STATES',
      '  auto              802.1X enforced — authenticate or no traffic',
      '  force-authorized  always open, 802.1X effectively disabled',
      '  force-unauthorized always closed',
      '',
      'BEYOND IDENTITY: POSTURE',
      '  NAC can also check device state before granting access — patch level,',
      '  disk encryption, EDR agent running. Failing devices go to a remediation',
      '  VLAN rather than being refused outright.',
      '',
      'WATCH FOR force-authorized EXEMPTIONS. They are usually added to fix a',
      'device that would not authenticate, and they never get removed.',
    ].join('\n'),
    teaches:
      'The posture check is what connects NAC to the Phase 5 conditional access model: both evaluate the device as well as the identity before granting access. And note the exemption pattern — a force-authorized port added to unblock a printer in 2023 is still open in 2026, and it is in a room anyone can walk into.',
  },
  {
    match: 'explain dhcp dns security',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'DHCP SECURITY',
      '  Threat    A rogue DHCP server answers faster than the real one and',
      '            supplies its own gateway and DNS — an on-path position with',
      '            no router compromise required.',
      '  Control   DHCP snooping. The switch drops DHCP offers from any port not',
      '            explicitly trusted, so only the real server can answer.',
      '  Also      Dynamic ARP Inspection uses the snooping table to drop',
      '            forged ARP, closing the Phase 3 ARP spoofing path.',
      '',
      'DNS SECURITY',
      '  Threat    Poisoned or spoofed responses redirect traffic without',
      '            touching the network path at all.',
      '  Controls  DNSSEC validates response authenticity.',
      '            Egress filtering forces all queries through a resolver you',
      '            log — which is what made the Phase 7 DNS evidence exist.',
      '            DNS filtering blocks known-bad and newly registered domains.',
      '',
      'DNS over HTTPS is a genuine tension: it protects user privacy and it',
      'bypasses your internal resolver, so you lose the logging. Decide',
      'deliberately rather than discovering it.',
    ].join('\n'),
    teaches:
      'DHCP snooping and Dynamic ARP Inspection close two of the on-path attacks from Phase 3 with switch configuration alone. And note the DNS-over-HTTPS tension — it is a real trade-off between user privacy and organisational visibility, and pretending it has an obvious answer is how policies get written that nobody follows.',
  },
  {
    match: 'show network hardening checklist',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'NETWORK HARDENING — the items that recur in every review',
      '',
      'SWITCHING',
      '  [ ] User ports off VLAN 1',
      '  [ ] Native VLAN set to an unused, blackholed ID',
      '  [ ] Trunks restricted to the VLANs they need',
      '  [ ] switchport nonegotiate on access ports (no DTP)',
      '  [ ] BPDU guard on access ports',
      '  [ ] Unused ports shut down and in an unused VLAN',
      '',
      'FILTERING',
      '  [ ] Specific rules above general ones',
      '  [ ] No permit any/any/any',
      '  [ ] Explicit deny-all at the end, logged',
      '  [ ] Rule set reviewed against match counters',
      '',
      'ACCESS',
      '  [ ] 802.1X on access ports, exemptions reviewed',
      '  [ ] Corporate wireless on Enterprise, not PSK',
      '  [ ] Management plane on its own segment',
      '',
      'SERVICES',
      '  [ ] DHCP snooping with only real servers trusted',
      '  [ ] Dynamic ARP Inspection enabled',
      '  [ ] DNS egress restricted to logged resolvers',
      '  [ ] NTP configured — correlation needs synchronised time',
    ].join('\n'),
    teaches:
      'Note the last line. NTP looks like an operations concern rather than a security one, and it is the reason cross-device correlation works at all — the Phase 7 investigation depended on events from six sources lining up in time. A network with drifting clocks cannot be investigated.',
  },
];
