import type { PreparedCommand } from './types';

// ---------------------------------------------------------------------------
// Phase 15 prepared outputs — Mobile / IoT / Embedded Security.
//
// Same closed-allowlist contract. All device IDs, IPs, and identifiers are
// fictional / documentation-range values. No real credentials, keys, or
// tokens appear.
// ---------------------------------------------------------------------------

export const PHASE_15_COMMANDS: PreparedCommand[] = [
  {
    match: 'show mdm enrollment',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'MDM ENROLLMENT SUMMARY — Tenant lab-corp (40 devices)',
      '',
      'OWNERSHIP  COUNT  ENROLLED  COMPLIANT  NON-COMPLIANT',
      '─────────  ─────  ────────  ─────────  ─────────────',
      'BYOD        15      15         12            3',
      'COBO        10      10         10            0',
      'COPE         8       8          7            1',
      'CYOD         7       7          7            0',
      '',
      'NON-COMPLIANT DEVICES',
      'DEVICE ID       OWNER          OWNERSHIP  ISSUE',
      '──────────────  ─────────────  ─────────  ─────────────────────────────',
      'mob-0231        j.alvarez      BYOD       Jailbreak detected, still syncing mail  ← FINDING',
      'mob-0198        r.chen         BYOD       No passcode policy enforced             ← FINDING',
      'mob-0304        t.osei         BYOD       MDM profile removed 14 days ago          ← FINDING',
      'mob-0412        k.patel        COPE       OS version 3 major versions behind       ← FINDING',
      '',
      'FINDINGS:',
      '  1. mob-0231 is jailbroken yet still holds an active corporate mail connection.',
      '     REMEDIATION: Enforce automatic access revocation on jailbreak/root detection, not just logging.',
      '  2. mob-0198 has no passcode policy — a lost device exposes the work container immediately.',
      '     REMEDIATION: Enforce a minimum 6-digit passcode or biometric as a condition of enrolment.',
      '  3. mob-0304 removed its MDM profile two weeks ago and was never flagged for access revocation.',
      '     REMEDIATION: Configure automatic conditional-access block when MDM check-in lapses.',
    ].join('\n'),
    teaches:
      'An MDM enrolment report is only useful if non-compliance triggers an automatic response. Detection without enforcement — as with mob-0231 and mob-0304 — leaves the exact gap the control was supposed to close.',
  },
  {
    match: 'show mobile app policies',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'MOBILE APPLICATION POLICY REPORT — Tenant lab-corp',
      '',
      'PLATFORM  POLICY                              STATUS',
      '────────  ──────────────────────────────────  ─────────────',
      'iOS       App Store only (no sideloading)      ENFORCED  ✓',
      'iOS       Managed app configuration required    ENFORCED  ✓',
      'Android   Google Play Protect required          ENFORCED  ✓',
      'Android   Allow installation from unknown sources DISABLED on 34/40  ← FINDING',
      '',
      'DEVICES WITH SIDELOADING ENABLED',
      'DEVICE ID       OWNER          APP INSTALLED (UNVERIFIED)',
      '──────────────  ─────────────  ─────────────────────────',
      'mob-0177        d.nguyen       "QuickScan Pro" (unsigned APK, unknown publisher)',
      'mob-0290        m.reyes        "FreeVPN Turbo" (unsigned APK, unknown publisher)',
      '',
      'APP PERMISSION REVIEW (sample)',
      'APP NAME            REQUESTED PERMISSIONS                          NOTE',
      '───────────────────  ──────────────────────────────────────────────  ──────────────────',
      'CorpMail             Contacts, Calendar, Notifications               Expected for function',
      'PocketFlashlight     Contacts, Location, SMS, Camera                 ← FINDING: excessive',
      '',
      'FINDINGS:',
      '  1. 6 Android devices still allow installation from unknown sources.',
      '     REMEDIATION: Push a device policy disabling unknown-source installs fleet-wide.',
      '  2. mob-0177 and mob-0290 have sideloaded unsigned APKs from unverified publishers.',
      '     REMEDIATION: Quarantine both devices pending removal; block app hashes in the MDM catalogue.',
      '  3. PocketFlashlight requests contacts, location, SMS, and camera with no functional need.',
      '     REMEDIATION: Block via the managed app catalogue; investigate for data exfiltration.',
    ].join('\n'),
    teaches:
      'Sideloading and excessive permissions are two independent risks that both bypass the same control: app-store review. A flashlight app requesting SMS access is a permission mismatch worth investigating regardless of where it was installed from.',
  },
  {
    match: 'show byod devices',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'BYOD DEVICE REVIEW — Tenant lab-corp (15 devices)',
      '',
      'DEVICE ID       OWNER          CONTAINERISED  PASSCODE  REMOTE WIPE TESTED',
      '──────────────  ─────────────  ─────────────  ────────  ──────────────────',
      'mob-0102        a.kim          YES            YES       YES (Q3 2026)',
      'mob-0177        d.nguyen       YES            YES       YES (Q3 2026)',
      'mob-0198        r.chen         NO             NO        NEVER                ← FINDING',
      'mob-0231        j.alvarez      YES            YES       FAILED (jailbroken)  ← FINDING',
      'mob-0256        s.brooks       YES            YES       YES (Q3 2026)',
      '',
      'FINDINGS:',
      '  1. mob-0198 has no work-container separation and no passcode — a full personal-data wipe',
      '     would be the only remediation option if this device is lost, which the employee will resist.',
      '     REMEDIATION: Enrol in MAM containerisation and enforce a passcode as a condition of continued access.',
      '  2. mob-0231 (jailbroken) failed its last remote-wipe test — the wipe agent was disabled by the jailbreak.',
      '     REMEDIATION: Revoke access immediately; do not rely on wipe capability for a jailbroken device.',
    ].join('\n'),
    teaches:
      'A remote-wipe capability is only a real control if it is tested. mob-0231 shows why: the capability existed on paper but had already been disabled by the same compromise it was meant to remediate.',
  },
  {
    match: 'show mobile compliance report',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'MOBILE FLEET COMPLIANCE REPORT — Tenant lab-corp',
      '',
      'TOTAL DEVICES: 40   COMPLIANT: 35 (87.5%)   NON-COMPLIANT: 5 (12.5%)',
      '',
      'VIOLATION SUMMARY',
      'DEVICE ID       OWNERSHIP  VIOLATION                                  SEVERITY',
      '──────────────  ─────────  ──────────────────────────────────────────  ────────',
      'mob-0231        BYOD       Jailbroken, MDM compliance check bypassed   CRITICAL',
      'mob-0198        BYOD       No passcode, no containerisation            HIGH',
      'mob-0304        BYOD       MDM profile removed, access not revoked     HIGH',
      'mob-0412        COPE       OS 3 major versions behind current release  MEDIUM',
      'mob-0177        BYOD       Sideloaded unsigned APK installed            MEDIUM',
      '',
      'POLICY CHECK:',
      '  Organisation policy requires: passcode enforced, no jailbreak/root, no sideloading,',
      '  OS within one major version of current, MDM check-in within 7 days.',
      '  5 of 40 devices (12.5%) are NON-COMPLIANT.',
    ].join('\n'),
    teaches:
      'A single consolidated compliance report is what turns individual findings into an auditable, prioritisable list. Severity ranking (critical → medium) tells you which device to act on first.',
  },
  {
    match: 'show iot inventory',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'IOT DEVICE INVENTORY — Building lab-hq',
      '',
      'DEVICE CLASS         COUNT  VENDOR         FIRMWARE       CREDENTIAL STATUS',
      '───────────────────  ─────  ─────────────  ─────────────  ──────────────────────',
      'IP Cameras             24   VistaCam       v2.1 (2021)    Factory default (admin)  ← FINDING',
      'HVAC Controllers        6   ThermoNet      v1.4 (2020)    Factory default (admin)  ← FINDING',
      'Badge Readers          12   SecureEntry    v3.0 (2026)    Unique per-device cert   ✓',
      'Smart TVs (lobby)       2   ViewCast       v1.0 (2019)    Factory default (admin)  ← FINDING',
      '',
      'FINDINGS:',
      '  1. 24 IP cameras, 6 HVAC controllers, and 2 smart TVs still use factory-default credentials.',
      '     REMEDIATION: Rotate all default credentials to unique, managed values immediately.',
      '  2. Badge readers are the only class using per-device certificate identity — the model to extend.',
    ].join('\n'),
    teaches:
      'An IoT inventory is the equivalent of an asset register. Default credentials, present across three of four device classes here, are the single highest-value finding — and the cheapest to fix.',
  },
  {
    match: 'show iot network segments',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'NETWORK SEGMENTATION — Building lab-hq',
      '',
      'VLAN 10 (Corporate)      10.10.0.0/24   Workstations, file server, domain controller',
      'VLAN 20 (Guest)          10.20.0.0/24   Visitor Wi-Fi, internet-only',
      'VLAN 10 (Corporate)      10.10.0.0/24   IP Cameras (24)          ← FINDING: sharing corporate VLAN',
      'VLAN 10 (Corporate)      10.10.0.0/24   HVAC Controllers (6)     ← FINDING: sharing corporate VLAN',
      'VLAN 20 (Guest)          10.20.0.0/24   Smart TVs (2)            ← FINDING: sharing guest VLAN',
      'VLAN 30 (Management)     10.30.0.0/24   Switch/firewall mgmt interfaces  OK',
      '',
      'NO DEDICATED IOT VLAN EXISTS.',
      '',
      'FINDINGS:',
      '  1. Cameras and HVAC controllers sit on the corporate VLAN — a compromised camera can reach',
      '     the domain controller and file server directly.',
      '     REMEDIATION: Create VLAN 40 (IoT) at 10.40.0.0/24; migrate cameras and HVAC controllers.',
      '  2. Lobby smart TVs sit on the guest VLAN — a compromised guest laptop can reach the TVs and',
      '     vice versa.',
      '     REMEDIATION: Migrate smart TVs to VLAN 40 (IoT) as well; guest and IoT must not share a broadcast domain.',
      '  3. Recommended ACL for VLAN 40: allow only outbound HTTPS to each vendor\'s cloud management',
      '     endpoint; deny all other inbound and inter-VLAN traffic by default.',
    ].join('\n'),
    teaches:
      'A flat network with no dedicated IoT VLAN means every device inherits the trust level of whatever VLAN it happens to be plugged into. Segmentation has to be deliberate, not a side effect of which switch port was free.',
  },
  {
    match: 'show firmware status',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'FIRMWARE AND LIFECYCLE STATUS — Building lab-hq',
      '',
      'DEVICE CLASS         CURRENT VERSION  LATEST AVAILABLE  VENDOR SUPPORT',
      '───────────────────  ───────────────  ────────────────  ──────────────────────',
      'IP Cameras (VistaCam)      v2.1            v2.1          Active (patches available)',
      'HVAC (ThermoNet)           v1.4            v1.4          END OF LIFE (2024)  ← FINDING',
      'Badge Readers (SecureEntry) v3.0           v3.0          Active (patches available)',
      'Smart TVs (ViewCast)       v1.0            v1.0          END OF LIFE (2022)  ← FINDING',
      '',
      'FINDINGS:',
      '  1. ThermoNet HVAC controllers reached end-of-life in 2024 — no further firmware updates',
      '     will ever be released, regardless of future vulnerabilities discovered.',
      '     REMEDIATION: Budget for replacement; in the interim, isolate on the IoT VLAN and monitor closely.',
      '  2. ViewCast smart TVs reached end-of-life in 2022 — same permanent-risk profile.',
      '     REMEDIATION: Replace at next refresh cycle; disable any unused network services on the device today.',
    ].join('\n'),
    teaches:
      'End-of-life firmware is not a gap you close — it is a standing risk you manage. The only durable responses are replacement or stronger compensating controls around the device, never "wait for a patch."',
  },
  {
    match: 'show device certificates',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'DEVICE IDENTITY / CERTIFICATE STATUS — Building lab-hq',
      '',
      'DEVICE CLASS         IDENTITY METHOD              PER-DEVICE?  NOTE',
      '───────────────────  ───────────────────────────  ───────────  ──────────────────────────',
      'IP Cameras             Shared embedded credential   NO           ← FINDING: one secret for all 24',
      'HVAC Controllers       Shared embedded credential   NO           ← FINDING: one secret for all 6',
      'Badge Readers          Unique X.509 cert per unit   YES          ✓ Correct model',
      'Smart TVs              None (open pairing)          NO           ← FINDING: no authentication at all',
      '',
      'FINDINGS:',
      '  1. All 24 cameras share a single embedded credential — compromising one exposes every camera,',
      '     and revoking the credential requires re-provisioning the entire fleet at once.',
      '     REMEDIATION: Migrate to per-device certificates issued at provisioning, matching the badge-reader model.',
      '  2. Smart TVs pair with no authentication at all — any device on the same VLAN can control them.',
      '     REMEDIATION: Require paired-device authentication or remove network connectivity if unused.',
    ].join('\n'),
    teaches:
      'Badge readers show the target state: one identity per device, individually revocable. Everything else in this inventory shares a single secret across an entire device class — the worst-case blast radius for a single compromise.',
  },
];
