import type { PreparedCommand } from './types';

// ---------------------------------------------------------------------------
// Phase 16 prepared outputs — Application & Data Security.
//
// Same closed-allowlist contract. All code snippets, IDs, and identifiers are
// fictional / illustrative values from a simulated sample application. No
// real credentials, keys, or tokens appear.
// ---------------------------------------------------------------------------

export const PHASE_16_COMMANDS: PreparedCommand[] = [
  {
    match: 'show vulnerable code review',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'CODE REVIEW REPORT — sample-app (commit a1b2c3d)',
      '',
      'FILE: auth/login.py',
      '  Line 42: query = "SELECT * FROM users WHERE username=\'" + username + "\' AND pwd_hash=\'" + pwdHash + "\'"',
      '  ← FINDING: string-concatenated SQL query. Untrusted input reaches the query unparameterised.',
      '',
      'FILE: comments/views.py',
      '  Line 88: return f"<div class=\'comment\'>{comment_text}</div>"',
      '  ← FINDING: user-supplied comment_text rendered into HTML with no output encoding (stored XSS).',
      '',
      'FILE: reports/export.py',
      '  Line 15: os.system("grep " + search_term + " /var/log/app.log")',
      '  ← FINDING: user-supplied search_term passed directly to a shell command (OS command injection).',
      '',
      'SUMMARY: 3 findings — 2 injection (SQL, OS command), 1 stored XSS.',
      '',
      'REMEDIATION:',
      '  1. login.py — convert to a parameterised query: cursor.execute("SELECT * FROM users WHERE',
      '     username=%s AND password_hash=%s", (username, password_hash)).',
      '  2. views.py — HTML-encode comment_text before rendering, or use the templating engine\'s',
      '     autoescaping (do not disable it).',
      '  3. export.py — replace os.system with a safe subprocess call using an argument list, never',
      '     shell=True with concatenated user input.',
    ].join('\n'),
    teaches:
      'Every injection finding here shares the same root cause: untrusted input reaching an interpreter (SQL, shell, HTML) as if it were trusted code or markup. The fix is always structural separation of code from data, never "escape harder."',
  },
  {
    match: 'show input validation report',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'INPUT VALIDATION REPORT — sample-app',
      '',
      'ENDPOINT                METHOD  QUERY CONSTRUCTION        VALIDATION           STATUS',
      '───────────────────────  ──────  ────────────────────────  ───────────────────  ──────────────',
      '/login                   POST    String concatenation      None                 ← FINDING',
      '/search                  GET     Parameterised              Allow-list (basic)   COMPLIANT ✓',
      '/comments                POST    Parameterised              None (no encoding)   ← FINDING',
      '/reports/export          POST    Shell concatenation        None                 ← FINDING',
      '/profile/update          PUT     Parameterised              Type + length check  COMPLIANT ✓',
      '',
      'FINDINGS:',
      '  1. /login builds its query via string concatenation with zero input validation — the highest',
      '     severity gap in the application.',
      '  2. /comments uses a parameterised query for storage (safe from SQLi) but the stored value is',
      '     rendered without output encoding on read — the vulnerability class is XSS, not injection.',
      '  3. /reports/export concatenates user input into a shell command with zero validation.',
    ].join('\n'),
    teaches:
      '"Parameterised" and "safe" are not the same thing for every vulnerability class. /comments shows why: parameterisation stops SQL injection on write, but the application still needs output encoding on read to stop XSS. Each vulnerability class needs its own specific control.',
  },
  {
    match: 'show session config',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'SESSION / COOKIE CONFIGURATION — sample-app',
      '',
      'COOKIE          SECURE FLAG  HTTPONLY FLAG  SAMESITE  EXPIRY               INVALIDATED ON LOGOUT',
      '──────────────  ───────────  ─────────────  ────────  ───────────────────  ──────────────────────',
      'session_id      NO ← FINDING NO ← FINDING   None      Never ← FINDING       NO ← FINDING',
      'csrf_token      YES          YES            Strict    Session               YES',
      '',
      'FINDINGS:',
      '  1. session_id is missing the Secure flag — it can be transmitted over plain HTTP if an',
      '     attacker downgrades the connection.',
      '  2. session_id is missing the HttpOnly flag — client-side JavaScript, including any injected',
      '     via the stored XSS finding in show vulnerable code review, can read and exfiltrate it.',
      '  3. session_id never expires and is not invalidated server-side on logout — a captured token',
      '     remains valid indefinitely.',
      '',
      'REMEDIATION: Set Secure, HttpOnly, and SameSite=Strict on session_id; enforce a maximum session',
      'lifetime; invalidate the session server-side (not just clear the cookie) on logout.',
    ].join('\n'),
    teaches:
      'A stolen session token is as good as a stolen password for as long as the session remains valid. The three findings here compound each other: no HttpOnly means the XSS finding can steal the token, and no expiry means that stolen token works forever.',
  },
  {
    match: 'show authz test results',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'AUTHORISATION TEST SUITE — sample-app',
      '',
      'TEST                                              RESULT',
      '─────────────────────────────────────────────────  ──────────────────',
      'User A requests own /invoices/1042                  200 OK (expected)',
      'User A requests /invoices/1043 (belongs to User B)  200 OK  ← FINDING: IDOR',
      'User A requests /admin/reports (non-admin role)     200 OK  ← FINDING: missing role check',
      'User A requests /profile/1042 (own profile)         200 OK (expected)',
      'Anonymous request to /invoices/1042 (no session)    200 OK  ← FINDING: no auth check at all',
      '',
      'FINDINGS:',
      '  1. /invoices/{id} performs no ownership check — any authenticated user can view any invoice',
      '     by guessing or incrementing the ID (IDOR).',
      '  2. /admin/reports has no server-side role check; a non-admin user reaches it directly.',
      '  3. /invoices/{id} also accepts unauthenticated requests — the endpoint has no session check',
      '     at all, which is more severe than the IDOR alone.',
      '',
      'REMEDIATION: Add a server-side check on every request to /invoices/{id} verifying',
      'session.user_id == invoice.owner_id; add a role-based guard on /admin/* routes; require a',
      'valid session on every non-public endpoint.',
    ].join('\n'),
    teaches:
      'The anonymous-access finding is the most important one here: it shows that even a correct ownership check would not have been enough, because the endpoint never verified a session existed in the first place. Authentication and authorisation both have to be checked, in that order, on every request.',
  },
  {
    match: 'show data inventory',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'DATA INVENTORY — lab-corp',
      '',
      'ASSET                                   CURRENT CLASSIFICATION  SUGGESTED CLASSIFICATION',
      '───────────────────────────────────────  ──────────────────────  ────────────────────────',
      'Customer DB (names, emails, purchases)   Internal                Confidential  ← FINDING',
      'Customer DB (SSNs, card numbers)          Confidential            Restricted    ← FINDING',
      'HR records (salaries, reviews)            Internal                Confidential  ← FINDING',
      'Marketing brochures (published)           Internal                Public        ← FINDING',
      'Source code — encryption key module       Confidential            Restricted    ← FINDING',
      'Company holiday calendar                  Internal                Internal      COMPLIANT ✓',
      '',
      'FINDINGS:',
      '  1. Customer PII/purchase history is under-classified as Internal — it is business-sensitive',
      '     and should be Confidential at minimum.',
      '  2. SSNs and card numbers are regulated data and must be Restricted, the strictest tier,',
      '     not merely Confidential.',
      '  3. Already-published marketing material is over-classified as Internal with no benefit —',
      '     classification should reflect actual sensitivity, not organisational habit.',
      '  4. The encryption key management source code is Restricted-tier by impact: its compromise',
      '     would undermine every other control in the system.',
    ].join('\n'),
    teaches:
      'Classification drift in both directions is a finding: under-classifying leaves sensitive data under-protected, and over-classifying (the holiday calendar\'s cousin, the published brochure) wastes controls and trains people to ignore the labels.',
  },
  {
    match: 'show data protection methods',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'DATA PROTECTION METHOD REVIEW — lab-corp',
      '',
      'FIELD                        CLASSIFICATION  METHOD APPLIED        STATUS',
      '───────────────────────────  ──────────────  ─────────────────────  ──────────────',
      'Customer SSN (database)      Restricted      Tokenised              COMPLIANT ✓',
      'Customer card number (DB)    Restricted      Masked only            ← FINDING',
      'Customer card number (UI)    Restricted      Masked (last 4 shown)  COMPLIANT ✓',
      'Password (database)          Restricted      Salted hash            COMPLIANT ✓',
      'Employee salary (database)   Confidential    Plaintext              ← FINDING',
      'Session data (in transit)    Restricted      TLS 1.3                COMPLIANT ✓',
      '',
      'FINDINGS:',
      '  1. The card number stored in the database is only masked, not tokenised or encrypted —',
      '     masking is a display-layer control and provides no protection for the stored value itself.',
      '     REMEDIATION: Tokenise the stored card number; continue masking it for UI display only.',
      '  2. Employee salary data (Confidential tier) is stored in plaintext with no protection at rest.',
      '     REMEDIATION: Encrypt the column at rest; restrict decryption access to HR system roles only.',
    ].join('\n'),
    teaches:
      'The card-number finding is the classic exam trap: masking looks like protection because the full value is hidden on screen, but the underlying database column is unprotected. Masking secures a view of the data, not the data itself.',
  },
  {
    match: 'show dlp alerts',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'DLP ALERT LOG — lab-corp (last 30 days)',
      '',
      'TIMESTAMP              CHANNEL  MATCH TYPE          ACTION TAKEN   NOTE',
      '─────────────────────  ───────  ──────────────────  ─────────────  ──────────────────────────',
      '2026-08-12T09:14:00Z   Email    Credit card pattern  BLOCKED        Working as intended',
      '2026-08-20T15:02:00Z   USB      SSN pattern (bulk)   BLOCKED        Working as intended',
      '2026-09-01T11:47:00Z   Email    SSN pattern (bulk)   LOGGED ONLY    ← FINDING: 10,000 SSNs reached',
      '                                                                       a personal Gmail address',
      '',
      'POLICY REVIEW:',
      '  Restricted-tier data → Email channel → policy action currently set to LOG ONLY.',
      '  Restricted-tier data → USB / Email (other patterns) → policy action set to BLOCK.',
      '',
      'FINDINGS:',
      '  1. The 2026-09-01 event shows 10,000 SSNs left the organisation via email because the SSN',
      '     pattern on the email channel was configured to log, not block, unlike the USB channel.',
      '     REMEDIATION: Align the email channel policy for Restricted-tier data to BLOCK, matching USB.',
    ].join('\n'),
    teaches:
      'A DLP policy is only as good as its weakest configured channel. Blocking on USB while only logging the same data type over email is not a partial control — it is a guaranteed exfiltration path for anyone who tries email first.',
  },
  {
    match: 'show retention schedule',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'DATA RETENTION AND DISPOSAL SCHEDULE — lab-corp',
      '',
      'DATA CLASS                  RETENTION PERIOD     DISPOSAL METHOD          STATUS',
      '───────────────────────────  ────────────────────  ───────────────────────  ──────────────',
      'Customer transaction records  7 years (regulatory)  Cryptographic erasure    COMPLIANT ✓',
      'HR records (former employees) 7 years post-exit     Physical destruction     COMPLIANT ✓',
      'Marketing email lists        Not defined            None defined             ← FINDING',
      'Closed customer accounts     Not defined            None defined             ← FINDING',
      'Application access logs      1 year                 Automated deletion       COMPLIANT ✓',
      '',
      'FINDINGS:',
      '  1. Marketing email lists have no defined retention period — historically retained indefinitely,',
      '     including contacts who unsubscribed years ago.',
      '  2. Closed customer accounts have no defined retention period or disposal method — full customer',
      '     PII is retained forever after account closure with no business justification.',
      '',
      'REMEDIATION: Define a retention period for both data classes based on legal/business need',
      '(e.g., closed accounts: 2 years post-closure, then cryptographic erasure), and schedule',
      'automated disposal rather than relying on manual cleanup.',
    ].join('\n'),
    teaches:
      'Two data classes with no defined retention are not an oversight in isolation — they are the two most likely to contain PII with no ongoing business need, which is exactly the profile regulators and attackers both look for first.',
  },
];
