import type { PreparedCommand } from './types';

// ---------------------------------------------------------------------------
// Phase 5 prepared outputs — Identity & Access Management.
//
// SAFETY: signatures, key material, and token payloads are shown STRUCTURALLY
// and always redacted. Nothing here is a usable assertion, token, hash, or
// credential. The teaching value is in the shape of the artifact, not its bytes.
// ---------------------------------------------------------------------------

export const PHASE_5_COMMANDS: PreparedCommand[] = [
  // --------------------------- Lifecycle ---------------------------
  {
    match: 'trace identity lifecycle',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'Employee identity lifecycle — Priya Raman, Finance Analyst',
      '',
      '  [1] HR SYSTEM          Record created: start 2026-03-02, Finance, mgr J. Adeyemi',
      '  [2] IDENTITY PLATFORM  Identity minted; birthright entitlements from role (12)',
      '  [3] ACCOUNT CREATION   AD object written: CN=priya.raman,OU=Finance,DC=lab,DC=local',
      '  [4] MFA ENROLMENT      FIDO2 security key registered from a verified device',
      '  [5] SSO / FEDERATION   IdP session established; OIDC trust to finance app',
      '  [6] APPLICATION ACCESS Conditional access evaluated: compliant device, known location',
      '  [7] AUTHORIZATION      Role "finance-analyst" grants read on FIN-REPORTS',
      '  [8] AUDIT LOGS         Sign-in, MFA result, entitlement grants -> SIEM-01',
      '  [9] DEPROVISIONING     On leave: disable -> revoke tokens -> reclaim -> transfer',
      '',
      'Each stage consumes what the previous one produced. Break stage 1 and',
      'every stage after it is working from stale truth.',
    ].join('\n'),
    teaches:
      'HR is the authoritative source — the person exists because HR says so. Note stage 9 has four ordered actions, and that disable and revoke are separate: disabling stops future authentication but does nothing to a token already issued.',
  },
  {
    match: 'show joiner flow',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'JOINER — Priya Raman',
      '',
      'TRIGGER    HR record created, start date 2026-03-02',
      '',
      'STEP  ACTION                                    SYSTEM',
      '  1   Identity minted and matched (no prior)    Identity platform',
      '  2   Birthright entitlements calculated (12)   Identity platform',
      '  3   AD account created, groups applied        DC-01',
      '  4   Initial credential delivered out of band  Service desk',
      '  5   MFA enrolled from a verified device       IdP',
      '  6   Application access granted by role        SSO / app',
      '',
      'CHARACTERISTIC FAILURE: being late. If the HR record is created after the',
      'start date, the new starter cannot work on day one, and the service desk',
      'creates an account manually to unblock them — which is how orphaned',
      'accounts are born.',
    ].join('\n'),
    teaches:
      'Joiner failures are mostly timing failures, and they have a security consequence rather than only an inconvenience: manual workarounds bypass provisioning and produce accounts nothing will ever deprovision.',
  },
  {
    match: 'show leaver flow',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'LEAVER — deprovisioning sequence',
      '',
      'ORDER  ACTION                          WHY THIS ORDER',
      '  1    Disable the account             Stops NEW authentication immediately',
      '  2    Revoke sessions and tokens      Kills what was ALREADY issued',
      '  3    Reclaim licences                Cost, and reduces the account surface',
      '  4    Transfer data ownership         Before any archival or removal',
      '',
      'NOT ON THIS LIST: delete. Disable before delete, always — deleting the',
      'account destroys the evidence an investigation may need.',
      '',
      'Steps 1 and 2 are DIFFERENT ACTIONS. A process that performs only step 1',
      'leaves federated applications working from tokens issued earlier.',
    ].join('\n'),
    teaches:
      'The single most common real-world deprovisioning defect is treating disable as sufficient. A refresh token with days of life left keeps an application working without ever consulting the identity provider again.',
  },

  // --------------------------- Directory ---------------------------
  {
    match: 'show ad user priya.raman',
    tool: 'platform',
    provenance: 'prepared',
    output: [
      'DistinguishedName : CN=priya.raman,OU=Finance,DC=lab,DC=local',
      'SamAccountName    : priya.raman',
      'UserPrincipalName : priya.raman@lab.local',
      'Enabled           : True',
      'PasswordLastSet   : 2026-03-02 09:14:02',
      'LastLogonDate     : 2026-09-07 08:41:55',
      'MemberOf          : CN=Finance-Analysts,OU=Groups,DC=lab,DC=local',
      '                    CN=FIN-Reports-Read,OU=Groups,DC=lab,DC=local',
      '                    CN=Domain Users,CN=Users,DC=lab,DC=local',
      'ServicePrincipal  : (none — this is a user, not a service account)',
      '',
      'Note: no password hash is displayed, here or anywhere in this platform.',
    ].join('\n'),
    teaches:
      'Read a distinguished name most specific to least: CN (the object), OU (the container, used for delegation and Group Policy), then DC components (the domain). Group membership is how RBAC is actually implemented in Active Directory.',
  },
  {
    match: 'klist',
    tool: 'windows',
    provenance: 'prepared',
    output: [
      'Current LogonId is 0:0x3e7f2',
      '',
      'Cached Tickets: (2)',
      '',
      '#0> Client: priya.raman @ LAB.LOCAL',
      '    Server: krbtgt/LAB.LOCAL @ LAB.LOCAL      <-- ticket-granting ticket',
      '    KerbTicket Encryption Type: AES-256-CTS-HMAC-SHA1-96',
      '    Start Time: 09/08/2026 08:41:55',
      '    End Time:   09/08/2026 18:41:55',
      '    Renew Time: 09/15/2026 08:41:55',
      '',
      '#1> Client: priya.raman @ LAB.LOCAL',
      '    Server: cifs/srv-01.lab.local @ LAB.LOCAL  <-- service ticket',
      '    Start Time: 09/08/2026 08:42:10',
      '    End Time:   09/08/2026 18:41:55',
      '',
      'Session keys are not displayed.',
    ].join('\n'),
    teaches:
      'Ticket #0 is the TGT — the ticket that lets you request other tickets. Ticket #1 is a service ticket for one specific service (cifs on srv-01). Note the service ticket cannot outlive the TGT that obtained it.',
  },
  {
    match: 'explain kerberos flow',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'Kerberos exchange — troubleshooting depth',
      '',
      '  AS-REQ   Client -> KDC     "I am priya.raman"  (pre-auth timestamp)',
      '  AS-REP   KDC -> Client     Ticket-granting ticket',
      '  TGS-REQ  Client -> KDC     "TGT attached; I want cifs/srv-01"',
      '  TGS-REP  KDC -> Client     Service ticket for cifs/srv-01',
      '  AP-REQ   Client -> Service Service ticket presented',
      '  AP-REP   Service -> Client Validated LOCALLY — the KDC is not contacted',
      '',
      'KEY PROPERTY: the password crosses the network once, and the service',
      'never sees it at all.',
      '',
      'THE THREE COMMON FAILURES, in rough frequency order:',
      '  1. Clock skew  > ~5 min      Timestamps prevent replay; skew invalidates',
      '  2. SPN missing or duplicated The KDC cannot identify the target service',
      '  3. DNS misresolution         Client asks for a ticket for the wrong host',
    ].join('\n'),
    teaches:
      'The service validating locally is what makes Kerberos scale — and it is also why a disabled account can keep using a valid service ticket until it expires. Check time, then SPN, then DNS.',
  },

  // --------------------------- Federation ---------------------------
  {
    match: 'compare mfa factors',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'FACTOR          CATEGORY       RELAYABLE?  NOTES',
      '--------------  -------------  ----------  -------------------------------',
      'Password        Know           n/a         Single factor on its own',
      'Security Q&A    Know           n/a         Still "know" — not a 2nd factor',
      'SMS code        Have           YES         Also exposed to SIM swap',
      'TOTP code       Have           YES         Better than SMS, still relayable',
      'Push approval   Have           YES         Also vulnerable to MFA fatigue',
      'Push + number   Have           YES         Fatigue addressed, relay is not',
      'FIDO2 / WebAuthn Have          NO          Bound to the ORIGIN cryptographically',
      'Fingerprint     Are            n/a         Usually unlocks a local authenticator',
      '',
      'Only the origin-bound factor survives an adversary-in-the-middle relay:',
      'the authenticator will not respond to a lookalike domain even if the user',
      'cooperates completely.',
    ].join('\n'),
    teaches:
      'A password plus a security question is two-step but single-factor — both are things you know. And "we have MFA" says nothing useful until you know which factor: only FIDO2 defeats the Phase 3 attack chain.',
  },
  {
    match: 'show saml assertion',
    tool: 'platform',
    provenance: 'prepared',
    output: [
      '<saml:Assertion ID="_a1b2..." IssueInstant="2026-09-08T08:41:55Z">',
      '  <saml:Issuer>https://idp.lab.local/saml</saml:Issuer>',
      '  <ds:Signature>[REDACTED — no usable key material in this platform]</ds:Signature>',
      '  <saml:Subject>',
      '    <saml:NameID Format="emailAddress">priya.raman@lab.local</saml:NameID>',
      '  </saml:Subject>',
      '  <saml:Conditions NotBefore="2026-09-08T08:41:55Z"',
      '                   NotOnOrAfter="2026-09-08T08:46:55Z">',
      '    <saml:AudienceRestriction>',
      '      <saml:Audience>https://finance.lab.local</saml:Audience>',
      '    </saml:AudienceRestriction>',
      '  </saml:Conditions>',
      '  <saml:AttributeStatement>',
      '    <saml:Attribute Name="groups">Finance-Analysts</saml:Attribute>',
      '  </saml:AttributeStatement>',
      '</saml:Assertion>',
      '',
      'The service provider MUST validate: signature, issuer, audience, and the',
      'NotBefore/NotOnOrAfter window.',
    ].join('\n'),
    teaches:
      'Four validations decide whether an assertion is trustworthy. Audience restriction is the one most often overlooked — without it, an assertion minted for one application could be replayed at another.',
  },
  {
    match: 'show oidc token',
    tool: 'platform',
    provenance: 'prepared',
    output: [
      'OIDC ID token — decoded structure (signature redacted)',
      '',
      'HEADER   { "alg": "RS256", "kid": "[REDACTED]" }',
      '',
      'CLAIMS   {',
      '           "iss": "https://idp.lab.local",     issuer',
      '           "sub": "8f14e45f-...-redacted",     stable subject identifier',
      '           "aud": "finance-app",               audience',
      '           "exp": 1789012345,                  expiry',
      '           "iat": 1789008745,                  issued at',
      '           "amr": ["pwd", "hwk"],              password + hardware key',
      '           "email": "priya.raman@lab.local"',
      '         }',
      '',
      'SIGNATURE [REDACTED — no usable key material in this platform]',
      '',
      'This is an ID TOKEN: it states WHO the user is.',
      'An OAuth ACCESS TOKEN is different: it states what the bearer MAY DO.',
      'Never use an access token as proof of identity.',
    ].join('\n'),
    teaches:
      'The amr claim records how the user authenticated — "hwk" means a hardware key was used, which a relying party can require for sensitive operations. Note the sub claim is the stable identifier; email can change and should never be the join key.',
  },
  {
    match: 'show conditional access',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'Conditional access policy set — evaluated at sign-in',
      '',
      'POLICY                    CONDITION                       ACTION',
      'Require compliant device  Device not managed/compliant    Block',
      'Require MFA               All users, all cloud apps       Grant with MFA',
      'Require phishing-resistant Privileged role assignment     Grant with FIDO2 only',
      'Block legacy auth         Legacy protocol used            Block',
      'Risk-based step-up        Sign-in risk = medium or high   Require re-auth',
      'Unfamiliar location       ASN never seen for this user    Require re-auth + alert',
      '',
      'Evaluation combines IDENTITY signals (who, risk) with DEVICE signals',
      '(managed, compliant) — neither alone is sufficient.',
      '',
      'Note: "Block legacy auth" matters because legacy protocols predate MFA and',
      'cannot enforce it, so leaving them enabled bypasses every policy above.',
    ].join('\n'),
    teaches:
      'This is where Zero Trust stops being a principle and becomes a policy evaluation. The device signal comes from management or NAC (Phase 4); the identity signal comes from the IdP. Legacy authentication is the standard bypass — disable it first.',
  },

  // --------------------------- Authorization ---------------------------
  {
    match: 'show access review',
    tool: 'platform',
    provenance: 'prepared',
    output: [
      'Access review — Marketing role cohort, Q3',
      '',
      'USER              ROLE                ENTITLEMENTS  PEER MEDIAN  FLAG',
      'a.silva           marketing-analyst             11           12',
      'l.moreau          marketing-analyst             12           12',
      'd.okonkwo         marketing-analyst             47           12   <-- REVIEW',
      'k.yamada          marketing-analyst             13           12',
      '',
      'd.okonkwo detail:',
      '  Transferred from Finance 2026-05-04',
      '  Marketing birthright entitlements added on transfer date        (12)',
      '  Finance entitlements from previous role STILL ACTIVE            (35)',
      '  Access requests or exceptions on file                            (0)',
      '',
      'Two other recent movers show the same pattern — this is systemic.',
    ].join('\n'),
    teaches:
      '47 entitlements means nothing on its own; 47 against a peer median of 12 is a finding. Peer comparison is what makes over-permission diagnosable rather than a judgement call — and three movers with the same pattern says fix the process, not the person.',
  },
  {
    match: 'compare rbac abac',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      '                RBAC                        ABAC',
      '--------------  --------------------------  --------------------------',
      'Grants via      Role membership             Attribute evaluation',
      'Expresses       "Finance analysts may read  "May read records in their',
      '                FIN-REPORTS"                 own department, in hours"',
      'Audit "who can  List the role members       Evaluate policy against',
      'do X?"          — easy                       every user — hard',
      'Scales badly    Role explosion when         Policy complexity when',
      'when            conditions multiply          rules interact',
      'Typical use     The backbone                A few conditions layered on',
      '',
      'Most real environments are RBAC with selective ABAC conditions. Pure ABAC',
      'is expressive and difficult to audit; pure RBAC is auditable and cannot',
      'express context.',
    ].join('\n'),
    teaches:
      'The deciding question is whether the rule depends on context. If it does — time, location, data classification, device — RBAC needs a role per combination, which is role explosion. That is when one ABAC condition is worth the complexity.',
  },
  {
    match: 'show pam model',
    tool: 'platform',
    provenance: 'simulated',
    output: [
      'Privileged access management — target model',
      '',
      'WITHOUT PAM                       WITH PAM',
      'Admin holds standing rights       Rights checked out just-in-time',
      'Admin knows the password          Credential vaulted, rotated on return',
      'Shared admin account              Individual named identity',
      'No session record                 Session recorded and attributable',
      'Compromise = standing domain admin Compromise = no privilege by default',
      '',
      'Elevation request example:',
      '  Requester   j.adeyemi (named)',
      '  Role        Domain admin',
      '  Duration    60 minutes, expires automatically',
      '  Approval    Second approver required',
      '  Recording   Session captured',
      '',
      'This directly addresses the Phase 2 shared-account failure: elevation is',
      'attributable to a person, so non-repudiation becomes possible.',
    ].join('\n'),
    teaches:
      'PAM changes privilege from something you have into something you check out. A phished workstation then yields no standing administrative rights, because nobody holds any — which is a structurally different security posture, not just a stronger one.',
  },
  {
    match: 'show orphaned accounts',
    tool: 'platform',
    provenance: 'prepared',
    output: [
      'Reconciliation — directory accounts vs identity platform',
      '',
      'ACCOUNT           IN DIRECTORY  IN IDENTITY PLATFORM  LAST LOGON   STATUS',
      'svc-backup-old    Yes           No                    2024-11-02   ORPHANED',
      'temp.contractor   Yes           No                    2026-01-18   ORPHANED',
      'j.fielding        Yes           No                    2025-07-30   ORPHANED',
      'priya.raman       Yes           Yes                   2026-09-07   OK',
      '',
      'Three accounts exist in the directory with no owning identity. No HR event',
      'will ever trigger their removal, because HR has no record of them.',
      '',
      'Reconciliation finds accounts NOBODY KNOWS ABOUT.',
      'Access review asks whether KNOWN access is still needed.',
      'They are different controls and neither substitutes for the other.',
    ].join('\n'),
    teaches:
      'Orphaned accounts survive every leaver process by construction — the process is triggered by HR, and HR has no record of them. They are found only by reconciling the directory against the authoritative source, which is why that is a separate scheduled control.',
  },
];
